name = "CauchyIntegralTheorem"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Main"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3
linter.style.emptyLine = false
linter.flexible = false
linter.style.multiGoal = false
linter.unusedTactic = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.30.0-rc2"

[[lean_lib]]
name = "Main"

[[lean_lib]]
name = "PiecewiseLinear"

[[lean_lib]]
name = "PiecewiseC1"

[[lean_lib]]
name = "ComplexCurveIntegral"

[[lean_lib]]
name = "Complex"

[[lean_lib]]
name = "Topology"

[[lean_lib]]
name = "IntervalIntegral"
