/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

Authors: Steven Creech, Jaume de Dios, Bogdan Georgiev, Harald Helfgott, Ayush Khaitan, Terence Tao

Thanks to ICERM for hosting the workshop "Formalization of Analysis" where most of this work
was conducted.
-/
module

public import Mathlib.Analysis.BoxIntegral.Stieltjes.Defs
public import Mathlib.Analysis.BoxIntegral.Partition.OrderedDivision
public import Mathlib.Topology.EMetricSpace.BoundedVariation
public import Mathlib.MeasureTheory.Integral.IntervalIntegral.Basic
public import Mathlib.Analysis.Calculus.ContDiff.Basic
public import Mathlib.MeasureTheory.Integral.IntervalIntegral.ContDiff
public import Mathlib.Analysis.Calculus.ContDiff.Defs
public import Mathlib.Analysis.Calculus.ContDiff.Deriv

/-! # Riemann–Stieltjes integral

In this file we establish fundamental properties of Riemann–Stieltjes integral
`∫⟨B⟩ x in a..b, f x ∂g` dfefined in `Analysis.BoxIntegral.Stieltjes.Defs`.

## Main theorems

* `BoxIntegral.Stieltjes.hasStieltjesIntegral_iff_lim_sum`: gives the textbook ε-δ characterization
of the Riemann--Stieltjes integral.
* `BoxIntegral.stieltjesIntegral.add_adjacent`: gives the splitting identity
  `∫⟨B⟩ x in a..c, f x ∂g = ∫⟨B⟩ x in a..b, f x ∂g + ∫⟨B⟩ x in b..c, f x ∂g`, regardless of
  the ordering of `a`, `b`, `c`.
* `BoxIntegral.exists_of_continuousOn_of_boundedVariationOn` (Theorem A.1): if `f` is continuous
  and `g` has bounded variation on `[a, b]`, then the Riemann–Stieltjes integral exists.
* `BoxIntegral.stieltjesIntegral.by_parts` (Theorem A.2): if `∫⟨B⟩ x in a..b, f x ∂g` exists, then
  so does `∫⟨B⟩ x in a..b, g x ∂f`, and the two are related by the integration by parts identity
  `∫⟨B⟩ x in a..b, g x ∂f = B (f b) (g b) - B (f a) (g a) - ∫⟨B⟩ x in a..b, f x ∂g`.
* `BoxIntegral.variation_of_derivative` (Theorem A.3(a)) and
  `BoxIntegral.integral_of_derivative` (Theorem A.3(b)): when `g` is `C¹`, the total variation
  and the Riemann–Stieltjes integral can be computed by `g′`.
* `BoxIntegral.integral_le_integral_of_variation` (Theorem A.4): a norm bound on the integral
  in terms of the variation of `g`.
* `BoxIntegral.stieltjesIntegral_eq_intervalIntegral_of_riemannIntegrable`: the Riemann-Stieltjes
integral `∫⟨lsmul ℝ ℝ⟩ x in a..b, f x ∂id` agrees with the interval integral
`∫ x in a..b, f x` when `f` is Riemann integrable.
* `BoxIntegral.sum_eq_integral_nat_floor` and `BoxIntegral.sum_eq_integral_int_floor`: relate
  sums `∑ f n` to Riemann–Stieltjes integrals against the floor function.
* `BoxIntegral.sum_eq_integral_natSummatory_le` / `_lt` : relate sums `∑ B (f n) (g n)` to
  Riemann–Stieltjes integrals against the right- or left-continuous summatory function
  `x ↦ ∑ n ≤ x, g n` (resp. `x ↦ ∑ n < x, g n`).

## AI usage

* Much of the boilerplate API and docstrings was generated by AI, which was prompted to follow
existing Mathlib examples and style guides.  They were reviewed by human authors, but in
several cases no substantive improvement to the AI-generated code was found.

* More mathematically complex theorems were largely proved by hand, though in some cases AI tools
were used to generate an initial proof structure (which was then often revised either by hand,
or by further conversation with the AI agent).

* AI was also used to generate initial text for docstrings.

## References

* H. L. Montgomery and R. C. Vaughan, *Multiplicative Number Theory I: Classical Theory*,
  Cambridge Studies in Advanced Mathematics 97, Cambridge University Press, 2007 (Appendix A).

## TODO

* Develop a higher-dimensional Stieltjes integral (exists in the literature, but is rarely used)
* Develop a Stieltjes integral based around `Ico` intervals rather than `Ioc` intervals
* Other variants of Stieltjes integration, such as the Henstock-Stieltjes integral
* Change of variables formula wrt monotone substitutions
* Interpretation of `ofDiff` as a measure (assuming monotonicity)
* Interpretation of `ofDiff` as a signed measure (assuming bounded variation).  This requires
the development of signed measures in Mathlib
* Example: decay of Fourier transforms of total variation functions

## Tags

Stieltjes integral, Riemann–Stieltjes, bounded variation
-/

@[expose] public section

open scoped BigOperators
open BoxIntegral

namespace BoxIntegral.TaggedDivision

namespace DualPartition

def x (π : TaggedDivision) : Fin (π.N + 2) → ℝ :=
  Fin.cons (π.x 0) (Fin.snoc π.tag (π.x (Fin.last π.N)))

@[simp]
theorem x_first (π : TaggedDivision) : x π 0 = π.x 0 := by
  simp [x]

@[simp]
theorem x_last (π : TaggedDivision) : x π (Fin.last (π.N + 1)) = π.x (Fin.last π.N) := by
  simp [x]

end DualPartition

def DualPartition (π : TaggedDivision) : TaggedDivision where
  N := π.N + 1
  tag := π.x
  x := DualPartition.x π

@[simp]
theorem DualPartition_first (π : TaggedDivision) : π.DualPartition.x 0 = π.x 0 := by
  exact DualPartition.x_first π

@[simp]
theorem DualPartition_last (π : TaggedDivision) :
    π.DualPartition.x (Fin.last π.DualPartition.N) = π.x (Fin.last π.N) := by
  exact DualPartition.x_last π

def RiemannStieltjesSum (π : TaggedDivision) (f g : ℝ → ℝ) : ℝ :=
  ∑ i : Fin π.N, f (π.tag i) * (g (π.x i.succ) - g (π.x i.castSucc))

end BoxIntegral.TaggedDivision


namespace BoxIntegral.TaggedDivision.RiemannStieltjesSum

@[simp]
theorem eq_zero_of_N_eq_zero (π : TaggedDivision) (hπ : π.N = 0) (f g : ℝ → ℝ) :
    π.RiemannStieltjesSum f g = 0 := by
  rcases π with ⟨⟨N, x⟩, tag⟩
  dsimp at hπ ⊢
  subst N
  simp [TaggedDivision.RiemannStieltjesSum]

theorem eq_dropLast_add
    (π : TaggedDivision) (hN : 0 < π.N) (f g : ℝ → ℝ) :
      π.RiemannStieltjesSum f g =
      π.dropLast.RiemannStieltjesSum f g +
      f (π.tag ⟨π.N - 1, by omega⟩) *
        (g (π.x (Fin.last π.N)) - g (π.x ⟨π.N - 1, by omega⟩)) := by
  rcases π with ⟨⟨N, x⟩, tag⟩
  dsimp [RiemannStieltjesSum, dropLast] at hN ⊢
  cases N with
  | zero => omega
  | succ n =>
      rw [Fin.sum_univ_castSucc]
      congr

theorem snoc (π : TaggedDivision) (c t : ℝ) (f g : ℝ → ℝ) :
    (π.snoc c t).RiemannStieltjesSum  f g =
      π.RiemannStieltjesSum  f g + f t * (g c - g (π.x (Fin.last π.N))) := by
  rcases π with ⟨⟨N, x⟩, tag⟩
  dsimp [RiemannStieltjesSum, TaggedDivision.snoc, BoxIntegral.OrderedDivision.snoc]
  rw [Fin.sum_univ_castSucc]
  congr 1
  · apply Finset.sum_congr rfl
    intro i hi
    have hs : i.castSucc.succ = i.succ.castSucc := by ext; simp
    have hxs : @Fin.snoc (N + 1) (fun _ => ℝ) x c i.castSucc.succ = x i.succ := by
      rw [hs, Fin.snoc_castSucc]
    rw [hxs]
    simp [Fin.snoc_castSucc]
  · simp [Fin.snoc_last, Fin.snoc_castSucc]

theorem removeDuplicates
    (π : TaggedDivision) (f g : ℝ → ℝ) :
    π.removeDuplicates.RiemannStieltjesSum f g =
      π.RiemannStieltjesSum f g := by
  revert f g
  induction π using TaggedDivision.recOnDropLast with
  | zero π h0 =>
    intro f g
    rw [TaggedDivision.removeDuplicates.of_N_eq_zero π h0]
  | step π hN ih =>
    intro f g
    have h0 : ¬π.N = 0 := by omega
    let y := π.x ⟨π.N - 1, by omega⟩
    let z := π.x (Fin.last π.N)
    let t := π.tag ⟨π.N - 1, by omega⟩
    let σ := π.dropLast.removeDuplicates
    have hσ_last : σ.x (Fin.last σ.N) = y := by
      dsimp [σ]
      rw [TaggedDivision.removeDuplicates.last π.dropLast]
      exact π.dropLast_last
    have hrec :
        σ.RiemannStieltjesSum f g =
          π.dropLast.RiemannStieltjesSum f g := by
      dsimp [σ]
      exact ih f g
    have hdrop := eq_dropLast_add π hN f g
    by_cases h : y = z
    · rw [TaggedDivision.removeDuplicates.of_last_eq π hN (by simpa [y, z] using h)]
      rw [hrec, hdrop]
      simp [y, z, h]
    · rw [TaggedDivision.removeDuplicates.of_last_ne π hN (by simpa [y, z] using h)]
      rw [snoc σ z t f g, hrec, hdrop]
      simp [hσ_last, y, z, t]

theorem by_parts (π : TaggedDivision) (f g : ℝ → ℝ) :
    π.RiemannStieltjesSum f g =
      (π.DualPartition).RiemannStieltjesSum g f := by sorry

end BoxIntegral.TaggedDivision.RiemannStieltjesSum
namespace mynamespace

/-! ## One-dimensional interval partitions

API for one-dimensional partitions and tagged partitions
-/

open BoxIntegral

noncomputable def toPartition {N : ℕ} {a b : ℝ}
    (x : Fin (N + 1) → ℝ) (hx : StrictMono x)
    (ha : (x 0) = a) (hb : x (Fin.last N) = b) : Prepartition (Ioc a b) where
      boxes := (Finset.univ : Finset (Fin N)).map
        ⟨fun i ↦ Ioc (x i.castSucc) (x i.succ), by sorry⟩
      le_of_mem' := by sorry
      pairwiseDisjoint := by sorry

noncomputable def toTaggedPartition {N : ℕ} {a b : ℝ}
    (x : Fin (N + 1) → ℝ) (hx : StrictMono x)
    (y : Fin N → ℝ) (hy : ∀ i : Fin N,  (x i.castSucc ≤ y i) ∧ (y i ≤ x i.succ))
    (ha : (x 0) = a) (hb : x (Fin.last N) = b) :
    TaggedPrepartition (Ioc a b) :=
    {toPartition x hx ha hb with
      tag := by
        classical
        exact fun J _ ↦
          if h : ∃ i : Fin N, Ioc (x i.castSucc) (x i.succ) = J then y h.choose else a
      tag_mem_Icc := by sorry
    }


theorem toPartition_isPartition {N : ℕ} {a b : ℝ} (hab : a < b)
    (x : Fin (N + 1) → ℝ) (hx : StrictMono x)
    (ha : (x 0) = a) (hb : x (Fin.last N) = b) :
    (toPartition x hx ha hb).IsPartition := by
  sorry


theorem fromPartition
    {a b : ℝ} (hab : a < b)
    (π : Prepartition (Ioc a b))
    (hπ : π.IsPartition) :
    letI N := Finset.card π.boxes
    ∃ (x : Fin (N + 1) → ℝ) (hx : StrictMono x) (ha : (x 0) = a) (hb : x (Fin.last N) = b),
     π = toPartition x hx ha hb := by
  sorry

theorem fromTaggedPartition
    {a b : ℝ} (hab : a < b)
    (π : TaggedPrepartition (Ioc a b))
    (hπ : π.IsPartition) :
    ∃ (N : ℕ) (x : Fin (N + 1) → ℝ) (hx : StrictMono x)
      (ha : (x 0) = a) (hb : x (Fin.last N) = b)
      (y : Fin N → ℝ) (hy : ∀ i : Fin N, (x i.castSucc ≤ y i) ∧ (y i ≤ x i.succ)),
      π.toPrepartition = toPartition x hx ha hb ∧
        ∀ i : Fin N, y i = π.tag (Ioc (x i.castSucc) (x i.succ)) 0 := by
  sorry

open TaggedPrepartition
variable {E : Type} {F : Type} [NormedAddCommGroup E] [NormedSpace ℝ E]
  [NormedAddCommGroup F] [NormedSpace ℝ F]

theorem taggedSum_eq_integralSum {N : ℕ} {a b : ℝ} (hab : a < b)
    (x : Fin (N + 1) → ℝ) (hx : StrictMono x)
    (y : Fin N → ℝ) (hy : ∀ i : Fin N,  (x i.castSucc ≤ y i) ∧ (y i ≤ x i.succ))
    (ha : (x 0) = a) (hb : x (Fin.last N) = b)
    (vol : (Fin 1) →ᵇᵃ E →L[ℝ] F)
    (f :  ℝ → E):
    integralSum (fun x => (f (x 1))) vol (toTaggedPartition x hx y hy ha hb) =
      Finset.sum (Finset.univ)
        (fun i: Fin N ↦ (vol (Ioc (x i.succ) (x i.castSucc))) (f (y i))) := by
  sorry

end mynamespace

open BoxIntegral ContinuousLinearMap

namespace BoxIntegral

variable {E : Type*} {F : Type*} {G : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
  [NormedAddCommGroup F] [NormedSpace ℝ F] [NormedAddCommGroup G] [NormedSpace ℝ G]
variable (a b : ℝ) (B : E →L[ℝ] F →L[ℝ] G)

/-- The predicate `HasStieltjesIntegral` matches the usual epsilon-delta definition, at least if
one uses unordered partitions of the interval. -/
theorem hasStieltjesIntegral_iff_lim_sum {a b : ℝ} (hab : a < b) (f : ℝ → E) (g : ℝ → F) (L : G) :
    HasStieltjesIntegral a b B f g L ↔
    ∀ ε > 0, ∃ δ > 0, ∀ π : TaggedPrepartition (Ioc a b), π.IsHenstock → π.IsPartition
    → π.mesh_size ≤ δ →
     dist (∑ x ∈ π.boxes, ((B (f (π.tag x 0))) (g (x.upper 0) - g (x.lower 0)))) L < ε := by
  simp only [HasStieltjesIntegral.of_lt, hab, HasStieltjesIntegral', Fin.isValue,
  HasIntegral_Riemann_iff, gt_iff_lt, integralSum,
    BoxAdditiveMap.ofDiff_apply, coe_sub', Pi.sub_apply, flip_apply, Finset.sum_sub_distrib,
    dist_sub_eq_dist_add_left, map_sub]

theorem hasRiemannIntegral_iff_lim_sum {a b : ℝ} (hab : a < b) (f : ℝ → E) (L : E) :
    HasRiemannIntegral a b f L ↔
    ∀ ε > 0, ∃ δ > 0, ∀ π : TaggedPrepartition (Ioc a b), π.IsHenstock → π.IsPartition
    → π.mesh_size ≤ δ →
     dist (∑ x ∈ π.boxes, ((x.upper 0) - (x.lower 0)) • (f (π.tag x 0))) L < ε := by
  rw [HasRiemannIntegral]
  exact hasStieltjesIntegral_iff_lim_sum _ hab _ _ _

section Linearity

/-! ## Linearity

The provided API demonstrates that the Riemann--Stieltjes integral `∫⟨B⟩ x in a..b, f x ∂g` is
linear in each of the inputs `f`,`g`, `B`.
-/

variable {a b : ℝ} {B B₁ B₂ : E →L[ℝ] F →L[ℝ] G} {f f₁ f₂ : ℝ → E} {g g₁ g₂ : ℝ → F} {L L₁ L₂ : G}

/-! ### In the integrand -/

private theorem HasStieltjesIntegral'.zero_left : HasStieltjesIntegral' a b B 0 g 0 :=
  hasIntegral_zero

@[simp]
theorem HasStieltjesIntegral.zero_left : HasStieltjesIntegral a b B 0 g 0 := by
  rcases lt_trichotomy a b with h | rfl | h
  · simp only [of_lt, h, HasStieltjesIntegral'.zero_left]
  · simp
  rw [symm_iff]
  simp only [neg_zero, h, of_lt, HasStieltjesIntegral'.zero_left]

@[simp]
theorem StieltjesIntegrable.zero_left : StieltjesIntegrable a b B 0 g :=
  HasStieltjesIntegral.zero_left.stieltjesIntegrable

@[simp]
theorem stieltjesIntegral_zero_left : ∫⟨B⟩ _ in a..b, 0 ∂g = 0 :=
  HasStieltjesIntegral.zero_left.stieltjesIntegral_eq

private theorem HasStieltjesIntegral'.add_left
    (h₁ : HasStieltjesIntegral' a b B f₁ g L₁) (h₂ : HasStieltjesIntegral' a b B f₂ g L₂) :
    HasStieltjesIntegral' a b B (f₁ + f₂) g (L₁ + L₂) :=
  HasIntegral.add h₁ h₂

theorem HasStieltjesIntegral.add_left
    (h₁ : HasStieltjesIntegral a b B f₁ g L₁) (h₂ : HasStieltjesIntegral a b B f₂ g L₂) :
    HasStieltjesIntegral a b B (f₁ + f₂) g (L₁ + L₂) := by
  rcases lt_trichotomy a b with h | rfl | h
  · simp only [of_lt, h] at h₁ h₂ ⊢
    exact h₁.add_left h₂
  · simp_all
  rw [symm_iff] at h₁ h₂ ⊢
  simp only [h, of_lt, neg_add] at h₁ h₂ ⊢
  exact h₁.add_left h₂

theorem StieltjesIntegrable.add_left
    (h₁ : StieltjesIntegrable a b B f₁ g) (h₂ : StieltjesIntegrable a b B f₂ g) :
    StieltjesIntegrable a b B (f₁ + f₂) g :=
  (h₁.hasStieltjesIntegral.add_left h₂.hasStieltjesIntegral).stieltjesIntegrable

@[simp]
theorem stieltjesIntegral_add_left
    (h₁ : StieltjesIntegrable a b B f₁ g) (h₂ : StieltjesIntegrable a b B f₂ g) :
    ∫⟨B⟩ x in a..b, (f₁ + f₂) x ∂g
      = ∫⟨B⟩ x in a..b, f₁ x ∂g + ∫⟨B⟩ x in a..b, f₂ x ∂g := by
  rw [(h₁.hasStieltjesIntegral.add_left h₂.hasStieltjesIntegral).stieltjesIntegral_eq,
    h₁.hasStieltjesIntegral.stieltjesIntegral_eq,
    h₂.hasStieltjesIntegral.stieltjesIntegral_eq]

private theorem HasStieltjesIntegral'.neg_left (h : HasStieltjesIntegral' a b B f g L) :
    HasStieltjesIntegral' a b B (-f) g (-L) :=
  HasIntegral.neg h

theorem HasStieltjesIntegral.neg_left (h : HasStieltjesIntegral a b B f g L) :
    HasStieltjesIntegral a b B (-f) g (-L) := by
  rcases lt_trichotomy a b with hab | rfl | hab
  · simp only [of_lt, hab] at h ⊢
    apply h.neg_left
  · simp_all
  rw [symm_iff] at h ⊢
  simp only [hab, of_lt] at h ⊢
  apply h.neg_left

theorem StieltjesIntegrable.neg_left
  (h : StieltjesIntegrable a b B f g) : StieltjesIntegrable a b B (-f) g :=
  h.hasStieltjesIntegral.neg_left.stieltjesIntegrable

@[simp]
theorem stieltjesIntegral_neg_left (h : StieltjesIntegrable a b B f g) :
    ∫⟨B⟩ x in a..b, (-f) x ∂g = -∫⟨B⟩ x in a..b, f x ∂g :=
  h.hasStieltjesIntegral.neg_left.stieltjesIntegral_eq

private theorem HasStieltjesIntegral'.sub_left
    (h₁ : HasStieltjesIntegral' a b B f₁ g L₁) (h₂ : HasStieltjesIntegral' a b B f₂ g L₂) :
    HasStieltjesIntegral' a b B (f₁ - f₂) g (L₁ - L₂) :=
  HasIntegral.sub h₁ h₂

theorem HasStieltjesIntegral.sub_left
    (h₁ : HasStieltjesIntegral a b B f₁ g L₁) (h₂ : HasStieltjesIntegral a b B f₂ g L₂) :
    HasStieltjesIntegral a b B (f₁ - f₂) g (L₁ - L₂) := by
  rcases lt_trichotomy a b with h | rfl | h
  · simp only [of_lt, h] at h₁ h₂ ⊢
    exact h₁.sub_left h₂
  · simp_all
  rw [symm_iff] at h₁ h₂ ⊢
  simp only [h, of_lt] at h₁ h₂ ⊢
  convert h₁.sub_left h₂ using 1
  abel

theorem StieltjesIntegrable.sub_left
    (h₁ : StieltjesIntegrable a b B f₁ g) (h₂ : StieltjesIntegrable a b B f₂ g) :
    StieltjesIntegrable a b B (f₁ - f₂) g :=
  (h₁.hasStieltjesIntegral.sub_left h₂.hasStieltjesIntegral).stieltjesIntegrable

@[simp]
theorem stieltjesIntegral_sub_left
    (h₁ : StieltjesIntegrable a b B f₁ g) (h₂ : StieltjesIntegrable a b B f₂ g) :
    ∫⟨B⟩ x in a..b, (f₁ - f₂) x ∂g
      = ∫⟨B⟩ x in a..b, f₁ x ∂g - ∫⟨B⟩ x in a..b, f₂ x ∂g := by
  rw [(h₁.hasStieltjesIntegral.sub_left h₂.hasStieltjesIntegral).stieltjesIntegral_eq,
    h₁.hasStieltjesIntegral.stieltjesIntegral_eq,
    h₂.hasStieltjesIntegral.stieltjesIntegral_eq]

private theorem HasStieltjesIntegral'.smul_left (h : HasStieltjesIntegral' a b B f g L) (c : ℝ) :
    HasStieltjesIntegral' a b B (c • f) g (c • L) :=
  HasIntegral.smul h c

theorem HasStieltjesIntegral.smul_left (h : HasStieltjesIntegral a b B f g L) (c : ℝ) :
    HasStieltjesIntegral a b B (c • f) g (c • L) := by
  rcases lt_trichotomy a b with hab | rfl | hab
  · simp only [of_lt, hab] at h ⊢
    apply h.smul_left
  · simp_all
  rw [symm_iff] at h ⊢
  simp only [hab, of_lt] at h ⊢
  convert h.smul_left _ using 1
  norm_num

theorem StieltjesIntegrable.smul_left
    (h : StieltjesIntegrable a b B f g) (c : ℝ) : StieltjesIntegrable a b B (c • f) g :=
  (h.hasStieltjesIntegral.smul_left c).stieltjesIntegrable

@[simp]
theorem stieltjesIntegral_smul_left
    (h : StieltjesIntegrable a b B f g) (c : ℝ) :
    ∫⟨B⟩ x in a..b, (c • f) x ∂g = c • ∫⟨B⟩ x in a..b, f x ∂g :=
  (h.hasStieltjesIntegral.smul_left c).stieltjesIntegral_eq

/-! ### In the integrator -/

private theorem HasStieltjesIntegral'.const_right (c : F) :
    HasStieltjesIntegral' a b B f (fun _ ↦ c) 0 := by
  simp only [HasStieltjesIntegral', Fin.isValue, BoxAdditiveMap.ofDiff_const, hasIntegral_zero_vol]

@[simp]
theorem HasStieltjesIntegral.const_right (c : F) :
    HasStieltjesIntegral a b B f (fun _ ↦ c) 0 := by
  rcases lt_trichotomy a b with hab | rfl | hab
  · simp only [of_lt, hab] at ⊢
    apply HasStieltjesIntegral'.const_right
  · simp_all
  rw [symm_iff] at ⊢
  simp only [neg_zero, hab, of_lt] at ⊢
  apply HasStieltjesIntegral'.const_right

@[simp]
theorem HasStieltjesIntegral.zero_right : HasStieltjesIntegral a b B f 0 0 :=
  const_right 0

@[simp]
theorem StieltjesIntegrable.const_right (c : F) :
    StieltjesIntegrable a b B f (fun _ ↦ c) :=
  (HasStieltjesIntegral.const_right c).stieltjesIntegrable

@[simp]
theorem StieltjesIntegrable.zero_right : StieltjesIntegrable a b B f 0 :=
  const_right 0

@[simp]
theorem stieltjesIntegral_const_right (c : F) : ∫⟨B⟩ x in a..b, f x ∂(fun _ ↦ c) = 0 :=
  (HasStieltjesIntegral.const_right c).stieltjesIntegral_eq

@[simp]
theorem stieltjesIntegral_zero_right : ∫⟨B⟩ x in a..b, f x ∂0 = 0 :=
  stieltjesIntegral_const_right 0

private theorem HasStieltjesIntegral'.add_right
    (h₁ : HasStieltjesIntegral' a b B f g₁ L₁) (h₂ : HasStieltjesIntegral' a b B f g₂ L₂) :
    HasStieltjesIntegral' a b B f (g₁ + g₂) (L₁ + L₂) := by
  unfold HasStieltjesIntegral' at h₁ h₂ ⊢
  have h : (fun x : ℝ ↦ B.flip ((g₁ + g₂) x)) =
      (fun x ↦ B.flip (g₁ x)) + (fun x ↦ B.flip (g₂ x)) := by ext; simp
  rw [h, map_add]
  exact h₁.add_vol h₂

theorem HasStieltjesIntegral.add_right
    (h₁ : HasStieltjesIntegral a b B f g₁ L₁) (h₂ : HasStieltjesIntegral a b B f g₂ L₂) :
    HasStieltjesIntegral a b B f (g₁ + g₂) (L₁ + L₂) := by
  rcases lt_trichotomy a b with hab | rfl | hab
  · simp only [of_lt, hab] at h₁ h₂ ⊢
    exact h₁.add_right h₂
  · simp_all
  rw [symm_iff] at h₁ h₂ ⊢
  simp only [hab, of_lt] at h₁ h₂ ⊢
  convert h₁.add_right h₂ using 1
  abel

theorem StieltjesIntegrable.add_right
    (h₁ : StieltjesIntegrable a b B f g₁) (h₂ : StieltjesIntegrable a b B f g₂) :
    StieltjesIntegrable a b B f (g₁ + g₂) :=
  (h₁.hasStieltjesIntegral.add_right h₂.hasStieltjesIntegral).stieltjesIntegrable

@[simp]
theorem stieltjesIntegral_add_right
    (h₁ : StieltjesIntegrable a b B f g₁) (h₂ : StieltjesIntegrable a b B f g₂) :
    ∫⟨B⟩ x in a..b, f x ∂(g₁ + g₂)
      = ∫⟨B⟩ x in a..b, f x ∂g₁ + ∫⟨B⟩ x in a..b, f x ∂g₂ :=
    (h₁.hasStieltjesIntegral.add_right h₂.hasStieltjesIntegral).stieltjesIntegral_eq

private theorem HasStieltjesIntegral'.neg_right
    {f : ℝ → E} {g : ℝ → F} {L : G} (h : HasStieltjesIntegral' a b B f g L) :
    HasStieltjesIntegral' a b B f (-g) (-L) := by
  unfold HasStieltjesIntegral' at h ⊢
  have heq : (fun x : ℝ ↦ B.flip ((-g) x)) = -(fun x ↦ B.flip (g x)) := by ext; simp
  rw [heq, map_neg]
  exact h.neg_vol

theorem HasStieltjesIntegral.neg_right (h : HasStieltjesIntegral a b B f g L) :
    HasStieltjesIntegral a b B f (-g) (-L) := by
  rcases lt_trichotomy a b with hab | rfl | hab
  · simp only [of_lt, hab] at h ⊢
    apply h.neg_right
  · simp_all
  rw [symm_iff] at h ⊢
  simp only [hab, of_lt, neg_neg] at h ⊢
  convert h.neg_right using 1
  norm_num

theorem StieltjesIntegrable.neg_right
    (h : StieltjesIntegrable a b B f g) : StieltjesIntegrable a b B f (-g) :=
  h.hasStieltjesIntegral.neg_right.stieltjesIntegrable

@[simp]
theorem stieltjesIntegral_neg_right
    (h : StieltjesIntegrable a b B f g) :
    ∫⟨B⟩ x in a..b, f x ∂(-g) = -∫⟨B⟩ x in a..b, f x ∂g :=
  h.hasStieltjesIntegral.neg_right.stieltjesIntegral_eq

theorem HasStieltjesIntegral'.sub_right
    (h₁ : HasStieltjesIntegral' a b B f g₁ L₁) (h₂ : HasStieltjesIntegral' a b B f g₂ L₂) :
    HasStieltjesIntegral' a b B f (g₁ - g₂) (L₁ - L₂) := by
  unfold HasStieltjesIntegral' at h₁ h₂ ⊢
  have h : (fun x : ℝ ↦ B.flip ((g₁ - g₂) x)) =
      (fun x ↦ B.flip (g₁ x)) - (fun x ↦ B.flip (g₂ x)) := by ext; simp
  rw [h, map_sub]
  exact h₁.sub_vol h₂

theorem HasStieltjesIntegral.sub_right
    (h₁ : HasStieltjesIntegral a b B f g₁ L₁) (h₂ : HasStieltjesIntegral a b B f g₂ L₂) :
    HasStieltjesIntegral a b B f (g₁ - g₂) (L₁ - L₂) := by
  rcases lt_trichotomy a b with hab | rfl | hab
  · simp only [of_lt, hab] at h₁ h₂ ⊢
    exact h₁.sub_right h₂
  · simp_all
  rw [symm_iff] at h₁ h₂ ⊢
  simp only [hab, of_lt] at h₁ h₂ ⊢
  convert h₁.sub_right h₂ using 1
  abel

theorem StieltjesIntegrable.sub_right
    (h₁ : StieltjesIntegrable a b B f g₁) (h₂ : StieltjesIntegrable a b B f g₂) :
    StieltjesIntegrable a b B f (g₁ - g₂) :=
  (h₁.hasStieltjesIntegral.sub_right h₂.hasStieltjesIntegral).stieltjesIntegrable

@[simp]
theorem stieltjesIntegral_sub_right
    (h₁ : StieltjesIntegrable a b B f g₁) (h₂ : StieltjesIntegrable a b B f g₂) :
    ∫⟨B⟩ x in a..b, f x ∂(g₁ - g₂)
      = ∫⟨B⟩ x in a..b, f x ∂g₁ - ∫⟨B⟩ x in a..b, f x ∂g₂ :=
  (h₁.hasStieltjesIntegral.sub_right h₂.hasStieltjesIntegral).stieltjesIntegral_eq

private theorem HasStieltjesIntegral'.smul_right (h : HasStieltjesIntegral' a b B f g L) (c : ℝ) :
    HasStieltjesIntegral' a b B f (c • g) (c • L) := by
  unfold HasStieltjesIntegral' at h ⊢
  have heq : (fun x : ℝ ↦ B.flip ((c • g) x)) = c • (fun x ↦ B.flip (g x)) := by ext; simp
  rw [heq, BoxIntegral.BoxAdditiveMap.ofDiff_smul]
  exact h.smul_vol c

theorem HasStieltjesIntegral.smul_right (h : HasStieltjesIntegral a b B f g L) (c : ℝ) :
    HasStieltjesIntegral a b B f (c • g) (c • L) := by
  rcases lt_trichotomy a b with hab | rfl | hab
  · simp only [of_lt, hab] at h ⊢
    apply h.smul_right
  · simp_all
  rw [symm_iff] at h ⊢
  simp only [hab, of_lt] at h ⊢
  convert h.smul_right _ using 1
  norm_num

theorem StieltjesIntegrable.smul_right (h : StieltjesIntegrable a b B f g) (c : ℝ) :
    StieltjesIntegrable a b B f (c • g) :=
  (h.hasStieltjesIntegral.smul_right c).stieltjesIntegrable

@[simp]
theorem stieltjesIntegral_smul_right
    (h : StieltjesIntegrable a b B f g) (c : ℝ) :
    ∫⟨B⟩ x in a..b, f x ∂(c • g) = c • ∫⟨B⟩ x in a..b, f x ∂g :=
  (h.hasStieltjesIntegral.smul_right c).stieltjesIntegral_eq

/-! ### In the bilinear form -/

private theorem HasStieltjesIntegral'.zero_bil : HasStieltjesIntegral' a b 0 f g (0 : G) := by
  simp [HasStieltjesIntegral', hasIntegral_zero_vol]

@[simp]
theorem HasStieltjesIntegral.zero_bil : HasStieltjesIntegral a b 0 f g (0 : G) := by
  rcases lt_trichotomy a b with hab | rfl | hab
  · simp only [of_lt, hab] at ⊢
    apply HasStieltjesIntegral'.zero_bil
  · simp_all
  rw [symm_iff] at ⊢
  simp only [neg_zero, hab, of_lt] at ⊢
  apply HasStieltjesIntegral'.zero_bil

@[simp]
theorem StieltjesIntegrable.zero_bil : StieltjesIntegrable (G := G) a b 0 f g :=
  HasStieltjesIntegral.zero_bil.stieltjesIntegrable

@[simp]
theorem stieltjesIntegral_zero_bil : ∫⟨0⟩ x in a..b, f x ∂g = (0 : G) :=
  HasStieltjesIntegral.zero_bil.stieltjesIntegral_eq

private theorem HasStieltjesIntegral'.add_bil
    (h₁ : HasStieltjesIntegral' a b B₁ f g L₁) (h₂ : HasStieltjesIntegral' a b B₂ f g L₂) :
    HasStieltjesIntegral' a b (B₁ + B₂) f g (L₁ + L₂) := by
  unfold HasStieltjesIntegral' at h₁ h₂ ⊢
  have h : (fun x : ℝ ↦ (B₁ + B₂).flip (g x)) =
      (fun x ↦ B₁.flip (g x)) + (fun x ↦ B₂.flip (g x)) := by ext; simp
  rw [h, map_add]
  exact h₁.add_vol h₂

@[simp]
theorem HasStieltjesIntegral.add_bil
    (h₁ : HasStieltjesIntegral a b B₁ f g L₁) (h₂ : HasStieltjesIntegral a b B₂ f g L₂) :
    HasStieltjesIntegral a b (B₁ + B₂) f g (L₁ + L₂) := by
  rcases lt_trichotomy a b with hab | rfl | hab
  · simp only [of_lt, hab] at h₁ h₂ ⊢
    exact h₁.add_bil h₂
  · simp_all
  rw [symm_iff] at h₁ h₂ ⊢
  simp only [hab, of_lt] at h₁ h₂ ⊢
  convert h₁.add_bil h₂ using 1
  abel

private theorem HasStieltjesIntegral'.neg_bil
    {f : ℝ → E} {g : ℝ → F} {L : G} (h : HasStieltjesIntegral' a b B f g L) :
    HasStieltjesIntegral' a b (-B) f g (-L) := by
  unfold HasStieltjesIntegral' at h ⊢
  have heq : (fun x : ℝ ↦ (-B).flip (g x)) = -(fun x ↦ B.flip (g x)) := by ext; simp
  rw [heq, map_neg]
  exact h.neg_vol

theorem HasStieltjesIntegral.neg_bil (h : HasStieltjesIntegral a b B f g L) :
    HasStieltjesIntegral a b (-B) f g (-L) := by
  rcases lt_trichotomy a b with hab | rfl | hab
  · simp only [of_lt, hab] at h ⊢
    apply h.neg_bil
  · simp_all
  rw [symm_iff] at h ⊢
  simp only [hab, of_lt, neg_neg] at h ⊢
  convert h.neg_bil using 1
  norm_num

@[simp]
theorem stieltjesIntegral_neg_bil
    (h : StieltjesIntegrable a b B f g) :
    ∫⟨-B⟩ x in a..b, f x ∂g = -∫⟨B⟩ x in a..b, f x ∂g :=
  h.hasStieltjesIntegral.neg_bil.stieltjesIntegral_eq

theorem HasStieltjesIntegral'.sub_bil
    (h₁ : HasStieltjesIntegral' a b B₁ f g L₁) (h₂ : HasStieltjesIntegral' a b B₂ f g L₂) :
    HasStieltjesIntegral' a b (B₁ - B₂) f g (L₁ - L₂) := by
  unfold HasStieltjesIntegral' at h₁ h₂ ⊢
  have h : (fun x : ℝ ↦ (B₁ - B₂).flip (g x)) =
      (fun x ↦ B₁.flip (g x)) - (fun x ↦ B₂.flip (g x)) := by ext; simp
  rw [h, map_sub]
  exact h₁.sub_vol h₂

theorem HasStieltjesIntegral.sub_bil
    (h₁ : HasStieltjesIntegral a b B₁ f g L₁) (h₂ : HasStieltjesIntegral a b B₂ f g L₂) :
    HasStieltjesIntegral a b (B₁ - B₂) f g (L₁ - L₂) := by
  rcases lt_trichotomy a b with hab | rfl | hab
  · simp only [of_lt, hab] at h₁ h₂ ⊢
    exact h₁.sub_bil h₂
  · simp_all
  rw [symm_iff] at h₁ h₂ ⊢
  simp only [hab, of_lt] at h₁ h₂ ⊢
  convert h₁.sub_bil h₂ using 1
  abel

theorem StieltjesIntegrable.sub_bil
    (h₁ : StieltjesIntegrable a b B₁ f g) (h₂ : StieltjesIntegrable a b B₂ f g) :
    StieltjesIntegrable a b (B₁ - B₂) f g :=
  (h₁.hasStieltjesIntegral.sub_bil h₂.hasStieltjesIntegral).stieltjesIntegrable

@[simp]
theorem stieltjesIntegral_sub_bil
    (h₁ : StieltjesIntegrable a b B₁ f g) (h₂ : StieltjesIntegrable a b B₂ f g) :
    ∫⟨B₁ - B₂⟩ x in a..b, f x ∂g
      = ∫⟨B₁⟩ x in a..b, f x ∂g - ∫⟨B₂⟩ x in a..b, f x ∂g :=
  (h₁.hasStieltjesIntegral.sub_bil h₂.hasStieltjesIntegral).stieltjesIntegral_eq

private theorem HasStieltjesIntegral'.smul_bil (h : HasStieltjesIntegral' a b B f g L) (c : ℝ) :
    HasStieltjesIntegral' a b (c • B) f g (c • L) := by
  unfold HasStieltjesIntegral' at h ⊢
  have heq : (fun x : ℝ ↦ (c • B).flip (g x)) = c • (fun x ↦ B.flip (g x)) := by ext; simp
  rw [heq, BoxIntegral.BoxAdditiveMap.ofDiff_smul]
  exact h.smul_vol c

theorem HasStieltjesIntegral.smul_bil (h : HasStieltjesIntegral a b B f g L) (c : ℝ) :
    HasStieltjesIntegral a b (c • B) f g (c • L) := by
  rcases lt_trichotomy a b with hab | rfl | hab
  · simp only [of_lt, hab] at h ⊢
    apply h.smul_bil
  · simp_all
  rw [symm_iff] at h ⊢
  simp only [hab, of_lt] at h ⊢
  convert h.smul_bil _ using 1
  norm_num

theorem StieltjesIntegrable.smul_bil (h : StieltjesIntegrable a b B f g) (c : ℝ) :
    StieltjesIntegrable a b (c • B) f g :=
  (h.hasStieltjesIntegral.smul_bil c).stieltjesIntegrable

@[simp]
theorem stieltjesIntegral_smul_bil
    (h : StieltjesIntegrable a b B f g) (c : ℝ) :
    ∫⟨c • B⟩ x in a..b, f x ∂g = c • ∫⟨B⟩ x in a..b, f x ∂g :=
  (h.hasStieltjesIntegral.smul_bil c).stieltjesIntegral_eq

end Linearity

section Naturality

/-! ## Naturality: transporting along continuous linear maps -/

variable {E' F' G' : Type*} [NormedAddCommGroup E'] [NormedSpace ℝ E']
    [NormedAddCommGroup F'] [NormedSpace ℝ F'] [NormedAddCommGroup G'] [NormedSpace ℝ G']
    {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G} {f : ℝ → E} {g : ℝ → F} {L : G}
    {φ : E →L[ℝ] E'} {ψ : F →L[ℝ] F'} {Ψ : G →L[ℝ] G'}
    {B' : E' →L[ℝ] F' →L[ℝ] G'}

private theorem HasStieltjesIntegral'.map (hB : ∀ e y, Ψ (B e y) = B' (φ e) (ψ y))
    (h : HasStieltjesIntegral' a b B f g L) :
    HasStieltjesIntegral' a b B' (fun x ↦ φ (f x)) (fun x ↦ ψ (g x)) (Ψ L) := by
  unfold HasStieltjesIntegral' at h ⊢
  refine HasIntegral.map φ Ψ ?_ h
  intros
  simp only [BoxAdditiveMap.ofDiff_apply, sub_apply, flip_apply, map_sub, hB]

/-- If a bilinear pairing `B : E →L[ℝ] F →L[ℝ] G` and CLMs `φ : E →L[ℝ] E'`, `ψ : F →L[ℝ] F'`,
`Ψ : G →L[ℝ] G'` satisfy the compatibility `Ψ (B e y) = B' (φ e) (ψ y)` for all `e, y`, then
`HasStieltjesIntegral` transports along `(φ, ψ, Ψ)`: applying `φ` to the integrand, `ψ` to the
integrator and `Ψ` to the integral preserves the Stieltjes-integral relation. -/
theorem HasStieltjesIntegral.map (hB : ∀ e y, Ψ (B e y) = B' (φ e) (ψ y))
    (h : HasStieltjesIntegral a b B f g L) :
    HasStieltjesIntegral a b B' (fun x ↦ φ (f x)) (fun x ↦ ψ (g x)) (Ψ L) := by
  rcases lt_trichotomy a b with hab | rfl | hab
  · simp only [of_lt, hab] at h ⊢
    exact h.map hB
  · simp_all
  rw [symm_iff] at h ⊢
  simp only [hab, of_lt] at h ⊢
  convert h.map hB using 1
  simp

theorem StieltjesIntegrable.map (hB : ∀ e y, Ψ (B e y) = B' (φ e) (ψ y))
    (h : StieltjesIntegrable a b B f g) :
    StieltjesIntegrable a b B' (fun x ↦ φ (f x)) (fun x ↦ ψ (g x)) :=
  (h.hasStieltjesIntegral.map hB).stieltjesIntegrable

theorem stieltjesIntegral_map (hB : ∀ e y, Ψ (B e y) = B' (φ e) (ψ y))
    (h : StieltjesIntegrable a b B f g) :
    ∫⟨B'⟩ x in a..b, φ (f x) ∂(fun x ↦ ψ (g x)) =
      Ψ (∫⟨B⟩ x in a..b, f x ∂g) :=
  (h.hasStieltjesIntegral.map hB).stieltjesIntegral_eq

end Naturality

section Subinterval

/-! ### Integrability on subintervals -/

variable [CompleteSpace G] {f : ℝ → E} {g : ℝ → F} {a b c d : ℝ} {B : E →L[ℝ] F →L[ℝ] G}

private theorem StieltjesIntegrable'.to_subinterval
    (hab : a < b) (hcd : c < d) (hac : a ≤ c) (hdb : d ≤ b) (h : StieltjesIntegrable' a b B f g) :
    StieltjesIntegrable' c d B f g := by
  simp only [stieltjesIntegrable'_iff_integrable, Fin.isValue] at h ⊢
  exact Integrable.to_subbox h (by simp [hab, hcd, hac, hdb])

/-- If `f` is Stieltjes-integrable from `a` to `b` (with `a < b`) against `g`, then
it is also Stieltjes-integrable on any sub-interval of `(a, b]`. -/
theorem StieltjesIntegrable.to_subinterval (hab : a < b) (hc : c ∈ Set.Icc a b)
    (hd : d ∈ Set.Icc a b) (h : StieltjesIntegrable a b B f g) :
    StieltjesIntegrable c d B f g := by
  simp only [Set.mem_Icc] at hc hd
  simp only [of_lt, hab] at h
  rcases lt_trichotomy c d with hcd | rfl | hcd
  · simp only [hcd, of_lt]
    exact StieltjesIntegrable'.to_subinterval hab hcd hc.1 hd.2 h
  · simp
  symm
  simp only [hcd, of_lt]
  exact StieltjesIntegrable'.to_subinterval hab hcd hd.1 hc.2 h

end Subinterval

section Split
/-! ## Splitting over adjacent intervals -/

variable {f : ℝ → E} {g : ℝ → F} {L L' L'' : G} {a b c : ℝ}
  {B : E →L[ℝ] F →L[ℝ] G} [CompleteSpace G]

private theorem HasStieltjesIntegral'.add_adjacent (hab : a < b) (hbc : b < c)
    (h : StieltjesIntegrable' a c B f g)
    (h₁ : HasStieltjesIntegral' a b B f g L)
    (h₂ : HasStieltjesIntegral' b c B f g L') :
    HasStieltjesIntegral' a c B f g (L + L') := by
  simp only [HasStieltjesIntegral', StieltjesIntegrable'] at h h₁ h₂ ⊢
  have hac : a < c := hab.trans hbc
  have hb_mem : b ∈ Set.Ioo ((Ioc a c).lower 0) ((Ioc a c).upper 0) := by simp [hac, hab, hbc]
  refine HasIntegral.split 0 b ?_ ?_ h h₁ h₂
  · rw [Box.splitLower_def hb_mem, WithBot.coe_eq_coe]
    ext; simp [hac, hab]
  · rw [Box.splitUpper_def hb_mem, WithBot.coe_eq_coe]
    ext; simp [hac, hbc]

private theorem HasStieltjesIntegral.add_adjacent_prelim (hab : a < b) (hbc : b < c)
    (h₁ : HasStieltjesIntegral a b B f g L)
    (h₂ : HasStieltjesIntegral b c B f g L')
    (h₃ : HasStieltjesIntegral a c B f g L'') :
    L'' = L + L' := by
  apply unique h₃
  simp only [hab, of_lt, hbc, hab.trans hbc] at h₁ h₂ h₃ ⊢
  exact HasStieltjesIntegral'.add_adjacent hab hbc ⟨L'', h₃⟩ h₁ h₂

/-- If `f` is Stieltjes-integrable from `a` to `c`, has Stieltjes integral `L` from `a` to `b`
and `L'` from `b` to `c` then `f` has Stieltjes integral `L + L'` from `a` to `c`.  No ordering
is assumed in `a`, `b`, `c` in the final statement of the theorem.

TODO: reduce the amount of case splitting in the proof. -/
theorem HasStieltjesIntegral.add_adjacent
    (h : StieltjesIntegrable a c B f g)
    (h₁ : HasStieltjesIntegral a b B f g L)
    (h₂ : HasStieltjesIntegral b c B f g L') :
    HasStieltjesIntegral a c B f g (L + L') := by
  have h₃ := h.hasStieltjesIntegral
  by_cases! hab : a = b
  · simp_all
  by_cases! hbc : b = c
  · simp_all
  by_cases! hac : a = c
  · simp_all; simp [h₁.unique h₂.symm]
  have h₁' := h₁.symm
  have h₂' := h₂.symm
  have h₃' := h₃.symm
  convert h₃
  rcases lt_or_gt_of_ne hab with hab | hba <;>
  rcases lt_or_gt_of_ne hbc with hbc | hcb <;>
  rcases lt_or_gt_of_ne hac with hac | hca <;>
  try order
  · simp_all [add_adjacent_prelim hab hbc h₁ h₂ h₃]
  · have := add_adjacent_prelim hac hcb h₃ h₂' h₁
    grind
  · have := add_adjacent_prelim hca hab h₃' h₁ h₂'
    grind
  · have := add_adjacent_prelim hba hac h₁' h₃ h₂
    grind
  · have := add_adjacent_prelim hbc hca h₂ h₃' h₁'
    grind
  · have := add_adjacent_prelim hcb hba h₂' h₁' h₃'
    grind

theorem stieltjesIntegral.add_adjacent (h : StieltjesIntegrable a c B f g)
    (h₁ : StieltjesIntegrable a b B f g) (h₂ : StieltjesIntegrable b c B f g) :
    ∫⟨B⟩ x in a..c, f x ∂g = ∫⟨B⟩ x in a..b, f x ∂g + ∫⟨B⟩ x in b..c, f x ∂g :=
  (HasStieltjesIntegral.add_adjacent h h₁.hasStieltjesIntegral
    h₂.hasStieltjesIntegral).stieltjesIntegral_eq

end Split

section Change

/-! ## Change of variables -/

variable {φ : ℝ → ℝ} {f : ℝ → E} {g : ℝ → F} {L : G} {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G}

lemma Ioc.le_Ioc_iff {a b c d : ℝ} (hab : a < b) (hcd : c < d) :
  Ioc c d ≤ Ioc a b ↔ a ≤ c ∧ d ≤ b := by
  simp [Box.le_iff_bounds, Pi.le_def, hab, hcd]

lemma Box.le_Ioc_iff {a b : ℝ} (hab : a < b) (J : Box (Fin 1)) :
  J ≤ Ioc a b ↔ a ≤ J.lower 0 ∧ J.upper 0 ≤ b := by
  nth_rw 1 [J.eq_Ioc]
  exact Ioc.le_Ioc_iff hab (J.lower_lt_upper 0)

lemma Box.mem_of_le {a b : ℝ} (hab : a < b) {J : Box (Fin 1)} (hJ : J ≤ Ioc a b) :
  J.lower 0 ∈ Set.Icc a b ∧ J.upper 0 ∈ Set.Icc a b := by
  rw [le_Ioc_iff hab] at hJ
  have := J.lower_lt_upper 0
  grind

lemma Box.disjoint_iff {J J' : Box (Fin 1)} :
  Disjoint J.toSet J'.toSet ↔ J.upper 0 ≤ J'.lower 0 ∨ J'.upper 0 ≤ J.lower 0 := by
  have := J.lower_lt_upper 0
  have := J'.lower_lt_upper 0
  rw [← not_iff_not]
  simp only [Set.not_disjoint_iff_nonempty_inter, Fin.isValue, not_or, not_le]
  refine ⟨ fun h ↦ ?_, fun h ↦ ?_ ⟩
  · obtain ⟨ x, hx ⟩ := h
    simp [Box.mem_def] at hx
    grind
  use min J.upper J'.upper
  simp [Box.mem_def, h]

/-- Move to Mathlib.Topology.Order.IntermediateValue -/
theorem _root_.Set.BijOn.of_strictMonoOn_continuousOn {α : Type*} [TopologicalSpace α]
    [ConditionallyCompleteLinearOrder α] [OrderTopology α] [DenselyOrdered α] {δ : Type u_1}
    [LinearOrder δ] [TopologicalSpace δ] [OrderClosedTopology δ] {f : α → δ} {a b : α}
    (hab : a ≤ b) (hf : ContinuousOn f (Set.Icc a b)) (hf_mono : StrictMonoOn f (Set.Icc a b)) :
    Set.BijOn f (Set.Icc a b) (Set.Icc (f a) (f b)) :=
  Set.BijOn.mk hf_mono.monotoneOn.mapsTo_Icc hf_mono.injOn
  (hf.surjOn_Icc (Set.left_mem_Icc.mpr hab) (Set.right_mem_Icc.mpr hab))

/-- The Riemann-Stieltjes integral is unchanged after composing with a strictly monotone
continuous function.

TODO: establish a similar theorem for strictly antitone continuous functions. One may wish
to golf this proof first. -/
theorem HasStieltjesIntegral.of_comp_strictMono_continuous (hab : a < b)
  (hmono : StrictMonoOn φ (Set.Icc a b))
  (hcont : ContinuousOn φ (Set.Icc a b))
  (h : HasStieltjesIntegral (φ a) (φ b) B f g L) :
  HasStieltjesIntegral a b B (f ∘ φ) (g ∘ φ) L := by
  have ha_mem : a ∈ Set.Icc a b := by simp [hab.le]
  have hb_mem : b ∈ Set.Icc a b := by simp [hab.le]
  have hsurj := hcont.surjOn_Icc ha_mem hb_mem
  have hφab : φ a < φ b := hmono ha_mem hb_mem hab
  have hmono' := hmono.monotoneOn
  have hinv := (Set.BijOn.of_strictMonoOn_continuousOn hab.le hcont hmono).invOn_invFunOn
  set ψ := Function.invFunOn φ (Set.Icc a b)
  simp only [hφab, hasStieltjesIntegral_iff_lim_sum, gt_iff_lt, Prepartition.mesh_size_le_iff,
    Prepartition.mem_boxes, TaggedPrepartition.mem_toPrepartition, tsub_le_iff_right,
    Fin.forall_fin_one, Fin.isValue, map_sub, hab, Function.comp_apply] at h ⊢
  peel h with ε hε h
  obtain ⟨ δ', hδ', h ⟩ := h
  obtain ⟨ δ, hδ, hδf ⟩ :=  Metric.uniformContinuousOn_iff.mp
    (isCompact_Icc.uniformContinuousOn_of_continuous hcont) δ' hδ'
  refine ⟨ NNReal.mk (δ/2) (by linarith), (show 0 < δ/2 by positivity),
    fun π hhen hpart hmesh ↦ ?_ ⟩
  have h1 {J : Box (Fin 1)} (hJ : J ∈ π) := J.mem_of_le hab (π.le_of_mem' _ hJ)
  have h2 {J : Box (Fin 1)} (hJ : J ∈ π) : φ (J.lower 0) < φ (J.upper 0) :=
    hmono (h1 hJ).1 (h1 hJ).2 (J.lower_lt_upper 0)
  classical
  let π' : TaggedPrepartition (Ioc (φ a) (φ b)) := {
    boxes := π.boxes.image (Ioc.comp φ)
    le_of_mem' J' hJ' := by
      simp only [Finset.mem_image, Prepartition.mem_boxes,
        TaggedPrepartition.mem_toPrepartition] at hJ'
      obtain ⟨ J, hJπ, rfl ⟩ := hJ'
      rw [J.eq_Ioc]
      simp only [Fin.isValue, Box.lower_lt_upper, Ioc.comp_apply, Ioc.le_Ioc_iff hφab (h2 hJπ)]
      and_intros <;> apply hmono' <;> grind
    pairwiseDisjoint I' hI' J' hJ' hdisj := by
      simp only [Finset.coe_image, Set.mem_image, SetLike.mem_coe, Prepartition.mem_boxes,
        TaggedPrepartition.mem_toPrepartition, Function.onFun] at hI' hJ' ⊢
      obtain ⟨ I, hIπ, rfl ⟩ := hI'
      obtain ⟨ J, hJπ, rfl ⟩ := hJ'
      have h : I ≠ J := by grind
      replace h := π.pairwiseDisjoint hIπ hJπ h
      simp only [Function.onFun, Box.disjoint_iff, Fin.isValue, Ioc.comp, h2 hIπ, Ioc.upper, h2 hJπ,
        Ioc.lower] at h ⊢
      apply Or.imp _ _ h <;> apply hmono' <;> grind
    tag J := fun _ ↦ φ (π.tag ((Ioc.comp ψ) J) 0)
    tag_mem_Icc J := by
      have := π.tag_mem_Icc ((Ioc.comp ψ) J)
      simp only [Box.Icc_def, Set.mem_Icc, Pi.le_def, hab, Ioc.lower, Fin.forall_fin_one,
        Fin.isValue, Ioc.upper, hφab, forall_const] at this ⊢
      refine ⟨ hmono' ha_mem (by simp [this]) this.1, hmono' (by simp [this]) hb_mem this.2 ⟩
  }
  have hhen' : π'.IsHenstock := by
    intro J' hJ'
    simp only [Fin.isValue, TaggedPrepartition.mem_mk, Prepartition.mem_mk, Finset.mem_image,
      Prepartition.mem_boxes, TaggedPrepartition.mem_toPrepartition, Box.Icc_def, Set.mem_Icc,
      Pi.le_def, Fin.forall_fin_one, π'] at hJ' ⊢
    obtain ⟨ J, hJπ, rfl ⟩ := hJ'
    specialize h1 hJπ
    simp only [Ioc.comp, Fin.isValue, h2 hJπ, Ioc.lower, hinv.1 h1.1, Ioc.upper, hinv.1 h1.2,
      ← Box.eq_Ioc]
    have h3 := π.tag_mem_Icc J
    have h4 := hhen J hJπ
    simp only [Box.Icc_def, Set.mem_Icc, Pi.le_def, hab, Ioc.lower, Fin.forall_fin_one, Fin.isValue,
      Ioc.upper] at h3 h4
    exact ⟨ hmono' h1.1 (by simp [h3]) h4.1, hmono' (by simp [h3]) h1.2 h4.2 ⟩
  have hpart' : π'.IsPartition := by
    intro x' hx'
    simp only [Box.mem_def, hφab, Ioc.lower, Ioc.upper, Set.mem_Ioc, Fin.forall_fin_one,
      Fin.isValue, TaggedPrepartition.mem_toPrepartition] at hx' ⊢
    have := hsurj (show x' 0 ∈ Set.Icc (φ a) (φ b) by grind)
    simp only [Fin.isValue, Set.mem_image, Set.mem_Icc] at this
    obtain ⟨ x, hx, hxx' ⟩ := this
    simp only [Fin.isValue, ← hxx', TaggedPrepartition.mem_mk, Prepartition.mem_mk,
      Finset.mem_image, Prepartition.mem_boxes, TaggedPrepartition.mem_toPrepartition,
      exists_exists_and_eq_and, π'] at hx' ⊢
    have : a < x := by grind
    obtain ⟨ J, hJπ, hxJ ⟩ := hpart (fun _ ↦ x) (by simp [mem_Ioc, hab, this, hx])
    use J, hJπ
    simp only [Box.mem_def, Set.mem_Ioc, Fin.forall_fin_one, Fin.isValue, Ioc.comp, h2 hJπ,
      Ioc.lower, Ioc.upper] at hxJ ⊢
    specialize h1 hJπ
    exact ⟨ hmono h1.1 (by simp [hx]) hxJ.1, hmono' (by simp [hx]) h1.2 hxJ.2 ⟩
  have hmesh' : ∀ J' ∈ π', J'.upper 0 ≤ δ' + J'.lower 0 := by
    intro J' hJ'
    simp only [Fin.isValue, TaggedPrepartition.mem_mk, Prepartition.mem_mk, Finset.mem_image,
      Prepartition.mem_boxes, TaggedPrepartition.mem_toPrepartition, π'] at hJ'
    obtain ⟨ J, hJπ, rfl ⟩ := hJ'
    specialize h1 hJπ
    specialize h2 hJπ
    have := J.lower_lt_upper 0
    simp only [Ioc.comp, Fin.isValue, h2, Ioc.upper, Ioc.lower]
    suffices dist (φ (J.lower 0)) (φ (J.upper 0)) < δ' by
      simp [Real.dist_eq] at this
      grind
    apply hδf _ h1.1 _ h1.2
    specialize hmesh J hJπ
    simp [Real.dist_eq] at hmesh ⊢
    grind
  convert h π' hhen' hpart' hmesh' using 2
  have : ∀ J ∈ π, J = Ioc.comp ψ (Ioc.comp φ J) := by
    intro J hJ
    simp [Ioc.comp, h2 hJ, hinv.1 (h1 hJ).1, hinv.1 (h1 hJ).2, ← J.eq_Ioc]
  symm
  convert Finset.sum_image (g := Ioc.comp φ) ?_ with J hJ
    <;> try first | simp [← this J hJ] | simp [Ioc.comp, h2 hJ]
  intro I hI J hJ hIJ
  apply_fun Ioc.comp ψ at hIJ
  rwa [← this I hI, ← this J hJ] at hIJ

theorem StieltjesIntegrable.of_comp_strictMono_continuous (hab : a < b)
    (hmono : StrictMonoOn φ (Set.Icc a b))
    (hcont : ContinuousOn φ (Set.Icc a b))
    (h : StieltjesIntegrable (φ a) (φ b) B f g) :
    StieltjesIntegrable a b B (f ∘ φ) (g ∘ φ) :=
  (h.hasStieltjesIntegral.of_comp_strictMono_continuous hab hmono hcont).stieltjesIntegrable

theorem stieltjesIntegral_of_comp_strictMono_continuous (hab : a < b)
    (hmono : StrictMonoOn φ (Set.Icc a b))
    (hcont : ContinuousOn φ (Set.Icc a b))
    (h : StieltjesIntegrable (φ a) (φ b) B f g) :
    ∫⟨B⟩ x in a..b, f (φ x) ∂(fun x ↦ g (φ x)) = ∫⟨B⟩ x in φ a..φ b, f x ∂g := by
  rw [← (h.hasStieltjesIntegral.of_comp_strictMono_continuous hab hmono hcont).stieltjesIntegral_eq]
  congr

end Change

/-! ## Main theorems -/

/-- For any valid box partition of (a, b], the sum of the norm of the
differential `ofDiff g` is bounded by the total variation of g on the interval. -/
private lemma sum_norm_ofDiff_le_norm_mul_eVariationOn {a b : ℝ} (g : ℝ → F)
    (hg : BoundedVariationOn g (Set.Icc a b))
    (π : Prepartition (Ioc a b)) :
    ∑ J ∈ π.boxes, ‖(BoxAdditiveMap.ofDiff (fun x ↦ B.flip (g x))) J‖ ≤
      ‖B‖ * (eVariationOn g (Set.Icc a b)).toReal := by

  -- Step 1: Bound each local subbox evaluation by the operator norm of B.flip
  have h_term : ∀ J ∈ π.boxes, ‖(BoxAdditiveMap.ofDiff (fun x ↦ B.flip (g x))) J‖ ≤
      ‖B‖ * ‖g (J.upper 0) - g (J.lower 0)‖ := by
    intro J hJ
    change ‖B.flip (g (J.upper 0)) - B.flip (g (J.lower 0))‖ ≤ _
    rw [← map_sub, ← opNorm_flip B]
    exact (B.flip).le_opNorm (g (J.upper 0) - g (J.lower 0))

  -- Step 2: Apply bound term-wise to sum and cancel operator norm
  refine (Finset.sum_le_sum h_term).trans ?_
  rw [← Finset.mul_sum]
  gcongr

  -- Step 3: Upgrade to ENNReal and convert vector norms cleanly to `edist`
  have h_sum_eq : ∑ J ∈ π.boxes, ‖g (J.upper 0) - g (J.lower 0)‖ =
      (ENNReal.ofReal (∑ J ∈ π.boxes, ‖g (J.upper 0) - g (J.lower 0)‖)).toReal :=
    (ENNReal.toReal_ofReal (Finset.sum_nonneg fun _ _ ↦ norm_nonneg _)).symm
  rw [h_sum_eq]
  refine ENNReal.toReal_mono (by exact hg) ?_
  rw [ENNReal.ofReal_sum_of_nonneg (fun _ _ ↦ norm_nonneg _)]
  simp_rw [← dist_eq_norm, ← edist_dist]

  sorry


/-- Continuous integrand and a
bounded-variation integrator give an integrable Riemann-Stieltjes box integrand. -/
private lemma integrable_of_continuousOn_of_boundedVariationOn [CompleteSpace G]
   {a b : ℝ} {f : ℝ → E} {g : ℝ → F} (hab : a < b) (l : IntegrationParams)
    (hf : ContinuousOn f (Set.Icc a b)) (hg : BoundedVariationOn g (Set.Icc a b)) :
    Integrable (Ioc a b) l
      (fun x ↦ f (x 0)) (BoxAdditiveMap.ofDiff (fun x ↦ B.flip (g x))) := by
  let f' := fun x : Fin 1 → ℝ ↦ f (x 0)
  refine integrable_iff_cauchy_basis.2 fun ε hε ↦ ?_
  let V : ℝ := (eVariationOn g (Set.Icc a b)).toReal
  rcases exists_pos_mul_lt hε (‖B‖ * V) with ⟨η, hη, hηC⟩
  obtain ⟨δ, hδ, hδf⟩ :=
    Metric.uniformContinuousOn_iff.mp (isCompact_Icc.uniformContinuousOn_of_continuous hf) η hη
  let ρ : ℝ := δ / 4
  let r : NNReal → (Fin 1 → ℝ) → Set.Ioi (0 : ℝ) := fun _ _ ↦ ⟨ρ, by grind⟩
  refine ⟨r, fun _ _ _ ↦ by rfl, fun c₁ c₂ π₁ π₂ hπ₁ hpart₁ hπ₂ hpart₂ ↦ ?_⟩
  let vol := BoxAdditiveMap.ofDiff (fun x ↦ B.flip (g x))
  let π := π₁.toPrepartition ⊓ π₂.toPrepartition
  let τ₁ := π₁.infPrepartition π₂.toPrepartition
  let τ₂ := π₂.infPrepartition π₁.toPrepartition
  have hsub₁ : τ₁.IsSubordinate (r c₁) := hπ₁.isSubordinate.infPrepartition _
  have hsub₂ : τ₂.IsSubordinate (r c₂) := hπ₂.isSubordinate.infPrepartition _
  have hdiff : integralSum f' vol π₁ - integralSum f' vol π₂ =
      ∑ J ∈ π.boxes, (vol J (f (τ₁.tag J 0)) - vol J (f (τ₂.tag J 0))) := by
    simpa [vol, π, τ₁, τ₂] using integralSum_sub_partitions f' vol hpart₁ hpart₂
  have hterm : ∀ J ∈ π.boxes, ‖vol J (f (τ₁.tag J 0)) - vol J (f (τ₂.tag J 0))‖ ≤ ‖vol J‖ * η := by
    intro J hJ
    have hJτ₁ : J ∈ τ₁ := by change J ∈ τ₁.toPrepartition; simpa [π, τ₁] using hJ
    have hJτ₂ : J ∈ τ₂ := TaggedPrepartition.mem_infPrepartition_comm.mp hJτ₁
    have := τ₁.tag_mem_Icc J
    have := τ₂.tag_mem_Icc J
    have hτ₁_upper : dist (τ₁.tag J) J.upper ≤ ρ := by
      simpa [Metric.mem_closedBall, r, ρ, dist_comm] using hsub₁ J hJτ₁ J.upper_mem_Icc
    have hτ₂_upper : dist J.upper (τ₂.tag J) ≤ ρ := by
      simpa [Metric.mem_closedBall, r, ρ] using hsub₂ J hJτ₂ J.upper_mem_Icc
    grw [← map_sub, (vol J).le_opNorm, ← dist_eq_norm]
    gcongr
    apply le_of_lt (hδf _ (by simp_all) _ (by simp_all) _)
    grw [dist_le_pi_dist, dist_triangle _ J.upper _]
    unfold ρ at *; linarith
  calc
    dist (integralSum f' vol π₁) (integralSum f' vol π₂)
      = ‖∑ J ∈ π.boxes, (vol J (f (τ₁.tag J 0)) - vol J (f (τ₂.tag J 0)))‖ := by
      simp only [dist_eq_norm, hdiff]
    _ ≤ (‖B‖ * V) * η := by
      grw [norm_sum_le, Finset.sum_le_sum hterm, ← Finset.sum_mul]
      gcongr
      exact sum_norm_ofDiff_le_norm_mul_eVariationOn B g hg π
    _ ≤ ε := by grind

/-- Theorem A.1 of Montgomery-Vaughan: a continuous integrand and a bounded-variation integrator
have a Riemann-Stieltjes integral. -/
theorem exists_of_continuousOn_of_boundedVariationOn [CompleteSpace G] {a b : ℝ}
    (f : ℝ → E) (g : ℝ → F) (hab : a < b)
    (hf : ContinuousOn f (Set.Icc a b)) (hg : BoundedVariationOn g (Set.Icc a b)) :
    StieltjesIntegrable a b B f g := by
  obtain ⟨L, hL⟩ := integrable_of_continuousOn_of_boundedVariationOn B
    hab IntegrationParams.Riemann hf hg
  use L
  simp [HasStieltjesIntegral, HasStieltjesIntegral', hab.ne, hab, hL]

/-- Theorem A.2 of Montgomery Vaughan: if ∫ₐᵇ f dg exists, then ∫ₐᵇ g df exists and
∫ₐᵇ g df = g(b) * f(b) - g(a) * f(a) - ∫ₐᵇ f dg. -/
theorem HasStieltjesIntegral.by_parts {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G}
    {f : ℝ → E} {g : ℝ → F} {L : G} (hL : HasStieltjesIntegral a b B f g L) :
    HasStieltjesIntegral a b B.flip g f (B (f b) (g b) - B (f a) (g a) - L) := by sorry

theorem StieltjesIntegrable.by_parts {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G} {f : ℝ → E} {g : ℝ → F}
    (h : StieltjesIntegrable a b B f g) :
    StieltjesIntegrable a b B.flip g f := by
  exact ⟨_, h.hasStieltjesIntegral.by_parts⟩

theorem stieltjesIntegral.by_parts {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G} {f : ℝ → E} {g : ℝ → F}
    (h : StieltjesIntegrable a b B f g) :
    ∫⟨B.flip⟩ x in a..b, g x ∂f = B (f b) (g b) - B (f a) (g a) - ∫⟨B⟩ x in a..b, f x ∂g := by
  rw [h.hasStieltjesIntegral.by_parts.stieltjesIntegral_eq,
    h.hasStieltjesIntegral.stieltjesIntegral_eq]

theorem HasStieltjesIntegral.of_const {a b : ℝ} (c : E) (g : ℝ → F) :
    HasStieltjesIntegral a b B (fun _ ↦ c) g (B c (g b) - B c (g a)) := by
  convert by_parts (B := B.flip) (f := g) (g := fun _ ↦ c) (L := 0) (by simp [const_right]) using 1
  simp [flip_apply]

theorem StieltjesIntegrable.of_const (c : E) (g : ℝ → F) :
    StieltjesIntegrable a b B (fun _ ↦ c) g :=
  (HasStieltjesIntegral.of_const B c g).stieltjesIntegrable

@[simp]
theorem stieltjesIntegral.of_const (c : E) (g : ℝ → F) :
    ∫⟨B⟩ _ in a..b, c ∂g = B c (g b) - B c (g a) :=
  (HasStieltjesIntegral.of_const B c g).stieltjesIntegral_eq


/-- Lemma Subset given an interval [a,b], if c,d ∈ [a,b], then |c - d| < b -a
-/
lemma subset_smaller_distance {a b m n : ℝ} (hm : m ∈ Set.Icc a b)
  (hn : n ∈ Set.Icc a b) : |m - n| ≤ b - a := by
  grind

lemma MVT_with_error' [CompleteSpace F] {g : ℝ → F} {a b ε : ℝ}
  (hab : a < b) (hg : ContDiffOn ℝ 1 g (Set.Icc a b)) (hε : 0 < ε)
  : ∃ δ > 0, ∀ a' ∈ Set.Icc a b, ∀ b' ∈ Set.Icc a b,
  |b' - a'| < δ → ∀ c ∈ Set.uIcc a' b', dist (g b' -g a')
    ((b' - a') • (derivWithin g (Set.Icc a b)) c) ≤ ε * |b' - a'| := by
  set g' := derivWithin g (Set.Icc a b)
  have hderiv_ucont :=
    isCompact_Icc.uniformContinuousOn_of_continuous
      (ContDiffOn.continuousOn_derivWithin hg (uniqueDiffOn_Icc hab) le_rfl)
  obtain ⟨δ, hδ_pos, hδ_prop⟩ := Metric.uniformContinuousOn_iff.mp hderiv_ucont ε (by positivity)
  refine ⟨δ, hδ_pos, fun a' ha' b' hb' h_b'_sub_a'_lt_δ c hc => ?_⟩
  by_cases! ha'b' : a' = b'
  · simp [ha'b']
  have hIcc_subset : Set.uIcc a' b' ⊆ Set.Icc a b := by intro; simp [Set.mem_uIcc]; grind
  have h_ftc := calc
     g b' - g a' = ∫ x in a'..b', g' c + (g' x - g' c) := by
      rw [← intervalIntegral.integral_derivWithin_uIcc_of_contDiffOn_uIcc (hg.mono hIcc_subset)]
      apply intervalIntegral.integral_congr
      intro x hx
      simp only [add_sub_cancel]
      exact derivWithin_subset hIcc_subset (uniqueDiffOn_Icc (by grind) x hx)
        (hg.differentiableOn one_ne_zero x (hIcc_subset hx))
     _ = (∫ x in a'..b', g' c) + (∫ x in a'..b', (g' x - g' c)) := by
      rw [intervalIntegral.integral_add intervalIntegrable_const]
      exact ((hderiv_ucont.mono hIcc_subset).continuousOn.intervalIntegrable).sub
        intervalIntegrable_const
  simp only [h_ftc, intervalIntegral.integral_const, dist_self_add_left, ge_iff_le]
  apply intervalIntegral.norm_integral_le_of_norm_le_const
  intro x hx
  rw [←dist_eq_norm]
  apply (hδ_prop _ (hIcc_subset ⟨hx.1.le, hx.2⟩) _ (hIcc_subset hc) _).le
  exact lt_of_le_of_lt (subset_smaller_distance ⟨hx.1.le, hx.2⟩ hc) (by grind)

/-- Lemma MVT version using a bilinear form, this theorem is used in the proof of Theorem A3 (b)
Since the MVT is false in general (for higher dimensions), we prove a version where it is true up
to some error term.

For g : ℝ → F and f : ℝ → E, and B a bounded blinear from from E × F → G where E, F, and G are
normed. Then if g is C^1[a,b], and f is bounded on [a,b], then for any ε > 0, there is a δ > 0 such
that for all a',b' with a ≤ a' < b' ≤ b, we have for all c ∈ [a',b'] that
‖B(f(c),g(b') - g(a'))‖ ≤ ‖B(f(c),g'(c))‖ (b' - a') + ε (b' - a')
We remark that the theorem is most powerful when we take a' = a and b' = b. Since this is used to
say that if the mesh is fine enough (of size < δ), then we have this MVT with small error.

Remark: In the use of MV theorem A3, they assume that f is Riemann integrable on [a,b], and use the
fact that this will imply that f is bounded. However, for the MVT statement, we need only that f is
bounded. Furthermore, there is no statement in Mathlib that states that Riemann integrable functions
are bounded.
-/
lemma MVT_with_bilinear_form_and_error [CompleteSpace F] {f : ℝ → E} {g : ℝ → F} {a b ε : ℝ}
  (B : E →L[ℝ] F →L[ℝ] G) (hab : a < b) (hg : ContDiffOn ℝ 1 g (Set.Icc a b)) (hε : 0 < ε)
  (f_bounded : ∃ M > 0, ∀ x ∈ Set.Icc a b, ‖f x‖ < M) : ∃ δ > 0, ∀ a' ≥ a, ∀ b' ≤ b,
  a' < b' → b' - a' < δ → ∀ c ∈ Set.Icc a' b', ‖B (f c) (g b' -g a')‖
    ≤ ‖B (f c) (derivWithin g (Set.Icc a b) c)‖ * (b' - a') + ε * (b' - a') := by
  by_cases! hB : B = 0
  · use 1; simp only [gt_iff_lt, zero_lt_one, ge_iff_le, Set.mem_Icc, hB, zero_apply, norm_zero,
    zero_mul, zero_add, and_imp, true_and]; intros; positivity
  obtain ⟨M, hM_pos, hM_bound⟩ := f_bounded
  have hB_norm_pos : 0 < ‖B‖ := norm_pos_iff.mpr hB
  obtain ⟨ δ, hδ_pos, hδ_prop⟩ := MVT_with_error' hab hg (show 0 < ε / (‖B‖ * M) by positivity)
  use δ, hδ_pos
  intros a' ha' b' hb' h_a'_lt_b' h_b'_sub_a'_lt_δ c hc
  specialize hδ_prop a' (by grind) b' (by grind) (by grind) c
    (by simpa [Set.uIcc_of_lt h_a'_lt_b'] using hc)
  rw [dist_eq_norm] at hδ_prop
  have : |b'-a'| = b' - a' := abs_of_pos (by positivity)
  calc
    _ = ‖B (f c) ((b' - a') • derivWithin g (Set.Icc a b) c)
      + B (f c) (g b' - g a' - (b' - a') • derivWithin g (Set.Icc a b) c)‖ := by
      simp only [map_sub, map_smul, add_sub_cancel]
    _ ≤ ‖B (f c) ((b' - a') • derivWithin g (Set.Icc a b) c)‖
      + ‖B (f c) (g b' - g a' - (b' - a') • derivWithin g (Set.Icc a b) c)‖ := by
       apply norm_add_le
    _ ≤ _ := by
      simp only [map_smul, norm_smul, Real.norm_eq_abs, this, mul_comm,
        add_le_add_iff_left]
      grw [B.le_opNorm₂ (f c) _, hδ_prop, hM_bound _ (by grind), this]
      field_simp
      order

/-- Lemma for a vector valued MVT with error since MVT is false for a general
funcion in higher dimensions, but is true up to some error for higher dimensions.
This lemma is used in the proof of Theorem A3 (a). We prove it by specializing the
bilinear form version of the statement. However, we must break into cases on whether
or not F is the trivial space.

For g C^1[a,b] and ε > 0, there is a δ > 0 such that for all a ≤ a' < b' ≤ b with
b' - a' < δ, we have that for all c ∈ [a',b'] that
‖g(b')-g(a')‖ ≤ ‖g'(c)‖ * (b' - a') + ε * (b' - a')
-/
lemma MVT_with_error [CompleteSpace F] {g : ℝ → F} {ε : ℝ} (hab : a < b)
    (hg : ContDiffOn ℝ 1 g (Set.Icc a b)) (hε : 0 < ε)
    : ∃ δ > 0, ∀ a' ≥ a, ∀ b' ≤ b, a' < b' → b' - a' < δ → ∀ c ∈ Set.Icc a' b',
    ‖g b' - g a'‖ ≤ ‖derivWithin g (Set.Icc a b) c‖ * (b' - a') + ε * (b' - a') := by
  have f_bounded : ∃ M > 0, ∀ x ∈ Set.Icc a b, ‖(fun _ => (1 : ℝ)) x‖ < M :=
    ⟨ 2, by linarith, by intros; simp ⟩
  obtain ⟨δ, hδ_pos, hδ⟩ := MVT_with_bilinear_form_and_error (lsmul ℝ ℝ) hab hg hε f_bounded
  refine ⟨ δ, hδ_pos, fun a' ha' b' hb' hab' hdist c hc ↦ ?_ ⟩
  simpa using hδ a' ha' b' hb' hab' hdist c hc



/-- Theorem A.3 (a).  If g′ is continuous on [a, b], then
Varₐᵇ g = ∫ₐᵇ ‖g′(x)‖ dx.
-/
theorem variation_of_derivative {a b : ℝ} {g : ℝ → F} (hab : a < b)
    (hg : ContDiffOn ℝ 1 g (Set.Icc a b)) :
    (eVariationOn g (Set.Icc a b)).toReal = ∫ x in a..b, ‖deriv g x‖ := by sorry

/-- Theorem A.3 (b).  If g′ is continuous on [a, b] and if in addition f is
Riemann integrable, then ∫ₐᵇ f(x) dg(x) = ∫ₐᵇ f(x) g′(x) dx. -/
theorem integral_of_derivative {a b : ℝ} {f : ℝ → E} {g : ℝ → F} (hab : a < b)
    (hg : ContDiffOn ℝ 1 g (Set.Icc a b))
    (hf : RiemannIntegrable a b f) :
    HasStieltjesIntegral a b B f g (∫ x in a..b, B (f x) (deriv g x)) := by sorry

/-- Theorem A.4. Suppose that g has bounded variation, and put g∗(x) = Varₐˣ g. Then
‖∫ₐᵇ f(x) dg(x)‖ ≤ ∫ₐᵇ ‖f(x)‖ dg∗(x),
provided that both integrals exist. -/
theorem integral_le_integral_of_variation {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G}
    {f : ℝ → E} {g : ℝ → F} {L : G} {L' : ℝ}
    (hab : a < b) (hg : BoundedVariationOn g (Set.Icc a b))
    (hfg : HasStieltjesIntegral a b B f g L)
    (hfabs_gstar : HasStieltjesIntegral a b (mul ℝ ℝ) (fun x ↦ ‖f x‖)
      (fun x ↦ (eVariationOn g (Set.Icc a x)).toReal) L') :
    ‖L‖ ≤ ‖B‖ * L' := by sorry

/-! ### Connection to standard integrals -/

/-- Function-level form of Theorem A.3(b) (`integral_of_derivative`): when `g` is `C¹` on
`[a, b]` and `f` is Riemann integrable, the Stieltjes integral of `f` against `g` equals the
Riemann integral of `B (f x) (g' x)`. -/
theorem stieltjesIntegral_eq_intervalIntegral_of_contDiffOn' {f : ℝ → E} {g : ℝ → F} {a b : ℝ}
    (hab : a < b) (hg : ContDiffOn ℝ 1 g (Set.Icc a b)) (hf : RiemannIntegrable a b f) :
    ∫⟨B⟩ x in a..b, f x ∂g = ∫ x in a..b, B (f x) (deriv g x) :=
  (integral_of_derivative B hab hg hf).stieltjesIntegral_eq

theorem stieltjesIntegral_eq_intervalIntegral_of_contDiffOn {f : ℝ → E} {g : ℝ → F} {a b : ℝ}
    (hg : ContDiffOn ℝ 1 g (Set.Icc (min a b) (max a b)))
    (hf : RiemannIntegrable (min a b) (max a b) f) :
    ∫⟨B⟩ x in a..b, f x ∂g = ∫ x in a..b, B (f x) (deriv g x) := by
  rcases lt_trichotomy a b with hab | rfl | hba
  · simp only [le_of_lt hab, inf_of_le_left, sup_of_le_right] at hg hf
    exact stieltjesIntegral_eq_intervalIntegral_of_contDiffOn' B hab hg hf
  · simp
  simp only [le_of_lt hba, inf_of_le_right, sup_of_le_left] at hg hf
  rw [stieltjesIntegral.integral_symm, intervalIntegral.integral_symm,
    stieltjesIntegral_eq_intervalIntegral_of_contDiffOn' B hba hg hf]

/-- Special case of previous when `g x = x`. -/
theorem stieltjesIntegral_eq_intervalIntegral_of_riemannIntegrable
{f : ℝ → E} {a b : ℝ} (hf : RiemannIntegrable (min a b) (max a b) f) :
  ∫⟨(lsmul ℝ ℝ).flip⟩ x in a..b, f x ∂id = ∫ x in a..b, f x := by
  convert stieltjesIntegral_eq_intervalIntegral_of_contDiffOn _
    (ContDiff.contDiffOn contDiff_id) hf using 3 with x
  simp

/-! ### Sums as Stieltjes integrals -/

/-- Relate sums ∑ f(n) with Stieltjes integrals ∫ f ∂⌊x⌋ -/
theorem sum_eq_integral_nat_floor {a b : ℝ} (hab : a < b) (f : ℝ → E) :
    HasStieltjesIntegral a b (lsmul ℝ ℝ).flip f
      (fun x ↦ ⌊x⌋₊)
      (∑ n ∈ Finset.Ico ⌈a⌉₊ ⌈b⌉₊, f n) := by sorry

theorem sum_eq_integral_int_floor {a b : ℝ} (hab : a < b) (f : ℝ → E) :
    HasStieltjesIntegral a b (lsmul ℝ ℝ).flip f
      (fun x ↦ ⌊x⌋)
      (∑ n ∈ Finset.Ico ⌈a⌉ ⌈b⌉, f n) := by sorry

/-- Sum of pairings `B (f n) (g n)` over natural `n ∈ (⌊a⌋, ⌊b⌋]`, expressed as a Stieltjes
integral of `f` against the right-continuous summatory `x ↦ ∑ n ≤ x, g n`. -/
theorem sum_eq_integral_natSummatory_le {a b : ℝ} (hab : a < b) (f : ℝ → E) (g : ℕ → F) :
    HasStieltjesIntegral a b B f
      (fun x ↦ ∑ n ∈ Finset.Iic ⌊x⌋₊, g n)
      (∑ n ∈ Finset.Ioc ⌊a⌋₊ ⌊b⌋₊, B (f n) (g n)) := by sorry

/-- Sum of pairings `B (f n) (g n)` over natural `n ∈ [⌈a⌉, ⌈b⌉)`, expressed as a Stieltjes
integral of `f` against the left-continuous summatory `x ↦ ∑ n < x, g n`. -/
theorem sum_eq_integral_natSummatory_lt {a b : ℝ} (hab : a < b) (f : ℝ → E) (g : ℕ → F) :
    HasStieltjesIntegral a b B f
      (fun x ↦ ∑ n ∈ Finset.Iio ⌈x⌉₊, g n)
      (∑ n ∈ Finset.Ico ⌈a⌉₊ ⌈b⌉₊, B (f n) (g n)) := by sorry

end BoxIntegral
