/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

Authors: Steven Creech, Jaume de Dios, Bogdan Georgiev, Harald Helfgott, Ayush Khaitan, Terence Tao

Thanks to ICERM for hosting the workshop "Formalization of Analysis" where most of this work
was conducted.
-/
module

public import Mathlib.Analysis.BoxIntegral.Stieltjes.Defs
public import Mathlib.Analysis.BoxIntegral.Partition.OrderedDivision
public import Mathlib.Topology.EMetricSpace.BoundedVariation
public import Mathlib.MeasureTheory.Integral.IntervalIntegral.Basic
public import Mathlib.Analysis.Calculus.ContDiff.Basic

/-! # Riemann–Stieltjes integral

In this file we establish fundamental properties of Riemann–Stieltjes integral
`∫⟨B⟩ x in a..b, f x ∂g` dfefined in `Analysis.BoxIntegral.Stieltjes.Defs`.

## Main theorems

* `BoxIntegral.Stieltjes.hasStieltjesIntegral_iff_lim_sum`: gives the textbook ε-δ characterization
of the Riemann--Stieltjes integral.
* `BoxIntegral.stieltjesIntegral.add_adjacent`: gives the splitting identity
  `∫⟨B⟩ x in a..c, f x ∂g = ∫⟨B⟩ x in a..b, f x ∂g + ∫⟨B⟩ x in b..c, f x ∂g`, regardless of
  the ordering of `a`, `b`, `c`.
* `BoxIntegral.exists_of_continuousOn_of_boundedVariationOn` (Theorem A.1): if `f` is continuous
  and `g` has bounded variation on `[a, b]`, then the Riemann–Stieltjes integral exists.
* `BoxIntegral.stieltjesIntegral.by_parts` (Theorem A.2): if `∫⟨B⟩ x in a..b, f x ∂g` exists, then
  so does `∫⟨B⟩ x in a..b, g x ∂f`, and the two are related by the integration by parts identity
  `∫⟨B⟩ x in a..b, g x ∂f = B (f b) (g b) - B (f a) (g a) - ∫⟨B⟩ x in a..b, f x ∂g`.
* `BoxIntegral.variation_of_derivative` (Theorem A.3(a)) and
  `BoxIntegral.integral_of_derivative` (Theorem A.3(b)): when `g` is `C¹`, the total variation
  and the Riemann–Stieltjes integral can be computed by `g′`.
* `BoxIntegral.integral_le_integral_of_variation` (Theorem A.4): a norm bound on the integral
  in terms of the variation of `g`.
* `BoxIntegral.stieltjesIntegral_eq_intervalIntegral_of_riemannIntegrable`: the Riemann-Stieltjes
integral `∫⟨lsmul ℝ ℝ⟩ x in a..b, f x ∂id` agrees with the interval integral
`∫ x in a..b, f x` when `f` is Riemann integrable.
* `BoxIntegral.sum_eq_integral_nat_floor` and `BoxIntegral.sum_eq_integral_int_floor`: relate
  sums `∑ f n` to Riemann–Stieltjes integrals against the floor function.
* `BoxIntegral.sum_eq_integral_natSummatory_le` / `_lt` : relate sums `∑ B (f n) (g n)` to
  Riemann–Stieltjes integrals against the right- or left-continuous summatory function
  `x ↦ ∑ n ≤ x, g n` (resp. `x ↦ ∑ n < x, g n`).

## AI usage

* Much of the boilerplate API and docstrings was generated by AI, which was prompted to follow
existing Mathlib examples and style guides.  They were reviewed by human authors, but in
several cases no substantive improvement to the AI-generated code was found.

* More mathematically complex theorems were largely proved by hand, though in some cases AI tools
were used to generate an initial proof structure (which was then often revised either by hand,
or by further conversation with the AI agent).

* AI was also used to generate initial text for docstrings.

## References

* H. L. Montgomery and R. C. Vaughan, *Multiplicative Number Theory I: Classical Theory*,
  Cambridge Studies in Advanced Mathematics 97, Cambridge University Press, 2007 (Appendix A).

## TODO

* Develop a higher-dimensional Stieltjes integral (exists in the literature, but is rarely used)
* Develop a Stieltjes integral based around `Ico` intervals rather than `Ioc` intervals
* Other variants of Stieltjes integration, such as the Henstock-Stieltjes integral
* Change of variables formula wrt monotone substitutions
* Interpretation of `ofDiff` as a measure (assuming monotonicity)
* Interpretation of `ofDiff` as a signed measure (assuming bounded variation).  This requires
the development of signed measures in Mathlib
* Example: decay of Fourier transforms of total variation functions

## Tags

Stieltjes integral, Riemann–Stieltjes, bounded variation
-/

@[expose] public section

open scoped BigOperators
open BoxIntegral

namespace BoxIntegral.TaggedDivision

namespace DualPartition

def x (π : TaggedDivision) : Fin (π.N + 2) → ℝ :=
  Fin.cons (π.x 0) (Fin.snoc π.tag (π.x (Fin.last π.N)))

@[simp]
theorem x_first (π : TaggedDivision) : x π 0 = π.x 0 := by
  simp [x]

@[simp]
theorem x_last (π : TaggedDivision) : x π (Fin.last (π.N + 1)) = π.x (Fin.last π.N) := by
  simp [x]

end DualPartition

def DualPartition (π : TaggedDivision) : TaggedDivision where
  N := π.N + 1
  tag := π.x
  x := DualPartition.x π

@[simp]
theorem DualPartition_first (π : TaggedDivision) : π.DualPartition.x 0 = π.x 0 := by
  exact DualPartition.x_first π

@[simp]
theorem DualPartition_last (π : TaggedDivision) :
    π.DualPartition.x (Fin.last π.DualPartition.N) = π.x (Fin.last π.N) := by
  exact DualPartition.x_last π

def RiemannStieltjesSum (π : TaggedDivision) (f g : ℝ → ℝ) : ℝ :=
  ∑ i : Fin π.N, f (π.tag i) * (g (π.x i.succ) - g (π.x i.castSucc))

end BoxIntegral.TaggedDivision


namespace BoxIntegral.TaggedDivision.RiemannStieltjesSum

@[simp]
theorem eq_zero_of_N_eq_zero (π : TaggedDivision) (hπ : π.N = 0) (f g : ℝ → ℝ) :
    π.RiemannStieltjesSum f g = 0 := by
  rcases π with ⟨⟨N, x⟩, tag⟩
  dsimp at hπ ⊢
  subst N
  simp [TaggedDivision.RiemannStieltjesSum]

theorem eq_dropLast_add
    (π : TaggedDivision) (hN : 0 < π.N) (f g : ℝ → ℝ) :
      π.RiemannStieltjesSum f g =
      π.dropLast.RiemannStieltjesSum f g +
      f (π.tag ⟨π.N - 1, by omega⟩) *
        (g (π.x (Fin.last π.N)) - g (π.x ⟨π.N - 1, by omega⟩)) := by
  rcases π with ⟨⟨N, x⟩, tag⟩
  dsimp [RiemannStieltjesSum, dropLast] at hN ⊢
  cases N with
  | zero => omega
  | succ n =>
      rw [Fin.sum_univ_castSucc]
      congr

theorem snoc (π : TaggedDivision) (c t : ℝ) (f g : ℝ → ℝ) :
    (π.snoc c t).RiemannStieltjesSum  f g =
      π.RiemannStieltjesSum  f g + f t * (g c - g (π.x (Fin.last π.N))) := by
  rcases π with ⟨⟨N, x⟩, tag⟩
  dsimp [RiemannStieltjesSum, TaggedDivision.snoc, BoxIntegral.OrderedDivision.snoc]
  rw [Fin.sum_univ_castSucc]
  congr 1
  · apply Finset.sum_congr rfl
    intro i hi
    have hs : i.castSucc.succ = i.succ.castSucc := by ext; simp
    have hxs : @Fin.snoc (N + 1) (fun _ => ℝ) x c i.castSucc.succ = x i.succ := by
      rw [hs, Fin.snoc_castSucc]
    rw [hxs]
    simp [Fin.snoc_castSucc]
  · simp [Fin.snoc_last, Fin.snoc_castSucc]

theorem removeDuplicates
    (π : TaggedDivision) (f g : ℝ → ℝ) :
    π.removeDuplicates.RiemannStieltjesSum f g =
      π.RiemannStieltjesSum f g := by
  revert f g
  induction π using TaggedDivision.recOnDropLast with
  | zero π h0 =>
    intro f g
    rw [TaggedDivision.removeDuplicates.of_N_eq_zero π h0]
  | step π hN ih =>
    intro f g
    have h0 : ¬π.N = 0 := by omega
    let y := π.x ⟨π.N - 1, by omega⟩
    let z := π.x (Fin.last π.N)
    let t := π.tag ⟨π.N - 1, by omega⟩
    let σ := π.dropLast.removeDuplicates
    have hσ_last : σ.x (Fin.last σ.N) = y := by
      dsimp [σ]
      rw [TaggedDivision.removeDuplicates.last π.dropLast]
      exact π.dropLast_last
    have hrec :
        σ.RiemannStieltjesSum f g =
          π.dropLast.RiemannStieltjesSum f g := by
      dsimp [σ]
      exact ih f g
    have hdrop := eq_dropLast_add π hN f g
    by_cases h : y = z
    · rw [TaggedDivision.removeDuplicates.of_last_eq π hN (by simpa [y, z] using h)]
      rw [hrec, hdrop]
      simp [y, z, h]
    · rw [TaggedDivision.removeDuplicates.of_last_ne π hN (by simpa [y, z] using h)]
      rw [snoc σ z t f g, hrec, hdrop]
      simp [hσ_last, y, z, t]

theorem by_parts (π : TaggedDivision) (f g : ℝ → ℝ) :
    π.RiemannStieltjesSum f g =
      (π.DualPartition).RiemannStieltjesSum g f := by sorry

end BoxIntegral.TaggedDivision.RiemannStieltjesSum
namespace mynamespace

/-! ## One-dimensional interval partitions

API for one-dimensional partitions and tagged partitions
-/

open BoxIntegral

noncomputable def toPartition {N : ℕ} {a b : ℝ}
    (x : Fin (N + 1) → ℝ) (hx : StrictMono x)
    (ha : (x 0) = a) (hb : x (Fin.last N) = b) : Prepartition (Ioc a b) where
      boxes := (Finset.univ : Finset (Fin N)).map
        ⟨fun i ↦ Ioc (x i.castSucc) (x i.succ), by sorry⟩
      le_of_mem' := by sorry
      pairwiseDisjoint := by sorry

noncomputable def toTaggedPartition {N : ℕ} {a b : ℝ}
    (x : Fin (N + 1) → ℝ) (hx : StrictMono x)
    (y : Fin N → ℝ) (hy : ∀ i : Fin N,  (x i.castSucc ≤ y i) ∧ (y i ≤ x i.succ))
    (ha : (x 0) = a) (hb : x (Fin.last N) = b) :
    TaggedPrepartition (Ioc a b) :=
    {toPartition x hx ha hb with
      tag := by
        classical
        exact fun J _ ↦
          if h : ∃ i : Fin N, Ioc (x i.castSucc) (x i.succ) = J then y h.choose else a
      tag_mem_Icc := by sorry
    }


theorem toPartition_isPartition {N : ℕ} {a b : ℝ} (hab : a < b)
    (x : Fin (N + 1) → ℝ) (hx : StrictMono x)
    (ha : (x 0) = a) (hb : x (Fin.last N) = b) :
    (toPartition x hx ha hb).IsPartition := by
  sorry


theorem fromPartition
    {a b : ℝ} (hab : a < b)
    (π : Prepartition (Ioc a b))
    (hπ : π.IsPartition) :
    letI N := Finset.card π.boxes
    ∃ (x : Fin (N + 1) → ℝ) (hx : StrictMono x) (ha : (x 0) = a) (hb : x (Fin.last N) = b),
     π = toPartition x hx ha hb := by
  sorry

theorem fromTaggedPartition
    {a b : ℝ} (hab : a < b)
    (π : TaggedPrepartition (Ioc a b))
    (hπ : π.IsPartition) :
    ∃ (N : ℕ) (x : Fin (N + 1) → ℝ) (hx : StrictMono x)
      (ha : (x 0) = a) (hb : x (Fin.last N) = b)
      (y : Fin N → ℝ) (hy : ∀ i : Fin N, (x i.castSucc ≤ y i) ∧ (y i ≤ x i.succ)),
      π.toPrepartition = toPartition x hx ha hb ∧
        ∀ i : Fin N, y i = π.tag (Ioc (x i.castSucc) (x i.succ)) 0 := by
  sorry

open TaggedPrepartition
variable {E : Type} {F : Type} [NormedAddCommGroup E] [NormedSpace ℝ E]
  [NormedAddCommGroup F] [NormedSpace ℝ F]

theorem taggedSum_eq_integralSum {N : ℕ} {a b : ℝ} (hab : a < b)
    (x : Fin (N + 1) → ℝ) (hx : StrictMono x)
    (y : Fin N → ℝ) (hy : ∀ i : Fin N,  (x i.castSucc ≤ y i) ∧ (y i ≤ x i.succ))
    (ha : (x 0) = a) (hb : x (Fin.last N) = b)
    (vol : (Fin 1) →ᵇᵃ E →L[ℝ] F)
    (f :  ℝ → E):
    integralSum (fun x => (f (x 1))) vol (toTaggedPartition x hx y hy ha hb) =
      Finset.sum (Finset.univ)
        (fun i: Fin N ↦ (vol (Ioc (x i.succ) (x i.castSucc))) (f (y i))) := by
  sorry

end mynamespace

open BoxIntegral ContinuousLinearMap

namespace BoxIntegral

variable {E : Type*} {F : Type*} {G : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
  [NormedAddCommGroup F] [NormedSpace ℝ F] [NormedAddCommGroup G] [NormedSpace ℝ G]
variable (a b : ℝ) (B : E →L[ℝ] F →L[ℝ] G)

/-- The predicate `HasStieltjesIntegral` matches the usual epsilon-delta definition, at least if
one uses unordered partitions of the interval. -/
theorem hasStieltjesIntegral_iff_lim_sum {a b : ℝ} (hab : a < b) (f : ℝ → E) (g : ℝ → F) (L : G) :
    HasStieltjesIntegral a b B f g L ↔
    ∀ ε > 0, ∃ δ > 0, ∀ π : TaggedPrepartition (Ioc a b), π.IsHenstock → π.IsPartition
    → π.mesh_size ≤ δ →
     dist (∑ x ∈ π.boxes, ((B (f (π.tag x 0))) (g (x.upper 0) - g (x.lower 0)))) L < ε := by
  simp only [HasStieltjesIntegral.of_lt, hab, HasStieltjesIntegral', Fin.isValue,
  HasIntegral_Riemann_iff, gt_iff_lt, integralSum,
    BoxAdditiveMap.ofDiff_apply, coe_sub', Pi.sub_apply, flip_apply, Finset.sum_sub_distrib,
    dist_sub_eq_dist_add_left, map_sub]

theorem hasRiemannIntegral_iff_lim_sum {a b : ℝ} (hab : a < b) (f : ℝ → E) (L : E) :
    HasRiemannIntegral a b f L ↔
    ∀ ε > 0, ∃ δ > 0, ∀ π : TaggedPrepartition (Ioc a b), π.IsHenstock → π.IsPartition
    → π.mesh_size ≤ δ →
     dist (∑ x ∈ π.boxes, ((x.upper 0) - (x.lower 0)) • (f (π.tag x 0))) L < ε := by
  rw [HasRiemannIntegral]
  exact hasStieltjesIntegral_iff_lim_sum _ hab _ _ L


/-! ## Linearity -/

/-! ### In the integrand -/

private theorem HasStieltjesIntegral'.zero_left {g : ℝ → F} : HasStieltjesIntegral' a b B 0 g 0 :=
  hasIntegral_zero

theorem HasStieltjesIntegral.zero_left {g : ℝ → F} : HasStieltjesIntegral a b B 0 g 0 := by
  rcases lt_trichotomy a b with h | rfl | h
  · simp only [of_lt, h, HasStieltjesIntegral'.zero_left]
  · simp
  rw [symm_iff]
  simp only [neg_zero, h, of_lt, HasStieltjesIntegral'.zero_left]

private theorem HasStieltjesIntegral'.add_left {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G}
    {f₁ f₂ : ℝ → E} {g : ℝ → F} {L₁ L₂ : G}
    (h₁ : HasStieltjesIntegral' a b B f₁ g L₁) (h₂ : HasStieltjesIntegral' a b B f₂ g L₂) :
    HasStieltjesIntegral' a b B (f₁ + f₂) g (L₁ + L₂) :=
  HasIntegral.add h₁ h₂

theorem HasStieltjesIntegral.add_left {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G}
    {f₁ f₂ : ℝ → E} {g : ℝ → F} {L₁ L₂ : G}
    (h₁ : HasStieltjesIntegral a b B f₁ g L₁) (h₂ : HasStieltjesIntegral a b B f₂ g L₂) :
    HasStieltjesIntegral a b B (f₁ + f₂) g (L₁ + L₂) := by
  rcases lt_trichotomy a b with h | rfl | h
  · simp only [of_lt, h] at h₁ h₂ ⊢
    exact h₁.add_left h₂
  · simp_all
  rw [symm_iff] at h₁ h₂ ⊢
  simp only [h, of_lt, neg_add] at h₁ h₂ ⊢
  exact h₁.add_left h₂

private theorem HasStieltjesIntegral'.neg_left {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G}
    {f : ℝ → E} {g : ℝ → F} {L : G} (h : HasStieltjesIntegral' a b B f g L) :
    HasStieltjesIntegral' a b B (-f) g (-L) :=
  HasIntegral.neg h

theorem HasStieltjesIntegral.neg_left {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G}
    {f : ℝ → E} {g : ℝ → F} {L : G} (h : HasStieltjesIntegral a b B f g L) :
    HasStieltjesIntegral a b B (-f) g (-L) := by
  rcases lt_trichotomy a b with hab | rfl | hab
  · simp only [of_lt, hab] at h ⊢
    apply h.neg_left
  · simp_all
  rw [symm_iff] at h ⊢
  simp only [hab, of_lt] at h ⊢
  apply h.neg_left

private theorem HasStieltjesIntegral'.sub_left {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G}
    {f₁ f₂ : ℝ → E} {g : ℝ → F} {L₁ L₂ : G}
    (h₁ : HasStieltjesIntegral' a b B f₁ g L₁) (h₂ : HasStieltjesIntegral' a b B f₂ g L₂) :
    HasStieltjesIntegral' a b B (f₁ - f₂) g (L₁ - L₂) :=
  HasIntegral.sub h₁ h₂

theorem HasStieltjesIntegral.sub_left {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G}
    {f₁ f₂ : ℝ → E} {g : ℝ → F} {L₁ L₂ : G}
    (h₁ : HasStieltjesIntegral a b B f₁ g L₁) (h₂ : HasStieltjesIntegral a b B f₂ g L₂) :
    HasStieltjesIntegral a b B (f₁ - f₂) g (L₁ - L₂) := by
  rcases lt_trichotomy a b with h | rfl | h
  · simp only [of_lt, h] at h₁ h₂ ⊢
    exact h₁.sub_left h₂
  · simp_all
  rw [symm_iff] at h₁ h₂ ⊢
  simp only [h, of_lt] at h₁ h₂ ⊢
  convert h₁.sub_left h₂ using 1
  abel

private theorem HasStieltjesIntegral'.smul_left {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G}
    {f : ℝ → E} {g : ℝ → F} {L : G} (h : HasStieltjesIntegral' a b B f g L) (c : ℝ) :
    HasStieltjesIntegral' a b B (c • f) g (c • L) :=
  HasIntegral.smul h c

theorem HasStieltjesIntegral.smul_left {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G}
    {f : ℝ → E} {g : ℝ → F} {L : G} (h : HasStieltjesIntegral a b B f g L) (c : ℝ) :
    HasStieltjesIntegral a b B (c • f) g (c • L) := by
  rcases lt_trichotomy a b with hab | rfl | hab
  · simp only [of_lt, hab] at h ⊢
    apply h.smul_left
  · simp_all
  rw [symm_iff] at h ⊢
  simp only [hab, of_lt] at h ⊢
  convert h.smul_left _ using 1
  norm_num

/-! ### In the integrator -/

private theorem HasStieltjesIntegral'.const_right {f : ℝ → E} (c : F) :
    HasStieltjesIntegral' a b B f (fun _ ↦ c) 0 := by
  simp only [HasStieltjesIntegral', Fin.isValue, BoxAdditiveMap.ofDiff_const, hasIntegral_zero_vol]

theorem HasStieltjesIntegral.const_right {f : ℝ → E} (c : F) :
    HasStieltjesIntegral a b B f (fun _ ↦ c) 0 := by
  rcases lt_trichotomy a b with hab | rfl | hab
  · simp only [of_lt, hab] at ⊢
    apply HasStieltjesIntegral'.const_right
  · simp_all
  rw [symm_iff] at ⊢
  simp only [neg_zero, hab, of_lt] at ⊢
  apply HasStieltjesIntegral'.const_right

theorem HasStieltjesIntegral.zero_right {f : ℝ → E} : HasStieltjesIntegral a b B f 0 0 :=
  const_right a b B 0

private theorem HasStieltjesIntegral'.add_right {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G}
    {f : ℝ → E} {g₁ g₂ : ℝ → F} {L₁ L₂ : G}
    (h₁ : HasStieltjesIntegral' a b B f g₁ L₁) (h₂ : HasStieltjesIntegral' a b B f g₂ L₂) :
    HasStieltjesIntegral' a b B f (g₁ + g₂) (L₁ + L₂) := by
  unfold HasStieltjesIntegral' at h₁ h₂ ⊢
  have h : (fun x : ℝ ↦ B.flip ((g₁ + g₂) x)) =
      (fun x ↦ B.flip (g₁ x)) + (fun x ↦ B.flip (g₂ x)) := by ext; simp
  rw [h, map_add]
  exact h₁.add_vol h₂

theorem HasStieltjesIntegral.add_right {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G}
    {f : ℝ → E} {g₁ g₂ : ℝ → F} {L₁ L₂ : G}
    (h₁ : HasStieltjesIntegral a b B f g₁ L₁) (h₂ : HasStieltjesIntegral a b B f g₂ L₂) :
    HasStieltjesIntegral a b B f (g₁ + g₂) (L₁ + L₂) := by
  rcases lt_trichotomy a b with hab | rfl | hab
  · simp only [of_lt, hab] at h₁ h₂ ⊢
    exact h₁.add_right h₂
  · simp_all
  rw [symm_iff] at h₁ h₂ ⊢
  simp only [hab, of_lt] at h₁ h₂ ⊢
  convert h₁.add_right h₂ using 1
  abel

private theorem HasStieltjesIntegral'.neg_right {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G}
    {f : ℝ → E} {g : ℝ → F} {L : G} (h : HasStieltjesIntegral' a b B f g L) :
    HasStieltjesIntegral' a b B f (-g) (-L) := by
  unfold HasStieltjesIntegral' at h ⊢
  have heq : (fun x : ℝ ↦ B.flip ((-g) x)) = -(fun x ↦ B.flip (g x)) := by ext; simp
  rw [heq, map_neg]
  exact h.neg_vol

theorem HasStieltjesIntegral.neg_right {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G}
    {f : ℝ → E} {g : ℝ → F} {L : G} (h : HasStieltjesIntegral a b B f g L) :
    HasStieltjesIntegral a b B f (-g) (-L) := by
  rcases lt_trichotomy a b with hab | rfl | hab
  · simp only [of_lt, hab] at h ⊢
    apply h.neg_right
  · simp_all
  rw [symm_iff] at h ⊢
  simp only [hab, of_lt, neg_neg] at h ⊢
  convert h.neg_right using 1
  norm_num

theorem HasStieltjesIntegral'.sub_right {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G}
    {f : ℝ → E} {g₁ g₂ : ℝ → F} {L₁ L₂ : G}
    (h₁ : HasStieltjesIntegral' a b B f g₁ L₁) (h₂ : HasStieltjesIntegral' a b B f g₂ L₂) :
    HasStieltjesIntegral' a b B f (g₁ - g₂) (L₁ - L₂) := by
  unfold HasStieltjesIntegral' at h₁ h₂ ⊢
  have h : (fun x : ℝ ↦ B.flip ((g₁ - g₂) x)) =
      (fun x ↦ B.flip (g₁ x)) - (fun x ↦ B.flip (g₂ x)) := by ext; simp
  rw [h, map_sub]
  exact h₁.sub_vol h₂

theorem HasStieltjesIntegral.sub_right {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G}
    {f : ℝ → E} {g₁ g₂ : ℝ → F} {L₁ L₂ : G}
    (h₁ : HasStieltjesIntegral a b B f g₁ L₁) (h₂ : HasStieltjesIntegral a b B f g₂ L₂) :
    HasStieltjesIntegral a b B f (g₁ - g₂) (L₁ - L₂) := by
  rcases lt_trichotomy a b with hab | rfl | hab
  · simp only [of_lt, hab] at h₁ h₂ ⊢
    exact h₁.sub_right h₂
  · simp_all
  rw [symm_iff] at h₁ h₂ ⊢
  simp only [hab, of_lt] at h₁ h₂ ⊢
  convert h₁.sub_right h₂ using 1
  abel

private theorem HasStieltjesIntegral'.smul_right {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G}
    {f : ℝ → E} {g : ℝ → F} {L : G} (h : HasStieltjesIntegral' a b B f g L) (c : ℝ) :
    HasStieltjesIntegral' a b B f (c • g) (c • L) := by
  unfold HasStieltjesIntegral' at h ⊢
  have heq : (fun x : ℝ ↦ B.flip ((c • g) x)) = c • (fun x ↦ B.flip (g x)) := by ext; simp
  rw [heq, BoxIntegral.BoxAdditiveMap.ofDiff_smul]
  exact h.smul_vol c

theorem HasStieltjesIntegral.smul_right {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G}
    {f : ℝ → E} {g : ℝ → F} {L : G}
    (h : HasStieltjesIntegral a b B f g L) (c : ℝ) :
    HasStieltjesIntegral a b B f (c • g) (c • L) := by
  rcases lt_trichotomy a b with hab | rfl | hab
  · simp only [of_lt, hab] at h ⊢
    apply h.smul_right
  · simp_all
  rw [symm_iff] at h ⊢
  simp only [hab, of_lt] at h ⊢
  convert h.smul_right _ using 1
  norm_num

/-! ### Splitting over adjacent intervals -/

private theorem HasStieltjesIntegral'.add_adjacent [CompleteSpace G]
    {f : ℝ → E} {g : ℝ → F} {L L' : G} {a b c : ℝ} {B : E →L[ℝ] F →L[ℝ] G}
    (hab : a < b) (hbc : b < c)
    (h : StieltjesIntegrable' a c B f g)
    (h₁ : HasStieltjesIntegral' a b B f g L)
    (h₂ : HasStieltjesIntegral' b c B f g L') :
    HasStieltjesIntegral' a c B f g (L + L') := by
  simp only [HasStieltjesIntegral', StieltjesIntegrable'] at h h₁ h₂ ⊢
  have hac : a < c := hab.trans hbc
  have hb_mem :
      b ∈ Set.Ioo ((Ioc a c).lower 0) ((Ioc a c).upper 0) := by
    simp [hac, hab, hbc]
  refine HasIntegral.split 0 b ?_ ?_ h h₁ h₂
  · rw [Box.splitLower_def hb_mem, WithBot.coe_eq_coe]
    ext x
    simp [hac, hab]
  · rw [Box.splitUpper_def hb_mem, WithBot.coe_eq_coe]
    ext x
    simp [hac, hbc]

private theorem HasStieltjesIntegral.add_adjacent_prelim [CompleteSpace G]
    {f : ℝ → E} {g : ℝ → F} {L L' L'' : G} {a b c : ℝ} {B : E →L[ℝ] F →L[ℝ] G}
    (hab : a < b) (hbc : b < c)
    (h₁ : HasStieltjesIntegral a b B f g L)
    (h₂ : HasStieltjesIntegral b c B f g L')
    (h₃ : HasStieltjesIntegral a c B f g L'') :
    L'' = L + L' := by
  apply unique h₃
  simp only [hab, of_lt, hbc, hab.trans hbc] at h₁ h₂ h₃ ⊢
  exact HasStieltjesIntegral'.add_adjacent hab hbc ⟨L'', h₃⟩ h₁ h₂

/-- If `f` is Stieltjes-integrable from `a` to `c`, has Stieltjes integral `L` from `a` to `b`
and `L'` from `b` to `c` then `f` has Stieltjes integral `L + L'` from `a` to `c`.  No ordering
is assumed in `a`, `b`, `c` in the final statement of the theorem.

TODO: reduce the amount of case splitting in the proof. -/
theorem HasStieltjesIntegral.add_adjacent [CompleteSpace G]
    {f : ℝ → E} {g : ℝ → F} {L L' : G} {a b c : ℝ} {B : E →L[ℝ] F →L[ℝ] G}
    (h : StieltjesIntegrable a c B f g)
    (h₁ : HasStieltjesIntegral a b B f g L)
    (h₂ : HasStieltjesIntegral b c B f g L') :
    HasStieltjesIntegral a c B f g (L + L') := by
  have h₃ := h.hasStieltjesIntegral
  by_cases! hab : a = b
  · simp_all
  by_cases! hbc : b = c
  · simp_all
  by_cases! hac : a = c
  · simp_all; simp [h₁.unique h₂.symm]
  have h₁' := h₁.symm
  have h₂' := h₂.symm
  have h₃' := h₃.symm
  convert h₃
  rcases lt_or_gt_of_ne hab with hab | hba <;>
  rcases lt_or_gt_of_ne hbc with hbc | hcb <;>
  rcases lt_or_gt_of_ne hac with hac | hca <;>
  try order
  · simp_all [add_adjacent_prelim hab hbc h₁ h₂ h₃]
  · have := add_adjacent_prelim hac hcb h₃ h₂' h₁
    grind
  · have := add_adjacent_prelim hca hab h₃' h₁ h₂'
    grind
  · have := add_adjacent_prelim hba hac h₁' h₃ h₂
    grind
  · have := add_adjacent_prelim hbc hca h₂ h₃' h₁'
    grind
  · have := add_adjacent_prelim hcb hba h₂' h₁' h₃'
    grind

theorem stieltjesIntegral.add_adjacent [CompleteSpace G]
    {f : ℝ → E} {g : ℝ → F} {a b c : ℝ} {B : E →L[ℝ] F →L[ℝ] G}
    (h : StieltjesIntegrable a c B f g)
    (h₁ : StieltjesIntegrable a b B f g)
    (h₂ : StieltjesIntegrable b c B f g) :
    ∫⟨B⟩ x in a..c, f x ∂g = ∫⟨B⟩ x in a..b, f x ∂g + ∫⟨B⟩ x in b..c, f x ∂g := by
  have := HasStieltjesIntegral.add_adjacent h h₁.hasStieltjesIntegral h₂.hasStieltjesIntegral
  rwa [h.hasStieltjesIntegral_iff] at this

/-! ### Integrability in the integrand -/

theorem StieltjesIntegrable.zero_left {g : ℝ → F} : StieltjesIntegrable a b B 0 g :=
  (HasStieltjesIntegral.zero_left a b B).stieltjesIntegrable

theorem StieltjesIntegrable.add_left {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G} {f₁ f₂ : ℝ → E} {g : ℝ → F}
    (h₁ : StieltjesIntegrable a b B f₁ g) (h₂ : StieltjesIntegrable a b B f₂ g) :
    StieltjesIntegrable a b B (f₁ + f₂) g :=
  (h₁.hasStieltjesIntegral.add_left h₂.hasStieltjesIntegral).stieltjesIntegrable

theorem StieltjesIntegrable.neg_left {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G} {f : ℝ → E} {g : ℝ → F}
    (h : StieltjesIntegrable a b B f g) : StieltjesIntegrable a b B (-f) g :=
  h.hasStieltjesIntegral.neg_left.stieltjesIntegrable

theorem StieltjesIntegrable.sub_left {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G} {f₁ f₂ : ℝ → E} {g : ℝ → F}
    (h₁ : StieltjesIntegrable a b B f₁ g) (h₂ : StieltjesIntegrable a b B f₂ g) :
    StieltjesIntegrable a b B (f₁ - f₂) g :=
  (h₁.hasStieltjesIntegral.sub_left h₂.hasStieltjesIntegral).stieltjesIntegrable

theorem StieltjesIntegrable.smul_left {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G} {f : ℝ → E} {g : ℝ → F}
    (h : StieltjesIntegrable a b B f g) (c : ℝ) : StieltjesIntegrable a b B (c • f) g :=
  (h.hasStieltjesIntegral.smul_left c).stieltjesIntegrable

/-! ### Integrability in the integrator -/

theorem StieltjesIntegrable.const_right {f : ℝ → E} (c : F) :
    StieltjesIntegrable a b B f (fun _ ↦ c) :=
  (HasStieltjesIntegral.const_right a b B c).stieltjesIntegrable

theorem StieltjesIntegrable.zero_right {f : ℝ → E} : StieltjesIntegrable a b B f 0 :=
  const_right a b B 0

theorem StieltjesIntegrable.add_right {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G} {f : ℝ → E} {g₁ g₂ : ℝ → F}
    (h₁ : StieltjesIntegrable a b B f g₁) (h₂ : StieltjesIntegrable a b B f g₂) :
    StieltjesIntegrable a b B f (g₁ + g₂) :=
  (h₁.hasStieltjesIntegral.add_right h₂.hasStieltjesIntegral).stieltjesIntegrable

theorem StieltjesIntegrable.neg_right {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G} {f : ℝ → E} {g : ℝ → F}
    (h : StieltjesIntegrable a b B f g) : StieltjesIntegrable a b B f (-g) :=
  h.hasStieltjesIntegral.neg_right.stieltjesIntegrable

theorem StieltjesIntegrable.sub_right {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G} {f : ℝ → E} {g₁ g₂ : ℝ → F}
    (h₁ : StieltjesIntegrable a b B f g₁) (h₂ : StieltjesIntegrable a b B f g₂) :
    StieltjesIntegrable a b B f (g₁ - g₂) :=
  (h₁.hasStieltjesIntegral.sub_right h₂.hasStieltjesIntegral).stieltjesIntegrable

theorem StieltjesIntegrable.smul_right {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G} {f : ℝ → E} {g : ℝ → F}
    (h : StieltjesIntegrable a b B f g) (c : ℝ) : StieltjesIntegrable a b B f (c • g) :=
  (h.hasStieltjesIntegral.smul_right c).stieltjesIntegrable

/-! ### Integral linearity in the integrand -/

theorem stieltjesIntegral_zero_left {g : ℝ → F} : ∫⟨B⟩ _ in a..b, 0 ∂g = 0 :=
  (HasStieltjesIntegral.zero_left a b B).stieltjesIntegral_eq

theorem stieltjesIntegral_add_left {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G} {f₁ f₂ : ℝ → E} {g : ℝ → F}
    (h₁ : StieltjesIntegrable a b B f₁ g) (h₂ : StieltjesIntegrable a b B f₂ g) :
    ∫⟨B⟩ x in a..b, (f₁ + f₂) x ∂g
      = ∫⟨B⟩ x in a..b, f₁ x ∂g + ∫⟨B⟩ x in a..b, f₂ x ∂g := by
  rw [(h₁.hasStieltjesIntegral.add_left h₂.hasStieltjesIntegral).stieltjesIntegral_eq,
    h₁.hasStieltjesIntegral.stieltjesIntegral_eq,
    h₂.hasStieltjesIntegral.stieltjesIntegral_eq]

theorem stieltjesIntegral_neg_left {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G} {f : ℝ → E} {g : ℝ → F}
    (h : StieltjesIntegrable a b B f g) :
    ∫⟨B⟩ x in a..b, (-f) x ∂g = -∫⟨B⟩ x in a..b, f x ∂g := by
  rw [h.hasStieltjesIntegral.neg_left.stieltjesIntegral_eq,
    h.hasStieltjesIntegral.stieltjesIntegral_eq]

theorem stieltjesIntegral_sub_left {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G} {f₁ f₂ : ℝ → E} {g : ℝ → F}
    (h₁ : StieltjesIntegrable a b B f₁ g) (h₂ : StieltjesIntegrable a b B f₂ g) :
    ∫⟨B⟩ x in a..b, (f₁ - f₂) x ∂g
      = ∫⟨B⟩ x in a..b, f₁ x ∂g - ∫⟨B⟩ x in a..b, f₂ x ∂g := by
  rw [(h₁.hasStieltjesIntegral.sub_left h₂.hasStieltjesIntegral).stieltjesIntegral_eq,
    h₁.hasStieltjesIntegral.stieltjesIntegral_eq,
    h₂.hasStieltjesIntegral.stieltjesIntegral_eq]

theorem stieltjesIntegral_smul_left {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G} {f : ℝ → E} {g : ℝ → F}
    (h : StieltjesIntegrable a b B f g) (c : ℝ) :
    ∫⟨B⟩ x in a..b, (c • f) x ∂g = c • ∫⟨B⟩ x in a..b, f x ∂g := by
  rw [(h.hasStieltjesIntegral.smul_left c).stieltjesIntegral_eq,
    h.hasStieltjesIntegral.stieltjesIntegral_eq]

/-! ### Integral linearity in the integrator -/

@[simp]
theorem stieltjesIntegral_const_right {f : ℝ → E} (c : F) : ∫⟨B⟩ x in a..b, f x ∂(fun _ ↦ c) = 0 :=
  (HasStieltjesIntegral.const_right a b B c).stieltjesIntegral_eq

@[simp]
theorem stieltjesIntegral_zero_right {f : ℝ → E} : ∫⟨B⟩ x in a..b, f x ∂0 = 0 :=
  stieltjesIntegral_const_right a b B 0

theorem stieltjesIntegral_add_right {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G} {f : ℝ → E} {g₁ g₂ : ℝ → F}
    (h₁ : StieltjesIntegrable a b B f g₁) (h₂ : StieltjesIntegrable a b B f g₂) :
    ∫⟨B⟩ x in a..b, f x ∂(g₁ + g₂)
      = ∫⟨B⟩ x in a..b, f x ∂g₁ + ∫⟨B⟩ x in a..b, f x ∂g₂ := by
  rw [(h₁.hasStieltjesIntegral.add_right h₂.hasStieltjesIntegral).stieltjesIntegral_eq,
    h₁.hasStieltjesIntegral.stieltjesIntegral_eq,
    h₂.hasStieltjesIntegral.stieltjesIntegral_eq]

theorem stieltjesIntegral_neg_right {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G} {f : ℝ → E} {g : ℝ → F}
    (h : StieltjesIntegrable a b B f g) :
    ∫⟨B⟩ x in a..b, f x ∂(-g) = -∫⟨B⟩ x in a..b, f x ∂g := by
  rw [(h.hasStieltjesIntegral.neg_right).stieltjesIntegral_eq,
    h.hasStieltjesIntegral.stieltjesIntegral_eq]

theorem stieltjesIntegral_sub_right {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G} {f : ℝ → E} {g₁ g₂ : ℝ → F}
    (h₁ : StieltjesIntegrable a b B f g₁) (h₂ : StieltjesIntegrable a b B f g₂) :
    ∫⟨B⟩ x in a..b, f x ∂(g₁ - g₂)
      = ∫⟨B⟩ x in a..b, f x ∂g₁ - ∫⟨B⟩ x in a..b, f x ∂g₂ := by
  rw [(h₁.hasStieltjesIntegral.sub_right h₂.hasStieltjesIntegral).stieltjesIntegral_eq,
    h₁.hasStieltjesIntegral.stieltjesIntegral_eq,
    h₂.hasStieltjesIntegral.stieltjesIntegral_eq]

theorem stieltjesIntegral_smul_right {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G} {f : ℝ → E} {g : ℝ → F}
    (h : StieltjesIntegrable a b B f g) (c : ℝ) :
    ∫⟨B⟩ x in a..b, f x ∂(c • g) = c • ∫⟨B⟩ x in a..b, f x ∂g := by
  rw [(h.hasStieltjesIntegral.smul_right c).stieltjesIntegral_eq,
    h.hasStieltjesIntegral.stieltjesIntegral_eq]

/-! ### Naturality: transporting along continuous linear maps -/

/-- If a bilinear pairing `B : E →L[ℝ] F →L[ℝ] G` and CLMs `φ : E →L[ℝ] E'`, `ψ : F →L[ℝ] F'`,
`Ψ : G →L[ℝ] G'` satisfy the compatibility `Ψ (B e y) = B' (φ e) (ψ y)` for all `e, y`, then
`HasStieltjesIntegral` transports along `(φ, ψ, Ψ)`: applying `φ` to the integrand, `ψ` to the
integrator and `Ψ` to the integral preserves the Stieltjes-integral relation. -/
private theorem HasStieltjesIntegral'.map {E' F' G' : Type*}
    [NormedAddCommGroup E'] [NormedSpace ℝ E']
    [NormedAddCommGroup F'] [NormedSpace ℝ F']
    [NormedAddCommGroup G'] [NormedSpace ℝ G']
    {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G} {f : ℝ → E} {g : ℝ → F} {L : G}
    {φ : E →L[ℝ] E'} {ψ : F →L[ℝ] F'} {Ψ : G →L[ℝ] G'}
    {B' : E' →L[ℝ] F' →L[ℝ] G'}
    (hB : ∀ e y, Ψ (B e y) = B' (φ e) (ψ y))
    (h : HasStieltjesIntegral' a b B f g L) :
    HasStieltjesIntegral' a b B' (fun x ↦ φ (f x)) (fun x ↦ ψ (g x)) (Ψ L) := by
  unfold HasStieltjesIntegral' at h ⊢
  refine HasIntegral.map φ Ψ ?_ h
  intro J e
  simp only [BoxIntegral.BoxAdditiveMap.ofDiff_apply, ContinuousLinearMap.sub_apply,
    ContinuousLinearMap.flip_apply, map_sub, hB]

theorem HasStieltjesIntegral.map {E' F' G' : Type*}
    [NormedAddCommGroup E'] [NormedSpace ℝ E']
    [NormedAddCommGroup F'] [NormedSpace ℝ F']
    [NormedAddCommGroup G'] [NormedSpace ℝ G']
    {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G} {f : ℝ → E} {g : ℝ → F} {L : G}
    {φ : E →L[ℝ] E'} {ψ : F →L[ℝ] F'} {Ψ : G →L[ℝ] G'}
    {B' : E' →L[ℝ] F' →L[ℝ] G'}
    (hB : ∀ e y, Ψ (B e y) = B' (φ e) (ψ y))
    (h : HasStieltjesIntegral a b B f g L) :
    HasStieltjesIntegral a b B' (fun x ↦ φ (f x)) (fun x ↦ ψ (g x)) (Ψ L) := by
  rcases lt_trichotomy a b with hab | rfl | hab
  · simp only [of_lt, hab] at h ⊢
    exact h.map hB
  · simp_all
  rw [symm_iff] at h ⊢
  simp only [hab, of_lt] at h ⊢
  convert h.map hB using 1
  simp

/-- Existence-level naturality: if `(B, B', φ, ψ, Ψ)` are compatible in the sense of
`HasStieltjesIntegral.map`, then `StieltjesIntegrable` is preserved when transporting
the integrand along `φ` and the integrator along `ψ`. -/
theorem StieltjesIntegrable.map {E' F' G' : Type*}
    [NormedAddCommGroup E'] [NormedSpace ℝ E']
    [NormedAddCommGroup F'] [NormedSpace ℝ F']
    [NormedAddCommGroup G'] [NormedSpace ℝ G']
    {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G} {f : ℝ → E} {g : ℝ → F}
    {φ : E →L[ℝ] E'} {ψ : F →L[ℝ] F'} {Ψ : G →L[ℝ] G'}
    {B' : E' →L[ℝ] F' →L[ℝ] G'}
    (hB : ∀ e y, Ψ (B e y) = B' (φ e) (ψ y))
    (h : StieltjesIntegrable a b B f g) :
    StieltjesIntegrable a b B' (fun x ↦ φ (f x)) (fun x ↦ ψ (g x)) :=
  (h.hasStieltjesIntegral.map hB).stieltjesIntegrable

/-- Function-level naturality of `stieltjesIntegral` under continuous linear maps. -/
theorem stieltjesIntegral_map {E' F' G' : Type*}
    [NormedAddCommGroup E'] [NormedSpace ℝ E']
    [NormedAddCommGroup F'] [NormedSpace ℝ F']
    [NormedAddCommGroup G'] [NormedSpace ℝ G']
    {f : ℝ → E} {B : E →L[ℝ] F →L[ℝ] G} {g : ℝ → F} {a b : ℝ}
    {φ : E →L[ℝ] E'} {ψ : F →L[ℝ] F'} {Ψ : G →L[ℝ] G'}
    {B' : E' →L[ℝ] F' →L[ℝ] G'}
    (hB : ∀ e y, Ψ (B e y) = B' (φ e) (ψ y))
    (h : StieltjesIntegrable a b B f g) :
    ∫⟨B'⟩ x in a..b, φ (f x) ∂(fun x ↦ ψ (g x)) =
      Ψ (∫⟨B⟩ x in a..b, f x ∂g) := by
  rw [(h.hasStieltjesIntegral.map hB).stieltjesIntegral_eq,
    h.hasStieltjesIntegral.stieltjesIntegral_eq]

/-! ### Integrability on subboxes -/

/-- If `f` is Stieltjes-integrable from `a` to `b` (with `a < b`) against `g`, then
it is also Stieltjes-integrable on any sub-interval `(c, d]` with `a ≤ c < d ≤ b`. -/
private theorem StieltjesIntegrable'.to_subbox [CompleteSpace G] {f : ℝ → E} {g : ℝ → F}
    {a b c d : ℝ} {B : E →L[ℝ] F →L[ℝ] G} (hab : a < b) (hcd : c < d) (hac : a ≤ c) (hdb : d ≤ b)
    (h : StieltjesIntegrable' a b B f g) :
    StieltjesIntegrable' c d B f g := by
  simp only [stieltjesIntegrable'_iff_integrable, Fin.isValue] at h ⊢
  have hle : Ioc c d ≤ Ioc a b := by
    simp [hab, hcd, hac, hdb]
  exact Integrable.to_subbox h hle

/-! ## Main theorems -/

/-- For any valid box partition of (a, b], the sum of the norm of the
differential `ofDiff g` is bounded by the total variation of g on the interval. -/
private lemma sum_norm_ofDiff_le_norm_mul_eVariationOn {a b : ℝ} (g : ℝ → F)
    (hg : BoundedVariationOn g (Set.Icc a b))
    (π : BoxIntegral.Prepartition (Ioc a b)) :
    ∑ J ∈ π.boxes, ‖(BoxIntegral.BoxAdditiveMap.ofDiff (fun x ↦ B.flip (g x))) J‖ ≤
      ‖B‖ * (eVariationOn g (Set.Icc a b)).toReal := by

  -- Step 1: Bound each local subbox evaluation by the operator norm of B.flip
  have h_term : ∀ J ∈ π.boxes, ‖(BoxIntegral.BoxAdditiveMap.ofDiff (fun x ↦ B.flip (g x))) J‖ ≤
      ‖B‖ * ‖g (J.upper 0) - g (J.lower 0)‖ := by
    intro J hJ
    change ‖B.flip (g (J.upper 0)) - B.flip (g (J.lower 0))‖ ≤ _
    rw [← map_sub, ← ContinuousLinearMap.opNorm_flip B]
    exact (B.flip).le_opNorm (g (J.upper 0) - g (J.lower 0))

  -- Step 2: Apply bound term-wise to sum and cancel operator norm
  refine (Finset.sum_le_sum h_term).trans ?_
  rw [← Finset.mul_sum]
  gcongr

  -- Step 3: Upgrade to ENNReal and convert vector norms cleanly to `edist`
  have h_sum_eq : ∑ J ∈ π.boxes, ‖g (J.upper 0) - g (J.lower 0)‖ =
      (ENNReal.ofReal (∑ J ∈ π.boxes, ‖g (J.upper 0) - g (J.lower 0)‖)).toReal :=
    (ENNReal.toReal_ofReal (Finset.sum_nonneg fun _ _ ↦ norm_nonneg _)).symm
  rw [h_sum_eq]
  refine ENNReal.toReal_mono (by exact hg) ?_
  rw [ENNReal.ofReal_sum_of_nonneg (fun _ _ ↦ norm_nonneg _)]
  simp_rw [← dist_eq_norm, ← edist_dist]

  sorry


/-- Continuous integrand and a
bounded-variation integrator give an integrable Riemann-Stieltjes box integrand. -/
private lemma integrable_of_continuousOn_of_boundedVariationOn [CompleteSpace G]
   {a b : ℝ} {f : ℝ → E} {g : ℝ → F} (hab : a < b) (l : IntegrationParams)
    (hf : ContinuousOn f (Set.Icc a b)) (hg : BoundedVariationOn g (Set.Icc a b)) :
    Integrable (Ioc a b) l
      (fun x ↦ f (x 0)) (BoxAdditiveMap.ofDiff (fun x ↦ B.flip (g x))) := by
  -- Step 1: Reduce integrability to the Cauchy convergence criterion over fine prepartitions
  let f' := fun x : Fin 1 → ℝ ↦ f (x 0)
  refine integrable_iff_cauchy_basis.2 fun ε hε ↦ ?_
  -- Step 2: Define global constants for total variation and bilinear scaling bounds
  let V : ℝ := (eVariationOn g (Set.Icc a b)).toReal
  rcases exists_pos_mul_lt hε (‖B‖ * V) with ⟨η, hη, hηC⟩
  -- Step 3: Extract the uniform continuity margin δ required to achieve our target error η
  rcases Metric.uniformContinuousOn_iff.mp (isCompact_Icc.uniformContinuousOn_of_continuous hf) η hη
    with ⟨δ, hδ, hδf⟩
  -- Step 4: Define a strictly positive, constant gauge ρ = δ / 4
  -- Forcing subboxes to have a radius ≤ δ / 4 ensures that any two tags inside overlapping
  -- subboxes are separated by a strict total distance of less than δ.
  let ρ : ℝ := δ / 4
  let r : NNReal → (Fin 1 → ℝ) → Set.Ioi (0 : ℝ) := fun _ _ ↦ ⟨ρ, by grind⟩
  refine ⟨r, fun _ _ _ ↦ by rfl, fun c₁ c₂ π₁ π₂ hπ₁ hpart₁ hπ₂ hpart₂ ↦ ?_⟩
  -- Evaluate the Cauchy distance between two arbitrary r-fine prepartitions π₁ and π₂
  let vol := BoxAdditiveMap.ofDiff (fun x ↦ B.flip (g x))
  let π := π₁.toPrepartition ⊓ π₂.toPrepartition
  let τ₁ := π₁.infPrepartition π₂.toPrepartition
  let τ₂ := π₂.infPrepartition π₁.toPrepartition
  have hsub₁ : τ₁.IsSubordinate (r c₁) := hπ₁.isSubordinate.infPrepartition _
  have hsub₂ : τ₂.IsSubordinate (r c₂) := hπ₂.isSubordinate.infPrepartition _
  -- Express the global difference of integral sums as the discrete sum of local subbox
  -- differences.
  have hdiff : integralSum f' vol π₁ - integralSum f' vol π₂ =
      ∑ J ∈ π.boxes, (vol J (f (τ₁.tag J 0)) - vol J (f (τ₂.tag J 0))) := by
    simpa [vol, π, τ₁, τ₂] using
      integralSum_sub_partitions f' vol hpart₁ hpart₂
  -- Step 5: Prove that each localized subbox evaluation is bounded strictly by η * ‖vol J‖
  have hterm : ∀ J ∈ π.boxes,
      ‖vol J (f (τ₁.tag J 0)) - vol J (f (τ₂.tag J 0))‖ ≤ ‖vol J‖ * η := by
    intro J hJ
    have hJτ₁ : J ∈ τ₁ := by change J ∈ τ₁.toPrepartition; simpa [π, τ₁] using hJ
    have hJτ₂ : J ∈ τ₂ := TaggedPrepartition.mem_infPrepartition_comm.mp hJτ₁
    -- Map local tag coordinates back inside the global ambient domain [a, b]
    have := τ₁.tag_mem_Icc J
    have := τ₂.tag_mem_Icc J
    -- Gauge subordination forces both tags to sit within ρ of the shared upper boundary corner
    have hτ₁_upper : dist (τ₁.tag J) J.upper ≤ ρ := by
      simpa [Metric.mem_closedBall, r, ρ, dist_comm] using hsub₁ J hJτ₁ J.upper_mem_Icc
    have hτ₂_upper : dist J.upper (τ₂.tag J) ≤ ρ := by
      simpa [Metric.mem_closedBall, r, ρ] using hsub₂ J hJτ₂ J.upper_mem_Icc
    -- Chain the tag metrics through the shared upper corner via the triangle inequality
    -- Trigger the uniform continuity bound using the coordinated metric separation
    -- Factor the bounded vector difference through the linear volume operator norm
    grw [← map_sub, (vol J).le_opNorm, ← dist_eq_norm]
    gcongr
    apply le_of_lt (hδf _ (by simp_all) _ (by simp_all) _)
    grw [dist_le_pi_dist, dist_triangle _ J.upper _]
    unfold ρ at *; linarith
  -- Step 6: Aggregate local bounds over the partition to confirm total metric distance < ε
  calc
    dist (integralSum f' vol π₁) (integralSum f' vol π₂)
      = ‖∑ J ∈ π.boxes, (vol J (f (τ₁.tag J 0)) - vol J (f (τ₂.tag J 0)))‖ := by
      simp only [dist_eq_norm, hdiff]
    _ ≤ (‖B‖ * V) * η := by
      grw [norm_sum_le, Finset.sum_le_sum hterm, ← Finset.sum_mul]
      gcongr
      exact sum_norm_ofDiff_le_norm_mul_eVariationOn B g hg π
    _ ≤ ε := by grind

/-- Theorem A.1 of Montgomery-Vaughan: a continuous integrand and a bounded-variation integrator
have a Riemann-Stieltjes integral. -/
theorem exists_of_continuousOn_of_boundedVariationOn [CompleteSpace G] {a b : ℝ}
    (f : ℝ → E) (g : ℝ → F) (hab : a < b)
    (hf : ContinuousOn f (Set.Icc a b)) (hg : BoundedVariationOn g (Set.Icc a b)) :
    StieltjesIntegrable a b B f g := by
  obtain ⟨L, hL⟩ := integrable_of_continuousOn_of_boundedVariationOn B
    hab IntegrationParams.Riemann hf hg
  use L
  simp [HasStieltjesIntegral, HasStieltjesIntegral', hab.ne, hab, hL]

/-- Theorem A.2 of Montgomery Vaughan: if ∫ₐᵇ f dg exists, then ∫ₐᵇ g df exists and
∫ₐᵇ g df = g(b) * f(b) - g(a) * f(a) - ∫ₐᵇ f dg. -/
theorem HasStieltjesIntegral.by_parts {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G}
    {f : ℝ → E} {g : ℝ → F} {L : G} (hL : HasStieltjesIntegral a b B f g L) :
    HasStieltjesIntegral a b B.flip g f (B (f b) (g b) - B (f a) (g a) - L) := by sorry

theorem StieltjesIntegrable.by_parts {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G} {f : ℝ → E} {g : ℝ → F}
    (h : StieltjesIntegrable a b B f g) :
    StieltjesIntegrable a b B.flip g f := by
  exact ⟨_, h.hasStieltjesIntegral.by_parts⟩

theorem stieltjesIntegral.by_parts {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G} {f : ℝ → E} {g : ℝ → F}
    (h : StieltjesIntegrable a b B f g) :
    ∫⟨B.flip⟩ x in a..b, g x ∂f = B (f b) (g b) - B (f a) (g a) - ∫⟨B⟩ x in a..b, f x ∂g := by
  rw [h.hasStieltjesIntegral.by_parts.stieltjesIntegral_eq,
    h.hasStieltjesIntegral.stieltjesIntegral_eq]

theorem HasStieltjesIntegral.of_const {a b : ℝ} (c : E) (g : ℝ → F) :
    HasStieltjesIntegral a b B (fun _ ↦ c) g (B c (g b) - B c (g a)) := by
  convert by_parts (B := B.flip) (f := g) (g := fun _ ↦ c) (L := 0) (by simp [const_right]) using 1
  simp [flip_apply]

theorem StieltjesIntegrable.of_const (c : E) (g : ℝ → F) :
    StieltjesIntegrable a b B (fun _ ↦ c) g :=
  (HasStieltjesIntegral.of_const B c g).stieltjesIntegrable

@[simp]
theorem stieltjesIntegral.of_const (c : E) (g : ℝ → F) :
    ∫⟨B⟩ _ in a..b, c ∂g = B c (g b) - B c (g a) :=
  (HasStieltjesIntegral.of_const B c g).stieltjesIntegral_eq

/-- Theorem A.3 (a).  If g′ is continuous on [a, b], then
Varₐᵇ g = ∫ₐᵇ ‖g′(x)‖ dx.
-/
theorem variation_of_derivative {a b : ℝ} {g : ℝ → F} (hab : a < b)
    (hg : ContDiffOn ℝ 1 g (Set.Icc a b)) :
    (eVariationOn g (Set.Icc a b)).toReal = ∫ x in a..b, ‖deriv g x‖ := by sorry

/-- Theorem A.3 (b).  If g′ is continuous on [a, b] and if in addition f is
Riemann integrable, then ∫ₐᵇ f(x) dg(x) = ∫ₐᵇ f(x) g′(x) dx. -/
theorem integral_of_derivative {a b : ℝ} {f : ℝ → E} {g : ℝ → F} (hab : a < b)
    (hg : ContDiffOn ℝ 1 g (Set.Icc a b))
    (hf : RiemannIntegrable a b f) :
    HasStieltjesIntegral a b B f g (∫ x in a..b, B (f x) (deriv g x)) := by sorry

/-- Theorem A.4. Suppose that g has bounded variation, and put g∗(x) = Varₐˣ g. Then
‖∫ₐᵇ f(x) dg(x)‖ ≤ ∫ₐᵇ ‖f(x)‖ dg∗(x),
provided that both integrals exist. -/
theorem integral_le_integral_of_variation {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G}
    {f : ℝ → E} {g : ℝ → F} {L : G} {L' : ℝ}
    (hab : a < b) (hg : BoundedVariationOn g (Set.Icc a b))
    (hfg : HasStieltjesIntegral a b B f g L)
    (hfabs_gstar : HasStieltjesIntegral a b (mul ℝ ℝ) (fun x ↦ ‖f x‖)
      (fun x ↦ (eVariationOn g (Set.Icc a x)).toReal) L') :
    ‖L‖ ≤ ‖B‖ * L' := by sorry

/-! ### Connection to standard integrals -/

/-- When the integrator is the identity, the Stieltjes integral with the scalar-multiplication
pairing `(lsmul ℝ ℝ).flip` reduces to the ordinary `BoxIntegral.HasIntegral` against the
Lebesgue volume on `(a, b]`. -/
theorem hasStieltjesIntegral_id_iff_hasIntegral_volume {a b : ℝ} (hab : a < b) (f : ℝ → E) (L : E) :
    HasStieltjesIntegral a b (lsmul ℝ ℝ).flip f id L ↔
      HasIntegral (Ioc a b) IntegrationParams.Riemann (fun x ↦ f (x 0))
        BoxAdditiveMap.volume L := by
    simp [hab, HasStieltjesIntegral', BoxAdditiveMap.ofDiff_lsmul_eq_volume]

/-- Function-level form of Theorem A.3(b) (`integral_of_derivative`): when `g` is `C¹` on
`[a, b]` and `f` is Riemann integrable, the Stieltjes integral of `f` against `g` equals the
Riemann integral of `B (f x) (g' x)`. -/
theorem stieltjesIntegral_eq_intervalIntegral_of_contDiffOn' {f : ℝ → E} {g : ℝ → F} {a b : ℝ}
    (hab : a < b) (hg : ContDiffOn ℝ 1 g (Set.Icc a b)) (hf : RiemannIntegrable a b f) :
    ∫⟨B⟩ x in a..b, f x ∂g = ∫ x in a..b, B (f x) (deriv g x) :=
  (integral_of_derivative B hab hg hf).stieltjesIntegral_eq

theorem stieltjesIntegral_eq_intervalIntegral_of_contDiffOn {f : ℝ → E} {g : ℝ → F} {a b : ℝ}
    (hg : ContDiffOn ℝ 1 g (Set.Icc (min a b) (max a b)))
    (hf : RiemannIntegrable (min a b) (max a b) f) :
    ∫⟨B⟩ x in a..b, f x ∂g = ∫ x in a..b, B (f x) (deriv g x) := by
  rcases lt_trichotomy a b with hab | rfl | hba
  · simp only [le_of_lt hab, inf_of_le_left, sup_of_le_right] at hg hf
    exact stieltjesIntegral_eq_intervalIntegral_of_contDiffOn' B hab hg hf
  · simp
  simp only [le_of_lt hba, inf_of_le_right, sup_of_le_left] at hg hf
  rw [stieltjesIntegral.integral_symm, intervalIntegral.integral_symm,
    stieltjesIntegral_eq_intervalIntegral_of_contDiffOn' B hba hg hf]

/-- Special case of previous when `g x = x`. -/
theorem stieltjesIntegral_eq_intervalIntegral_of_riemannIntegrable
{f : ℝ → E} {a b : ℝ} (hf : RiemannIntegrable (min a b) (max a b) f) :
  ∫⟨(lsmul ℝ ℝ).flip⟩ x in a..b, f x ∂id = ∫ x in a..b, f x := by
  convert stieltjesIntegral_eq_intervalIntegral_of_contDiffOn _
    (ContDiff.contDiffOn contDiff_id) hf using 3 with x
  simp

/-! ### Sums as Stieltjes integrals -/

/-- Relate sums ∑ f(n) with Stieltjes integrals ∫ f ∂⌊x⌋ -/
theorem sum_eq_integral_nat_floor {a b : ℝ} (hab : a < b) (f : ℝ → E) :
    HasStieltjesIntegral a b (lsmul ℝ ℝ).flip f
      (fun x ↦ ⌊x⌋₊)
      (∑ n ∈ Finset.Ico ⌈a⌉₊ ⌈b⌉₊, f n) := by sorry

theorem sum_eq_integral_int_floor {a b : ℝ} (hab : a < b) (f : ℝ → E) :
    HasStieltjesIntegral a b (lsmul ℝ ℝ).flip f
      (fun x ↦ ⌊x⌋)
      (∑ n ∈ Finset.Ico ⌈a⌉ ⌈b⌉, f n) := by sorry

/-- Sum of pairings `B (f n) (g n)` over natural `n ∈ (⌊a⌋, ⌊b⌋]`, expressed as a Stieltjes
integral of `f` against the right-continuous summatory `x ↦ ∑ n ≤ x, g n`. -/
theorem sum_eq_integral_natSummatory_le {a b : ℝ} (hab : a < b) (f : ℝ → E) (g : ℕ → F) :
    HasStieltjesIntegral a b B f
      (fun x ↦ ∑ n ∈ Finset.Iic ⌊x⌋₊, g n)
      (∑ n ∈ Finset.Ioc ⌊a⌋₊ ⌊b⌋₊, B (f n) (g n)) := by sorry

/-- Sum of pairings `B (f n) (g n)` over natural `n ∈ [⌈a⌉, ⌈b⌉)`, expressed as a Stieltjes
integral of `f` against the left-continuous summatory `x ↦ ∑ n < x, g n`. -/
theorem sum_eq_integral_natSummatory_lt {a b : ℝ} (hab : a < b) (f : ℝ → E) (g : ℕ → F) :
    HasStieltjesIntegral a b B f
      (fun x ↦ ∑ n ∈ Finset.Iio ⌈x⌉₊, g n)
      (∑ n ∈ Finset.Ico ⌈a⌉₊ ⌈b⌉₊, B (f n) (g n)) := by sorry

end BoxIntegral
