/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

Authors: Steven Creech, Jaume de Dios, Bogdan Georgiev, Harald Helfgott, Ayush Khaitan, Terence Tao

Thanks to ICERM for hosting the workshop "Formalization of Analysis" where most of this work
was conducted.
-/
module

public import Mathlib.Analysis.BoxIntegral.Stieltjes.Defs
public import Mathlib.Analysis.BoxIntegral.Partition.OrderedDivision
public import Mathlib.Topology.EMetricSpace.BoundedVariation
public import Mathlib.MeasureTheory.Integral.IntervalIntegral.Basic
public import Mathlib.Analysis.Calculus.ContDiff.Basic
public import Mathlib.MeasureTheory.Integral.IntervalIntegral.ContDiff
public import Mathlib.Analysis.Calculus.ContDiff.Defs
public import Mathlib.Analysis.Calculus.ContDiff.Deriv
public import Mathlib.Analysis.Calculus.Deriv.Linear
public import Mathlib.Analysis.Calculus.Deriv.Mul


set_option linter.style.longFile 2700

/-! # Riemann–Stieltjes integral

In this file we establish fundamental properties of Riemann–Stieltjes integral
`∫⟨B⟩ x in a..b, f x ∂g` defined in `Analysis.BoxIntegral.Stieltjes.Defs`.

## Main theorems

* `BoxIntegral.Stieltjes.hasStieltjesIntegral_iff_lim_sum`: gives the textbook ε-δ characterization
of the Riemann--Stieltjes integral.
* `BoxIntegral.stieltjesIntegral.add_adjacent`: gives the splitting identity
  `∫⟨B⟩ x in a..c, f x ∂g = ∫⟨B⟩ x in a..b, f x ∂g + ∫⟨B⟩ x in b..c, f x ∂g`, regardless of
  the ordering of `a`, `b`, `c`.
* `BoxIntegral.exists_of_continuousOn_of_boundedVariationOn` (Theorem A.1): if `f` is continuous
  and `g` has bounded variation on `[a, b]`, then the Riemann–Stieltjes integral exists.
* `BoxIntegral.stieltjesIntegral.by_parts` (Theorem A.2): if `∫⟨B⟩ x in a..b, f x ∂g` exists, then
  so does `∫⟨B⟩ x in a..b, g x ∂f`, and the two are related by the integration by parts identity
  `∫⟨B⟩ x in a..b, g x ∂f = B (f b) (g b) - B (f a) (g a) - ∫⟨B⟩ x in a..b, f x ∂g`.
* `BoxIntegral.variation_of_derivative` (Theorem A.3(a)) and
  `BoxIntegral.integral_of_derivative` (Theorem A.3(b)): when `g` is `C¹`, the total variation
  and the Riemann–Stieltjes integral can be computed by `g′`.
* `BoxIntegral.integral_le_integral_of_variation` (Theorem A.4): a norm bound on the integral
  in terms of the variation of `g`.
* `BoxIntegral.stieltjesIntegral_eq_intervalIntegral_of_riemannIntegrable`: the Riemann-Stieltjes
integral `∫⟨lsmul ℝ ℝ⟩ x in a..b, f x ∂id` agrees with the interval integral
`∫ x in a..b, f x` when `f` is Riemann integrable.
* `BoxIntegral.stieltjesIntegral_of_fun_floor_right`: `∫⟨B⟩ x in a..b, f x ∂(g ⌊·⌋)` is equal to
`∑ n in Finset.Ioc ⌊a⌋ ⌊b⌋, B (f n) (g n - g (n - 1))` when `f` is continuous.  Similarly with
the `⌊·⌋₊` function.

## AI usage

* Much of the boilerplate API and docstrings was generated by AI, which was prompted to follow
existing Mathlib examples and style guides.

* More mathematically complex theorems were largely proved by hand.

## References

* H. L. Montgomery and R. C. Vaughan, *Multiplicative Number Theory I: Classical Theory*,
  Cambridge Studies in Advanced Mathematics 97, Cambridge University Press, 2007 (Appendix A).

## TODO

* Develop a higher-dimensional Stieltjes integral (exists in the literature, but is rarely used)
* Develop a Stieltjes integral based around `Ico` intervals rather than `Ioc` intervals
* Other variants of Stieltjes integration, such as the Henstock-Stieltjes integral
* Interpretation of `ofDiff` as a measure (assuming monotonicity)
* Interpretation of `ofDiff` as a signed measure (assuming bounded variation).  This requires
the development of signed measures in Mathlib

## Tags

Stieltjes integral, Riemann–Stieltjes, bounded variation
-/

@[expose] public section


-- Helper lemmas

/-- Move to Mathlib.Algebra.Order.Floor.Defs -/
lemma Int.coe_mem_Ioc_iff {α : Type*} [Ring α] [LinearOrder α] [FloorRing α] {n : ℤ} {a b : α}
    : ↑n ∈ Set.Ioc a b ↔ n ∈ Finset.Ioc ⌊a⌋ ⌊b⌋  := by
  simp [Int.floor_lt, Int.le_floor]

/-- move somewhere? -/
lemma ContinuousOn.metric_uniform {E : Type*} [NormedAddCommGroup E] {a b : ℝ} {f : ℝ → E}
  (hf : ContinuousOn f (Set.Icc a b)) (ε : ℝ) (hε : ε > 0) :
  ∃ δ > 0, ∀ x ∈ Set.Icc a b, ∀ y ∈ Set.Icc a b, |x - y| < δ → ‖f x - f y‖ < ε := by
  simpa [dist_eq_norm] using Metric.uniformContinuousOn_iff.mp
    (isCompact_Icc.uniformContinuousOn_of_continuous hf) ε hε

open BoxIntegral
open ContinuousLinearMap TaggedPrepartition intervalIntegral Metric
open Prepartition hiding mem_mk
open Finset hiding Ioc mem_mk
open Fin hiding zero_lt_one

namespace BoxIntegral

/-! ## Epsilon-delta definition of the Stieltjes integral -/

variable {E : Type*} {F : Type*} {G : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
  [NormedAddCommGroup F] [NormedSpace ℝ F] [NormedAddCommGroup G] [NormedSpace ℝ G]
variable (a b : ℝ) (B : E →L[ℝ] F →L[ℝ] G)

/-- The predicate `HasStieltjesIntegral` matches the usual epsilon-delta definition, at least if
one uses unordered partitions of the interval. -/
theorem hasStieltjesIntegral_iff_lim_sum {a b : ℝ} (hab : a < b) (f : ℝ → E) (g : ℝ → F) (L : G) :
    HasStieltjesIntegral a b B f g L ↔
    ∀ ε > 0, ∃ δ > 0, ∀ π : TaggedPrepartition (Ioc a b), π.IsHenstock → π.IsPartition
    → π.mesh_size ≤ δ →
     dist (∑ x ∈ π.boxes, ((B (f (π.tag x 0))) (g (x.upper 0) - g (x.lower 0)))) L < ε := by
  simp [HasStieltjesIntegral.of_lt, hab, HasStieltjesIntegral',
    HasIntegral_Riemann_iff, integralSum]

theorem hasRiemannIntegral_iff_lim_sum {a b : ℝ} (hab : a < b) (f : ℝ → E) (L : E) :
    HasRiemannIntegral a b f L ↔
    ∀ ε > 0, ∃ δ > 0, ∀ π : TaggedPrepartition (Ioc a b), π.IsHenstock → π.IsPartition
    → π.mesh_size ≤ δ →
     dist (∑ x ∈ π.boxes, ((x.upper 0) - (x.lower 0)) • (f (π.tag x 0))) L < ε :=
  hasStieltjesIntegral_iff_lim_sum _ hab _ _ _

/-- A Riemann integrable function on a closed interval is bounded. -/
theorem RiemannIntegrable.bounded (hab : a < b) {f : ℝ → E} (h : RiemannIntegrable a b f) :
    Bornology.IsBounded (f '' (.Ioc a b)) := by
  rw [RiemannIntegrable.def] at h
  obtain ⟨ L, hL ⟩ := h
  rw [hasRiemannIntegral_iff_lim_sum hab] at hL
  obtain ⟨ δ, hδ, h ⟩ := hL 1 (by norm_num)
  let N := ⌈(b - a) / δ⌉₊
  have hN : N > 0 := by positivity
  have hab' : 0 < b - a := by positivity
  let z : ℕ → ℝ := (a + (b - a) * · / N)
  have z0 : z 0 = a := by simp [z]
  have zN : z N = b := by simp [z]; field_simp; abel
  have zdiff (n : ℕ) : z (n + 1) = z n + (b - a) / N := by simp [z]; grind
  have zmono (n : ℕ) : z n < z (n + 1) := by simp only [zdiff, lt_add_iff_pos_right]; positivity
  have zmono' : Monotone z := by intro i j hij; unfold z; grw [hij]
  let box : ℕ → Box (Fin 1) := fun n ↦ Ioc (z n) (z (n + 1))
  have box_upper (i : ℕ) : (box i).upper 0 = z (i + 1) := by simp [box, Ioc.upper (zmono i)]
  have box_lower (i : ℕ) : (box i).lower 0 = z i := by simp [box, Ioc.lower (zmono i)]
  have box_le {i : ℕ} (hi : i < N) : box i ≤ Ioc a b := by
    simp only [hab, zmono i, Ioc_le_Ioc_iff, box]
    simp only [← z0, ← zN]
    exact ⟨ zmono' (by lia), zmono' (by lia) ⟩
  rw [isBounded_iff_forall_norm_le]
  let F : ℕ → NNReal := fun n ↦ ‖f (z n)‖₊
  refine ⟨ (range (N + 1)).sup F + 2 * N / (b - a), fun y hy ↦ ?_ ⟩
  simp only [Set.mem_image, Set.mem_Ioc] at hy; obtain ⟨ x, ⟨ hx, hx' ⟩, rfl ⟩ := hy
  let i : ℝ → ℕ := fun x ↦ ⌈N * (x - a) / (b - a)⌉₊
  have hipos {x : ℝ} (hx : a < x) : 0 < i x := by positivity
  have hi {x : ℝ} (hx' : x ≤ b) : i x ≤ N := by simp [i]; field_simp; linarith
  have hi_sub {x : ℝ} (hx : a < x) : i x - 1 + 1 = i x := by have := hipos hx; lia
  classical
  let π : Bool → TaggedPrepartition (Ioc a b) := fun p ↦ {
    boxes := (range N).image box
    le_of_mem' J hJ := by
      simp only [mem_image, mem_range] at hJ; obtain ⟨ j, hj, rfl ⟩ := hJ
      exact box_le hj
    pairwiseDisjoint I hI J hJ hdisj := by
      simp only [coe_image, coe_range, Set.mem_image, Set.mem_Iio] at hI hJ
      obtain ⟨ i, hi, rfl ⟩ := hI
      obtain ⟨ j, hj, rfl ⟩ := hJ
      simp only [Function.onFun, Box.disjoint_iff, isValue, box_upper, box_lower]
      rcases lt_trichotomy i j with hlt | rfl | hgt
      · left; exact zmono' (by lia)
      · simp at hdisj
      right; exact zmono' (by lia)
    tag J := if p ∧ J = box (i x - 1) then (fun _ ↦ x) else
      if J ∈ (range N).image box then J.upper else (Ioc a b).upper
    tag_mem_Icc J := by
      split_ifs with h h'
      · simp [Box.Icc_def, Pi.le_def, hab, hx.le, hx']
      · simp only [mem_image, mem_range] at h'; obtain ⟨ j, hj, rfl ⟩ := h'
        exact (Box.le_iff_Icc.mp (box_le hj)) (Box.upper_mem_Icc _)
      apply Box.upper_mem_Icc
  }
  have hmem {x : ℝ} (hx : a < x) (hx' : x ≤ b) : (fun _ ↦ x) ∈ box (i x - 1) := by
    simp only [zmono (i x - 1), box, mem_Ioc]
    simp only [hi_sub hx, z, i]
    constructor
    · calc
        _ < a + (b - a) * (↑N * (x - a) / (b - a)) / ↑N := by
          gcongr; grw [← add_lt_add_iff_right 1]
          convert Nat.ceil_lt_add_one ?_ <;> try infer_instance
          · rw [←Nat.cast_add_one, Nat.sub_one_add_one]
            positivity
          positivity
        _ ≤ _ := by field_simp; linarith
    grw [← Nat.le_ceil]
    field_simp; linarith
  have hhen (p : Bool) : (π p).IsHenstock := by
    intro J hJ
    simp only [mem_image, mem_range, π]; split_ifs with h h'
    · rw [h.2]
      exact Box.coe_subset_Icc (hmem hx hx')
    · obtain ⟨ j, hj, rfl ⟩ := h'
      apply Box.upper_mem_Icc
    simp [π] at hJ; tauto
  have hpart (p : Bool) : (π p).IsPartition := by
    intro x hx; simp only [hab, mem_Ioc, isValue] at hx
    refine ⟨ box (i (x 0) - 1), ?_, by convert hmem hx.1 hx.2 ⟩
    simp only [isValue, Prepartition.mem_mk, mem_image, mem_range, π]
    exact ⟨ i (x 0) - 1, by have := hi hx.2; grind, by rfl ⟩
  have hmesh (p : Bool) : (π p).mesh_size ≤ δ := by
    simp only [mesh_size_le_iff, mem_boxes, mem_toPrepartition, tsub_le_iff_right,
      forall_fin_one, isValue]
    intro J hJ; simp only [mem_image, mem_range, mem_mk, Prepartition.mem_mk, π] at hJ
    obtain ⟨ i, hi, rfl ⟩ := hJ
    simp only [isValue, box_upper, zdiff, box_lower, N]
    nth_rw 1 [add_comm]; gcongr; field_simp; grw [← Nat.le_ceil]; field_simp; norm_num
  specialize hi hx'
  specialize hipos hx
  specialize hi_sub hx
  have : ‖((box (i x - 1)).upper 0 - (box (i x - 1)).lower 0) • (f x - f ((box (i x - 1)).upper 0))‖
    ≤ 2 := calc
    _ = dist (∑ x ∈ (π true).boxes, (x.upper 0 - x.lower 0) • f ((π true).tag x 0))
      (∑ x ∈ (π false).boxes, (x.upper 0 - x.lower 0) • f ((π false).tag x 0)) := by
        simp only [isValue, true_and, Bool.false_eq_true, false_and, ↓reduceIte, dist_eq_norm,
          ← sum_sub_distrib, π]
        congr; symm
        convert sum_eq_single (box (i x - 1)) ?_ ?_ using 1
        · have : ∃ a < N, box a = box (i x - 1) := ⟨ i x - 1, by lia, rfl ⟩
          simp [← smul_sub, this]
        · intro I hI hIi; simp only [mem_image, mem_range] at hI
          obtain ⟨ j, hj, rfl ⟩ := hI
          simp [hIi]
        simp only [mem_image, mem_range, not_exists, not_and, isValue, ↓reduceIte]
        intro h; simpa using h (i x - 1) (by lia)
    _ ≤ 2 := by
      grw [dist_triangle_right _ _ L, h (π true) (hhen true) (hpart true) (hmesh true),
        h (π false) (hhen false) (hpart false) (hmesh false)]
      norm_num
  have h : ((box (i x - 1)).upper 0 - (box (i x - 1)).lower 0) = (b - a) / N := by
    simp [box_upper, box_lower, zdiff]
  simp only [isValue, h, norm_smul, norm_div, Real.norm_eq_abs, RCLike.norm_natCast] at this
  grw [← this, box_upper]
  have : ‖f (z (i x))‖₊ ≤ (range (N + 1)).sup F := le_sup (f := F) (b := i x) (by simp [hi])
  rw [← NNReal.coe_le_coe] at this; grw [← this]
  simp [hi_sub, abs_of_pos hab']; field_simp; apply norm_le_insert'

section Naturality

/-! ## Naturality: transporting along continuous linear maps -/

variable {E' F' G' : Type*} [NormedAddCommGroup E'] [NormedSpace ℝ E']
    [NormedAddCommGroup F'] [NormedSpace ℝ F'] [NormedAddCommGroup G'] [NormedSpace ℝ G']
    {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G} {f : ℝ → E} {g : ℝ → F} {L : G} {M : E}
    {φ : E →L[ℝ] E'} {ψ : F →L[ℝ] F'} {Ψ : G →L[ℝ] G'}
    {B' : E' →L[ℝ] F' →L[ℝ] G'}

private theorem HasStieltjesIntegral'.map (hB : ∀ e y, Ψ (B e y) = B' (φ e) (ψ y))
    (h : HasStieltjesIntegral' a b B f g L) :
    HasStieltjesIntegral' a b B' (φ ∘ f) (ψ ∘ g) (Ψ L) :=
  HasIntegral.map φ Ψ (fun _ _ ↦ by simp [hB]) h

/-- If a bilinear pairing `B : E →L[ℝ] F →L[ℝ] G` and CLMs `φ : E →L[ℝ] E'`, `ψ : F →L[ℝ] F'`,
`Ψ : G →L[ℝ] G'` satisfy the compatibility `Ψ (B e y) = B' (φ e) (ψ y)` for all `e, y`, then
`HasStieltjesIntegral` transports along `(φ, ψ, Ψ)`: applying `φ` to the integrand, `ψ` to the
integrator and `Ψ` to the integral preserves the Stieltjes-integral relation. -/
theorem HasStieltjesIntegral.map (hB : ∀ e y, Ψ (B e y) = B' (φ e) (ψ y))
    (h : HasStieltjesIntegral a b B f g L) :
    HasStieltjesIntegral a b B' (φ ∘ f) (ψ ∘ g) (Ψ L) := by
  rcases lt_trichotomy a b with hab | rfl | hab
  · simp only [of_lt, hab] at h ⊢
    exact h.map hB
  · simp_all
  rw [symm_iff] at h ⊢
  simp only [hab, of_lt] at h ⊢
  convert h.map hB using 1
  simp

theorem HasRiemannIntegral.map (h : HasRiemannIntegral a b f M) :
    HasRiemannIntegral a b (φ ∘ f) (φ M) := by
  convert HasStieltjesIntegral.map (ψ := .id ℝ ℝ) ?_ h
  simp

theorem StieltjesIntegrable.map (hB : ∀ e y, Ψ (B e y) = B' (φ e) (ψ y))
    (h : StieltjesIntegrable a b B f g) :
    StieltjesIntegrable a b B' (φ ∘ f) (ψ ∘ g) :=
  (h.hasStieltjesIntegral.map hB).stieltjesIntegrable

theorem RiemannIntegrable.map (h : RiemannIntegrable a b f) :
    RiemannIntegrable a b (φ ∘ f) := by
  convert StieltjesIntegrable.map (ψ := .id ℝ ℝ) (Ψ := φ) ?_ h
  simp

theorem stieltjesIntegral_map (hB : ∀ e y, Ψ (B e y) = B' (φ e) (ψ y))
    (h : StieltjesIntegrable a b B f g) :
    ∫⟨B'⟩ x in a..b, φ (f x) ∂(ψ ∘ g) =
      Ψ (∫⟨B⟩ x in a..b, f x ∂g) :=
  (h.hasStieltjesIntegral.map hB).stieltjesIntegral_eq

end Naturality

section Linearity

/-! ## Linearity

The API provided here demonstrates that the Riemann--Stieltjes integral `∫⟨B⟩ x in a..b, f x ∂g` is
linear in each of the inputs `f`, `g`, `B`.
-/

variable {a b : ℝ} {B B₁ B₂ : E →L[ℝ] F →L[ℝ] G} {f f₁ f₂ : ℝ → E} {g g₁ g₂ : ℝ → F} {L L₁ L₂ : G}
    {M M₁ M₂ : E} {ι : Type*} {s : Finset ι}

/-! ### In the integrand -/

private theorem HasStieltjesIntegral'.zero_left : HasStieltjesIntegral' a b B 0 g 0 :=
  hasIntegral_zero

@[simp]
theorem HasStieltjesIntegral.zero_left : HasStieltjesIntegral a b B 0 g 0 := by
  rcases lt_trichotomy a b with h | rfl | h
  · simp only [of_lt, h, HasStieltjesIntegral'.zero_left]
  · simp
  rw [symm_iff]
  simp only [neg_zero, h, of_lt, HasStieltjesIntegral'.zero_left]

@[simp]
theorem HasRiemannIntegral.zero : HasRiemannIntegral a b (0 : ℝ  → E) 0 :=
  HasStieltjesIntegral.zero_left

@[simp]
theorem StieltjesIntegrable.zero_left : StieltjesIntegrable a b B 0 g :=
  HasStieltjesIntegral.zero_left.stieltjesIntegrable

@[simp]
theorem RiemannIntegrable.zero : RiemannIntegrable a b (0 : ℝ  → E) :=
  HasRiemannIntegral.zero.stieltjesIntegrable

@[simp]
theorem stieltjesIntegral_zero_left : ∫⟨B⟩ _ in a..b, 0 ∂g = 0 :=
  HasStieltjesIntegral.zero_left.stieltjesIntegral_eq

private theorem HasStieltjesIntegral'.add_left
    (h₁ : HasStieltjesIntegral' a b B f₁ g L₁) (h₂ : HasStieltjesIntegral' a b B f₂ g L₂) :
    HasStieltjesIntegral' a b B (f₁ + f₂) g (L₁ + L₂) :=
  HasIntegral.add h₁ h₂

theorem HasStieltjesIntegral.add_left
    (h₁ : HasStieltjesIntegral a b B f₁ g L₁) (h₂ : HasStieltjesIntegral a b B f₂ g L₂) :
    HasStieltjesIntegral a b B (f₁ + f₂) g (L₁ + L₂) := by
  rcases lt_trichotomy a b with h | rfl | h
  · simp only [of_lt, h] at h₁ h₂ ⊢
    exact h₁.add_left h₂
  · simp_all
  rw [symm_iff] at h₁ h₂ ⊢
  simp only [h, of_lt, neg_add] at h₁ h₂ ⊢
  exact h₁.add_left h₂

theorem HasRiemannIntegral.add
    (h₁ : HasRiemannIntegral a b f₁ M₁) (h₂ : HasRiemannIntegral a b f₂ M₂) :
    HasRiemannIntegral a b (f₁ + f₂) (M₁ + M₂) := HasStieltjesIntegral.add_left h₁ h₂

theorem StieltjesIntegrable.add_left
    (h₁ : StieltjesIntegrable a b B f₁ g) (h₂ : StieltjesIntegrable a b B f₂ g) :
    StieltjesIntegrable a b B (f₁ + f₂) g :=
  (h₁.hasStieltjesIntegral.add_left h₂.hasStieltjesIntegral).stieltjesIntegrable

theorem RiemannIntegrable.add
    (h₁ : RiemannIntegrable a b f₁) (h₂ : RiemannIntegrable a b f₂) :
    RiemannIntegrable a b (f₁ + f₂) := StieltjesIntegrable.add_left h₁ h₂

@[simp]
theorem stieltjesIntegral_add_left
    (h₁ : StieltjesIntegrable a b B f₁ g) (h₂ : StieltjesIntegrable a b B f₂ g) :
    ∫⟨B⟩ x in a..b, (f₁ + f₂) x ∂g
      = ∫⟨B⟩ x in a..b, f₁ x ∂g + ∫⟨B⟩ x in a..b, f₂ x ∂g :=
    (h₁.hasStieltjesIntegral.add_left h₂.hasStieltjesIntegral).stieltjesIntegral_eq

private theorem HasStieltjesIntegral'.smul_left (h : HasStieltjesIntegral' a b B f g L) (c : ℝ) :
    HasStieltjesIntegral' a b B (c • f) g (c • L) :=
  HasIntegral.smul h c

theorem HasStieltjesIntegral.smul_left (h : HasStieltjesIntegral a b B f g L) (c : ℝ) :
    HasStieltjesIntegral a b B (c • f) g (c • L) := by
  rcases lt_trichotomy a b with hab | rfl | hab
  · simp only [of_lt, hab] at h ⊢
    apply h.smul_left
  · simp_all
  rw [symm_iff] at h ⊢
  simp only [hab, of_lt] at h ⊢
  convert h.smul_left _ using 1
  norm_num

theorem HasRiemannIntegral.smul (h : HasRiemannIntegral a b f M) (c : ℝ) :
    HasRiemannIntegral a b (c • f) (c • M) :=
  HasStieltjesIntegral.smul_left h c

theorem StieltjesIntegrable.smul_left
    (h : StieltjesIntegrable a b B f g) (c : ℝ) : StieltjesIntegrable a b B (c • f) g :=
  (h.hasStieltjesIntegral.smul_left c).stieltjesIntegrable

theorem RiemannIntegrable.smul
    (h : RiemannIntegrable a b f) (c : ℝ) : RiemannIntegrable a b (c • f) :=
  StieltjesIntegrable.smul_left h c

@[simp]
theorem stieltjesIntegral_smul_left
    (h : StieltjesIntegrable a b B f g) (c : ℝ) :
    ∫⟨B⟩ x in a..b, (c • f) x ∂g = c • ∫⟨B⟩ x in a..b, f x ∂g :=
  (h.hasStieltjesIntegral.smul_left c).stieltjesIntegral_eq

theorem HasStieltjesIntegral.neg_left (h : HasStieltjesIntegral a b B f g L) :
    HasStieltjesIntegral a b B (-f) g (-L) := by
  convert h.smul_left (-1) using 1 <;> simp

theorem HasRiemannIntegral.neg (h : HasRiemannIntegral a b f M) :
  HasRiemannIntegral a b (-f) (-M) :=
  HasStieltjesIntegral.neg_left h

theorem StieltjesIntegrable.neg_left
  (h : StieltjesIntegrable a b B f g) : StieltjesIntegrable a b B (-f) g :=
  h.hasStieltjesIntegral.neg_left.stieltjesIntegrable

theorem RiemannIntegrable.neg
  (h : RiemannIntegrable a b f) : RiemannIntegrable a b (-f) :=
  StieltjesIntegrable.neg_left h

@[simp]
theorem stieltjesIntegral_neg_left (h : StieltjesIntegrable a b B f g) :
    ∫⟨B⟩ x in a..b, (-f) x ∂g = -∫⟨B⟩ x in a..b, f x ∂g :=
  h.hasStieltjesIntegral.neg_left.stieltjesIntegral_eq

theorem HasStieltjesIntegral.sub_left
    (h₁ : HasStieltjesIntegral a b B f₁ g L₁) (h₂ : HasStieltjesIntegral a b B f₂ g L₂) :
    HasStieltjesIntegral a b B (f₁ - f₂) g (L₁ - L₂) := by
  convert h₁.add_left (h₂.neg_left) using 1 <;> abel

theorem HasRiemannIntegral.sub
    (h₁ : HasRiemannIntegral a b f₁ M₁) (h₂ : HasRiemannIntegral a b f₂ M₂) :
    HasRiemannIntegral a b (f₁ - f₂) (M₁ - M₂) :=
  HasStieltjesIntegral.sub_left h₁ h₂

theorem StieltjesIntegrable.sub_left
    (h₁ : StieltjesIntegrable a b B f₁ g) (h₂ : StieltjesIntegrable a b B f₂ g) :
    StieltjesIntegrable a b B (f₁ - f₂) g :=
  (h₁.hasStieltjesIntegral.sub_left h₂.hasStieltjesIntegral).stieltjesIntegrable

theorem RiemannIntegrable.sub
    (h₁ : RiemannIntegrable a b f₁) (h₂ : RiemannIntegrable a b f₂) :
    RiemannIntegrable a b (f₁ - f₂) := StieltjesIntegrable.sub_left h₁ h₂

@[simp]
theorem stieltjesIntegral_sub_left
    (h₁ : StieltjesIntegrable a b B f₁ g) (h₂ : StieltjesIntegrable a b B f₂ g) :
    ∫⟨B⟩ x in a..b, (f₁ - f₂) x ∂g
      = ∫⟨B⟩ x in a..b, f₁ x ∂g - ∫⟨B⟩ x in a..b, f₂ x ∂g :=
  (h₁.hasStieltjesIntegral.sub_left h₂.hasStieltjesIntegral).stieltjesIntegral_eq

theorem HasStieltjesIntegral.finset_sum_left {f : ι → ℝ → E} {L : ι → G}
    (h : ∀ i ∈ s, HasStieltjesIntegral a b B (f i) g (L i)) :
    HasStieltjesIntegral a b B (∑ i ∈ s, f i) g (∑ i ∈ s, L i) := by
  classical
  revert h
  refine Finset.induction_on s ?_ ?_
  · simp
  intro j s hjs hind h
  specialize hind (by aesop)
  specialize h j (by aesop)
  simp only [hjs, not_false_eq_true, sum_insert]
  exact h.add_left hind

theorem HasRiemannIntegral.finset_sum {f : ι → ℝ → E} {L : ι → E}
    (h : ∀ i ∈ s, HasRiemannIntegral a b (f i) (L i)) :
    HasRiemannIntegral a b (∑ i ∈ s, f i) (∑ i ∈ s, L i) :=
  HasStieltjesIntegral.finset_sum_left h

theorem StieltjesIntegrable.finset_sum_left {f : ι → ℝ → E}
    (h : ∀ i ∈ s, StieltjesIntegrable a b B (f i) g) :
    StieltjesIntegrable a b B (∑ i ∈ s, f i) g :=
  (HasStieltjesIntegral.finset_sum_left
    (fun i hi ↦ (h i hi).hasStieltjesIntegral)).stieltjesIntegrable

theorem RiemannIntegrable.finset_sum {f : ι → ℝ → E}
    (h : ∀ i ∈ s, RiemannIntegrable a b (f i)) :
    RiemannIntegrable a b (∑ i ∈ s, f i) := StieltjesIntegrable.finset_sum_left h

@[simp]
theorem stieltjesIntegral_finset_sum_left {f : ι → ℝ → E}
    (h : ∀ i ∈ s, StieltjesIntegrable a b B (f i) g) :
    ∫⟨B⟩ x in a..b, (∑ i ∈ s, f i) x ∂g = ∑ i ∈ s, ∫⟨B⟩ x in a..b, f i x ∂g :=
  (HasStieltjesIntegral.finset_sum_left
    (fun i hi ↦ (h i hi).hasStieltjesIntegral)).stieltjesIntegral_eq

/-! ### In the integrator -/

private theorem HasStieltjesIntegral'.const_right (c : F) :
    HasStieltjesIntegral' a b B f (fun _ ↦ c) 0 := by
  simp only [HasStieltjesIntegral', isValue, BoxAdditiveMap.ofDiff_const, hasIntegral_zero_vol]

@[simp]
theorem HasStieltjesIntegral.const_right (c : F) :
    HasStieltjesIntegral a b B f (fun _ ↦ c) 0 := by
  rcases lt_trichotomy a b with hab | rfl | hab
  · simp only [of_lt, hab] at ⊢
    apply HasStieltjesIntegral'.const_right
  · simp_all
  rw [symm_iff] at ⊢
  simp only [neg_zero, hab, of_lt] at ⊢
  apply HasStieltjesIntegral'.const_right

@[simp]
theorem HasStieltjesIntegral.zero_right : HasStieltjesIntegral a b B f 0 0 :=
  const_right 0

@[simp]
theorem StieltjesIntegrable.const_right (c : F) :
    StieltjesIntegrable a b B f (fun _ ↦ c) :=
  (HasStieltjesIntegral.const_right c).stieltjesIntegrable

@[simp]
theorem StieltjesIntegrable.zero_right : StieltjesIntegrable a b B f 0 :=
  const_right 0

@[simp]
theorem stieltjesIntegral_const_right (c : F) : ∫⟨B⟩ x in a..b, f x ∂(fun _ ↦ c) = 0 :=
  (HasStieltjesIntegral.const_right c).stieltjesIntegral_eq

@[simp]
theorem stieltjesIntegral_zero_right : ∫⟨B⟩ x in a..b, f x ∂0 = 0 :=
  stieltjesIntegral_const_right 0

private theorem HasStieltjesIntegral'.add_right
    (h₁ : HasStieltjesIntegral' a b B f g₁ L₁) (h₂ : HasStieltjesIntegral' a b B f g₂ L₂) :
    HasStieltjesIntegral' a b B f (g₁ + g₂) (L₁ + L₂) := by
  unfold HasStieltjesIntegral' at h₁ h₂ ⊢
  have h : (B.flip <| (g₁ + g₂) ·) = (B.flip <| g₁ ·) + (B.flip <| g₂ ·) := by ext; simp
  rw [h, map_add]
  exact h₁.add_vol h₂

theorem HasStieltjesIntegral.add_right
    (h₁ : HasStieltjesIntegral a b B f g₁ L₁) (h₂ : HasStieltjesIntegral a b B f g₂ L₂) :
    HasStieltjesIntegral a b B f (g₁ + g₂) (L₁ + L₂) := by
  rcases lt_trichotomy a b with hab | rfl | hab
  · simp only [of_lt, hab] at h₁ h₂ ⊢
    exact h₁.add_right h₂
  · simp_all
  rw [symm_iff] at h₁ h₂ ⊢
  simp only [hab, of_lt] at h₁ h₂ ⊢
  convert h₁.add_right h₂ using 1
  abel

theorem StieltjesIntegrable.add_right
    (h₁ : StieltjesIntegrable a b B f g₁) (h₂ : StieltjesIntegrable a b B f g₂) :
    StieltjesIntegrable a b B f (g₁ + g₂) :=
  (h₁.hasStieltjesIntegral.add_right h₂.hasStieltjesIntegral).stieltjesIntegrable

@[simp]
theorem stieltjesIntegral_add_right
    (h₁ : StieltjesIntegrable a b B f g₁) (h₂ : StieltjesIntegrable a b B f g₂) :
    ∫⟨B⟩ x in a..b, f x ∂(g₁ + g₂)
      = ∫⟨B⟩ x in a..b, f x ∂g₁ + ∫⟨B⟩ x in a..b, f x ∂g₂ :=
    (h₁.hasStieltjesIntegral.add_right h₂.hasStieltjesIntegral).stieltjesIntegral_eq

private theorem HasStieltjesIntegral'.smul_right (h : HasStieltjesIntegral' a b B f g L) (c : ℝ) :
    HasStieltjesIntegral' a b B f (c • g) (c • L) := by
  unfold HasStieltjesIntegral' at h ⊢
  have heq : (B.flip <| (c • g) ·) = c • (B.flip <| g ·) := by ext; simp
  rw [heq, BoxIntegral.BoxAdditiveMap.ofDiff_smul]
  exact h.smul_vol c

theorem HasStieltjesIntegral.smul_right (h : HasStieltjesIntegral a b B f g L) (c : ℝ) :
    HasStieltjesIntegral a b B f (c • g) (c • L) := by
  rcases lt_trichotomy a b with hab | rfl | hab
  · simp only [of_lt, hab] at h ⊢
    apply h.smul_right
  · simp_all
  rw [symm_iff] at h ⊢
  simp only [hab, of_lt] at h ⊢
  convert h.smul_right _ using 1
  norm_num

theorem StieltjesIntegrable.smul_right (h : StieltjesIntegrable a b B f g) (c : ℝ) :
    StieltjesIntegrable a b B f (c • g) :=
  (h.hasStieltjesIntegral.smul_right c).stieltjesIntegrable

@[simp]
theorem stieltjesIntegral_smul_right
    (h : StieltjesIntegrable a b B f g) (c : ℝ) :
    ∫⟨B⟩ x in a..b, f x ∂(c • g) = c • ∫⟨B⟩ x in a..b, f x ∂g :=
  (h.hasStieltjesIntegral.smul_right c).stieltjesIntegral_eq


theorem HasStieltjesIntegral.neg_right (h : HasStieltjesIntegral a b B f g L) :
    HasStieltjesIntegral a b B f (-g) (-L) := by
  convert h.smul_right (-1) using 1 <;> simp

theorem StieltjesIntegrable.neg_right
    (h : StieltjesIntegrable a b B f g) : StieltjesIntegrable a b B f (-g) :=
  h.hasStieltjesIntegral.neg_right.stieltjesIntegrable

@[simp]
theorem stieltjesIntegral_neg_right
    (h : StieltjesIntegrable a b B f g) :
    ∫⟨B⟩ x in a..b, f x ∂(-g) = -∫⟨B⟩ x in a..b, f x ∂g :=
  h.hasStieltjesIntegral.neg_right.stieltjesIntegral_eq

theorem HasStieltjesIntegral.sub_right
    (h₁ : HasStieltjesIntegral a b B f g₁ L₁) (h₂ : HasStieltjesIntegral a b B f g₂ L₂) :
    HasStieltjesIntegral a b B f (g₁ - g₂) (L₁ - L₂) := by
  convert h₁.add_right (h₂.neg_right) using 1 <;> abel

theorem StieltjesIntegrable.sub_right
    (h₁ : StieltjesIntegrable a b B f g₁) (h₂ : StieltjesIntegrable a b B f g₂) :
    StieltjesIntegrable a b B f (g₁ - g₂) :=
  (h₁.hasStieltjesIntegral.sub_right h₂.hasStieltjesIntegral).stieltjesIntegrable

@[simp]
theorem stieltjesIntegral_sub_right
    (h₁ : StieltjesIntegrable a b B f g₁) (h₂ : StieltjesIntegrable a b B f g₂) :
    ∫⟨B⟩ x in a..b, f x ∂(g₁ - g₂)
      = ∫⟨B⟩ x in a..b, f x ∂g₁ - ∫⟨B⟩ x in a..b, f x ∂g₂ :=
  (h₁.hasStieltjesIntegral.sub_right h₂.hasStieltjesIntegral).stieltjesIntegral_eq

theorem HasStieltjesIntegral.finset_sum_right {g : ι → ℝ → F} {L : ι → G}
    (h : ∀ i ∈ s, HasStieltjesIntegral a b B f (g i) (L i)) :
    HasStieltjesIntegral a b B f (∑ i ∈ s, g i) (∑ i ∈ s, L i) := by
  classical
  revert h
  refine Finset.induction_on s ?_ ?_
  · simp
  intro j s hjs hind h
  specialize hind (by aesop)
  specialize h j (by aesop)
  simp only [hjs, not_false_eq_true, sum_insert]
  exact h.add_right hind

theorem StieltjesIntegrable.finset_sum_right {g : ι → ℝ → F}
    (h : ∀ i ∈ s, StieltjesIntegrable a b B f (g i)) :
    StieltjesIntegrable a b B f (∑ i ∈ s, g i) :=
  (HasStieltjesIntegral.finset_sum_right
    (fun i hi ↦ (h i hi).hasStieltjesIntegral)).stieltjesIntegrable

@[simp]
theorem stieltjesIntegral_finset_sum_right {g : ι → ℝ → F}
    (h : ∀ i ∈ s, StieltjesIntegrable a b B f (g i)) :
    ∫⟨B⟩ x in a..b, f x ∂(∑ i ∈ s, g i) = ∑ i ∈ s, ∫⟨B⟩ x in a..b, f x ∂(g i) :=
  (HasStieltjesIntegral.finset_sum_right
    (fun i hi ↦ (h i hi).hasStieltjesIntegral)).stieltjesIntegral_eq

/-! ### In the bilinear form -/

private theorem HasStieltjesIntegral'.zero_bil : HasStieltjesIntegral' a b 0 f g (0 : G) := by
  simp [HasStieltjesIntegral', hasIntegral_zero_vol]

@[simp]
theorem HasStieltjesIntegral.zero_bil : HasStieltjesIntegral a b 0 f g (0 : G) := by
  rcases lt_trichotomy a b with hab | rfl | hab
  · simp only [of_lt, hab] at ⊢
    apply HasStieltjesIntegral'.zero_bil
  · simp_all
  rw [symm_iff] at ⊢
  simp only [neg_zero, hab, of_lt] at ⊢
  apply HasStieltjesIntegral'.zero_bil

@[simp]
theorem StieltjesIntegrable.zero_bil : StieltjesIntegrable (G := G) a b 0 f g :=
  HasStieltjesIntegral.zero_bil.stieltjesIntegrable

@[simp]
theorem stieltjesIntegral_zero_bil : ∫⟨0⟩ x in a..b, f x ∂g = (0 : G) :=
  HasStieltjesIntegral.zero_bil.stieltjesIntegral_eq

private theorem HasStieltjesIntegral'.add_bil
    (h₁ : HasStieltjesIntegral' a b B₁ f g L₁) (h₂ : HasStieltjesIntegral' a b B₂ f g L₂) :
    HasStieltjesIntegral' a b (B₁ + B₂) f g (L₁ + L₂) := by
  unfold HasStieltjesIntegral' at h₁ h₂ ⊢
  have h : ((B₁ + B₂).flip <| g ·) = (B₁.flip <| g ·) + (B₂.flip <| g ·) := by ext; simp
  rw [h, map_add]
  exact h₁.add_vol h₂

@[simp]
theorem HasStieltjesIntegral.add_bil
    (h₁ : HasStieltjesIntegral a b B₁ f g L₁) (h₂ : HasStieltjesIntegral a b B₂ f g L₂) :
    HasStieltjesIntegral a b (B₁ + B₂) f g (L₁ + L₂) := by
  rcases lt_trichotomy a b with hab | rfl | hab
  · simp only [of_lt, hab] at h₁ h₂ ⊢
    exact h₁.add_bil h₂
  · simp_all
  rw [symm_iff] at h₁ h₂ ⊢
  simp only [hab, of_lt] at h₁ h₂ ⊢
  convert h₁.add_bil h₂ using 1
  abel

private theorem HasStieltjesIntegral'.smul_bil (h : HasStieltjesIntegral' a b B f g L) (c : ℝ) :
    HasStieltjesIntegral' a b (c • B) f g (c • L) := by
  unfold HasStieltjesIntegral' at h ⊢
  have heq : ((c • B).flip <| g ·) = c • (B.flip <| g ·) := by ext; simp
  rw [heq, BoxIntegral.BoxAdditiveMap.ofDiff_smul]
  exact h.smul_vol c

theorem HasStieltjesIntegral.smul_bil (h : HasStieltjesIntegral a b B f g L) (c : ℝ) :
    HasStieltjesIntegral a b (c • B) f g (c • L) := by
  rcases lt_trichotomy a b with hab | rfl | hab
  · simp only [of_lt, hab] at h ⊢
    apply h.smul_bil
  · simp_all
  rw [symm_iff] at h ⊢
  simp only [hab, of_lt] at h ⊢
  convert h.smul_bil _ using 1
  norm_num

theorem StieltjesIntegrable.smul_bil (h : StieltjesIntegrable a b B f g) (c : ℝ) :
    StieltjesIntegrable a b (c • B) f g :=
  (h.hasStieltjesIntegral.smul_bil c).stieltjesIntegrable

@[simp]
theorem stieltjesIntegral_smul_bil
    (h : StieltjesIntegrable a b B f g) (c : ℝ) :
    ∫⟨c • B⟩ x in a..b, f x ∂g = c • ∫⟨B⟩ x in a..b, f x ∂g :=
  (h.hasStieltjesIntegral.smul_bil c).stieltjesIntegral_eq

theorem HasStieltjesIntegral.neg_bil (h : HasStieltjesIntegral a b B f g L) :
    HasStieltjesIntegral a b (-B) f g (-L) := by
  convert h.smul_bil (-1) <;> ext <;> simp

@[simp]
theorem stieltjesIntegral_neg_bil
    (h : StieltjesIntegrable a b B f g) :
    ∫⟨-B⟩ x in a..b, f x ∂g = -∫⟨B⟩ x in a..b, f x ∂g :=
  h.hasStieltjesIntegral.neg_bil.stieltjesIntegral_eq

theorem HasStieltjesIntegral.sub_bil
    (h₁ : HasStieltjesIntegral a b B₁ f g L₁) (h₂ : HasStieltjesIntegral a b B₂ f g L₂) :
    HasStieltjesIntegral a b (B₁ - B₂) f g (L₁ - L₂) := by
  convert h₁.add_bil (h₂.neg_bil) using 1 <;> abel

theorem StieltjesIntegrable.sub_bil
    (h₁ : StieltjesIntegrable a b B₁ f g) (h₂ : StieltjesIntegrable a b B₂ f g) :
    StieltjesIntegrable a b (B₁ - B₂) f g :=
  (h₁.hasStieltjesIntegral.sub_bil h₂.hasStieltjesIntegral).stieltjesIntegrable

@[simp]
theorem stieltjesIntegral_sub_bil
    (h₁ : StieltjesIntegrable a b B₁ f g) (h₂ : StieltjesIntegrable a b B₂ f g) :
    ∫⟨B₁ - B₂⟩ x in a..b, f x ∂g
      = ∫⟨B₁⟩ x in a..b, f x ∂g - ∫⟨B₂⟩ x in a..b, f x ∂g :=
  (h₁.hasStieltjesIntegral.sub_bil h₂.hasStieltjesIntegral).stieltjesIntegral_eq

theorem HasStieltjesIntegral.finset_sum_bil {B : ι → E →L[ℝ] F →L[ℝ] G} {L : ι → G}
    (h : ∀ i ∈ s, HasStieltjesIntegral a b (B i) f g (L i)) :
    HasStieltjesIntegral a b (∑ i ∈ s, B i) f g (∑ i ∈ s, L i) := by
  classical
  revert h
  refine Finset.induction_on s ?_ ?_
  · simp
  intro j s hjs hind h
  specialize hind (by aesop)
  specialize h j (by aesop)
  simp only [hjs, not_false_eq_true, sum_insert]
  exact h.add_bil hind

theorem StieltjesIntegrable.finset_sum_bil {B : ι → E →L[ℝ] F →L[ℝ] G}
    (h : ∀ i ∈ s, StieltjesIntegrable a b (B i) f g) :
    StieltjesIntegrable a b (∑ i ∈ s, B i) f g :=
  (HasStieltjesIntegral.finset_sum_bil
    (fun i hi ↦ (h i hi).hasStieltjesIntegral)).stieltjesIntegrable

@[simp]
theorem stieltjesIntegral_finset_sum_bil {B : ι → E →L[ℝ] F →L[ℝ] G}
    (h : ∀ i ∈ s, StieltjesIntegrable a b (B i) f g) :
    ∫⟨∑ i ∈ s, B i⟩ x in a..b, f x ∂g = ∑ i ∈ s, ∫⟨B i⟩ x in a..b, f x ∂g :=
  (HasStieltjesIntegral.finset_sum_bil
    (fun i hi ↦ (h i hi).hasStieltjesIntegral)).stieltjesIntegral_eq

end Linearity


section Subinterval

/-! ### Integrability on subintervals -/

variable [CompleteSpace G] {f : ℝ → E} {g : ℝ → F} {a b c d : ℝ} {B : E →L[ℝ] F →L[ℝ] G}

private theorem StieltjesIntegrable'.to_subinterval
    (hab : a < b) (hcd : c < d) (hac : a ≤ c) (hdb : d ≤ b) (h : StieltjesIntegrable' a b B f g) :
    StieltjesIntegrable' c d B f g := by
  simp only [stieltjesIntegrable'_iff_integrable, isValue] at h ⊢
  exact .to_subbox h (by simp [hab, hcd, hac, hdb])

/-- If `f` is Stieltjes-integrable from `a` to `b` (with `a < b`) against `g`, then
it is also Stieltjes-integrable on any sub-interval of `(a, b]`. -/
theorem StieltjesIntegrable.to_subinterval (hab : a < b) (hc : c ∈ Set.Icc a b)
    (hd : d ∈ Set.Icc a b) (h : StieltjesIntegrable a b B f g) :
    StieltjesIntegrable c d B f g := by
  simp only [Set.mem_Icc] at hc hd
  simp only [of_lt, hab] at h
  rcases lt_trichotomy c d with hcd | rfl | hcd
  · simp only [hcd, of_lt]
    exact h.to_subinterval hab hcd hc.1 hd.2
  · simp
  symm
  simp only [hcd, of_lt]
  exact h.to_subinterval hab hcd hd.1 hc.2

theorem RiemannIntegrable.to_subinterval [CompleteSpace E] (hab : a < b)
    (hc : c ∈ Set.Icc a b) (hd : d ∈ Set.Icc a b) (h : RiemannIntegrable a b f) :
    RiemannIntegrable c d f := StieltjesIntegrable.to_subinterval hab hc hd h

end Subinterval

section Split
/-! ## Splitting over adjacent intervals -/

variable {f : ℝ → E} {g : ℝ → F} {L L' L'' : G} {a b c : ℝ}
  {B : E →L[ℝ] F →L[ℝ] G} [CompleteSpace G]

private theorem HasStieltjesIntegral'.add_adjacent (hab : a < b) (hbc : b < c)
    (h : StieltjesIntegrable' a c B f g)
    (h₁ : HasStieltjesIntegral' a b B f g L)
    (h₂ : HasStieltjesIntegral' b c B f g L') :
    HasStieltjesIntegral' a c B f g (L + L') := by
  simp only [HasStieltjesIntegral', StieltjesIntegrable'] at h h₁ h₂ ⊢
  have hac : a < c := hab.trans hbc
  have hb_mem : b ∈ Set.Ioo ((Ioc a c).lower 0) ((Ioc a c).upper 0) := by simp [hac, hab, hbc]
  refine HasIntegral.split 0 b ?_ ?_ h h₁ h₂
  · rw [Box.splitLower_def hb_mem, WithBot.coe_eq_coe]
    ext; simp [hac, hab]
  · rw [Box.splitUpper_def hb_mem, WithBot.coe_eq_coe]
    ext; simp [hac, hbc]

private theorem HasStieltjesIntegral.add_adjacent_prelim (hab : a < b) (hbc : b < c)
    (h₁ : HasStieltjesIntegral a b B f g L)
    (h₂ : HasStieltjesIntegral b c B f g L')
    (h₃ : HasStieltjesIntegral a c B f g L'') :
    L'' = L + L' := by
  apply unique h₃
  simp only [hab, of_lt, hbc, hab.trans hbc] at h₁ h₂ h₃ ⊢
  exact h₁.add_adjacent hab hbc ⟨L'', h₃⟩ h₂

/-- If `f` is Stieltjes-integrable from `a` to `c`, has Stieltjes integral `L` from `a` to `b`
and `L'` from `b` to `c` then `f` has Stieltjes integral `L + L'` from `a` to `c`.  No ordering
is assumed in `a`, `b`, `c` in the final statement of the theorem.

TODO: reduce the amount of case splitting in the proof. -/
theorem HasStieltjesIntegral.add_adjacent
    (h : StieltjesIntegrable a c B f g)
    (h₁ : HasStieltjesIntegral a b B f g L)
    (h₂ : HasStieltjesIntegral b c B f g L') :
    HasStieltjesIntegral a c B f g (L + L') := by
  have h₃ := h.hasStieltjesIntegral
  by_cases! hab : a = b
  · simp_all
  by_cases! hbc : b = c
  · simp_all
  by_cases! hac : a = c
  · simp_all; simp [h₁.unique h₂.symm]
  have h₁' := h₁.symm
  have h₂' := h₂.symm
  have h₃' := h₃.symm
  convert h₃
  rcases lt_or_gt_of_ne hab with hab | hba <;>
  rcases lt_or_gt_of_ne hbc with hbc | hcb <;>
  rcases lt_or_gt_of_ne hac with hac | hca <;>
  try order
  · simp_all [add_adjacent_prelim hab hbc h₁ h₂ h₃]
  · have := add_adjacent_prelim hac hcb h₃ h₂' h₁
    grind
  · have := add_adjacent_prelim hca hab h₃' h₁ h₂'
    grind
  · have := add_adjacent_prelim hba hac h₁' h₃ h₂
    grind
  · have := add_adjacent_prelim hbc hca h₂ h₃' h₁'
    grind
  · have := add_adjacent_prelim hcb hba h₂' h₁' h₃'
    grind

theorem HasRiemannIntegral.add_adjacent [CompleteSpace E] {M M' : E}
    (h : RiemannIntegrable a c f)
    (h₁ : HasRiemannIntegral a b f M)
    (h₂ : HasRiemannIntegral b c f M') :
    HasRiemannIntegral a c f (M + M') :=
  HasStieltjesIntegral.add_adjacent h h₁ h₂

theorem stieltjesIntegral.add_adjacent (h : StieltjesIntegrable a c B f g)
    (h₁ : StieltjesIntegrable a b B f g) (h₂ : StieltjesIntegrable b c B f g) :
    ∫⟨B⟩ x in a..c, f x ∂g = ∫⟨B⟩ x in a..b, f x ∂g + ∫⟨B⟩ x in b..c, f x ∂g :=
  (HasStieltjesIntegral.add_adjacent h h₁.hasStieltjesIntegral
    h₂.hasStieltjesIntegral).stieltjesIntegral_eq

/- TODO: A gluing theorem: if the Stieltjes integral is well-defined on `a..b` and `b..c`, then it
is well-defined in `a..c`. -/

end Split
/-! ## Main theorems -/

/-- For any valid box partition of (a, b], the sum of the norm of the
differential `ofDiff g` is bounded by the total variation of g on the interval. -/
private lemma sum_norm_ofDiff_le_norm_mul_eVariationOn {a b : ℝ} (g : ℝ → F)
    (hg : BoundedVariationOn g (.Icc a b))
    (π : Prepartition (Ioc a b)) :
    ∑ J ∈ π.boxes, ‖(BoxAdditiveMap.ofDiff (B.flip <| g ·)) J‖ ≤
      ‖B‖ * (eVariationOn g (Set.Icc a b)).toReal := by

  -- Step 1: Bound each local subbox evaluation by the operator norm of B.flip
  have h_term : ∀ J ∈ π.boxes, ‖(BoxAdditiveMap.ofDiff (B.flip <| g ·)) J‖ ≤
      ‖B‖ * ‖g (J.upper 0) - g (J.lower 0)‖ := by
    intro J hJ
    change ‖B.flip (g (J.upper 0)) - B.flip (g (J.lower 0))‖ ≤ _
    rw [← map_sub, ← opNorm_flip B]
    exact (B.flip).le_opNorm (g (J.upper 0) - g (J.lower 0))

  -- Step 2: Apply bound term-wise to sum and cancel operator norm
  refine (Finset.sum_le_sum h_term).trans ?_
  rw [← Finset.mul_sum]
  gcongr

  -- Step 3: Upgrade to ENNReal and convert vector norms cleanly to `edist`
  have h_sum_eq : ∑ J ∈ π.boxes, ‖g (J.upper 0) - g (J.lower 0)‖ =
      (ENNReal.ofReal (∑ J ∈ π.boxes, ‖g (J.upper 0) - g (J.lower 0)‖)).toReal :=
    (ENNReal.toReal_ofReal (Finset.sum_nonneg fun _ _ ↦ norm_nonneg _)).symm
  rw [h_sum_eq]
  refine ENNReal.toReal_mono (by exact hg) ?_
  rw [ENNReal.ofReal_sum_of_nonneg (fun _ _ ↦ norm_nonneg _)]
  simp_rw [← dist_eq_norm, ← edist_dist]

  sorry

/-- Continuous integrand and a
bounded-variation integrator give an integrable Riemann-Stieltjes box integrand. -/
private lemma integrable_of_continuousOn_of_boundedVariationOn [CompleteSpace G]
   {a b : ℝ} {f : ℝ → E} {g : ℝ → F} (hab : a < b) (l : IntegrationParams)
    (hf : ContinuousOn f (.Icc a b)) (hg : BoundedVariationOn g (.Icc a b)) :
    Integrable (Ioc a b) l
      (fun x ↦ f (x 0)) (BoxAdditiveMap.ofDiff (B.flip <| g ·)) := by
  let f' := fun x : Fin 1 → ℝ ↦ f (x 0)
  refine integrable_iff_cauchy_basis.2 fun ε hε ↦ ?_
  let V : ℝ := (eVariationOn g (.Icc a b)).toReal
  rcases exists_pos_mul_lt hε (‖B‖ * V) with ⟨η, hη, hηC⟩
  obtain ⟨δ, hδ, hδf⟩ := hf.metric_uniform η hη
  refine ⟨fun _ _ ↦ ⟨δ/4, by grind⟩, fun _ _ _ ↦ by rfl, fun _ _ π₁ π₂ hπ₁ hpart₁ hπ₂ hpart₂ ↦ ?_⟩
  let vol := BoxAdditiveMap.ofDiff (B.flip <| g ·)
  let π := π₁.toPrepartition ⊓ π₂.toPrepartition
  let τ₁ := π₁.infPrepartition π₂.toPrepartition
  let τ₂ := π₂.infPrepartition π₁.toPrepartition
  have hdiff : integralSum f' vol π₁ - integralSum f' vol π₂ =
      ∑ J ∈ π.boxes, (vol J (f (τ₁.tag J 0)) - vol J (f (τ₂.tag J 0))) := by
    simpa [vol, π, τ₁, τ₂] using integralSum_sub_partitions f' vol hpart₁ hpart₂
  have hterm : ∀ J ∈ π.boxes, ‖vol J (f (τ₁.tag J 0)) - vol J (f (τ₂.tag J 0))‖ ≤ ‖vol J‖ * η := by
    intro J hJ
    have hJτ₁ : J ∈ τ₁.toPrepartition := by simpa [π, τ₁] using hJ
    have := τ₁.tag_mem_Icc J
    have := τ₂.tag_mem_Icc J
    have hτ₁_upper : |τ₁.tag J 0 - J.upper 0| ≤ δ/4 := by
      simpa [mem_closedBall, dist_pi_le_iff', Real.dist_eq, abs_sub_comm]
        using hπ₁.isSubordinate.infPrepartition _ J hJτ₁ J.upper_mem_Icc
    have hτ₂_upper : |J.upper 0 - τ₂.tag J 0| ≤ δ/4 := by
      simpa [mem_closedBall, dist_pi_le_iff', Real.dist_eq]
        using hπ₂.isSubordinate.infPrepartition _ J
          (mem_infPrepartition_comm.mp hJτ₁) J.upper_mem_Icc
    grw [← map_sub, (vol J).le_opNorm]
    gcongr
    apply (hδf _ (by simp_all) _ (by simp_all) _).le
    linarith [abs_sub_le (τ₁.tag J 0) (J.upper 0) (τ₂.tag J 0)]
  calc
    dist (integralSum f' vol π₁) (integralSum f' vol π₂)
      = ‖∑ J ∈ π.boxes, (vol J (f (τ₁.tag J 0)) - vol J (f (τ₂.tag J 0)))‖ := by
      simp [dist_eq_norm, hdiff]
    _ ≤ (‖B‖ * V) * η := by
      grw [norm_sum_le, sum_le_sum hterm, ← sum_mul]; gcongr
      exact sum_norm_ofDiff_le_norm_mul_eVariationOn B g hg π
    _ ≤ ε := by grind

/-- Theorem A.1 of Montgomery-Vaughan: a continuous integrand and a bounded-variation integrator
have a Riemann-Stieltjes integral. -/
theorem exists_of_continuousOn_of_boundedVariationOn [CompleteSpace G] {a b : ℝ}
    {f : ℝ → E} {g : ℝ → F} (hab : a < b)
    (hf : ContinuousOn f (.Icc a b)) (hg : BoundedVariationOn g (.Icc a b)) :
    StieltjesIntegrable a b B f g := by
  obtain ⟨L, hL⟩ := integrable_of_continuousOn_of_boundedVariationOn B
    hab IntegrationParams.Riemann hf hg
  use L
  simp [HasStieltjesIntegral, HasStieltjesIntegral', hab.ne, hab, hL]

/-- given an interval [a,b], if c,d ∈ [a,b], then |c - d| < b -a -/
lemma dist_mem_Icc_le {a b m n : ℝ} (hm : m ∈ Set.Icc a b)
  (hn : n ∈ Set.Icc a b) : |m - n| ≤ b - a := by grind [Real.dist_eq]

/-- Lemma for a vector valued MVT with error since MVT is false for a general
funcion in higher dimensions, but is true up to some error for higher dimensions.
This lemma is used in the proof of Theorem A3 (a).

For g C^1[a,b] and ε > 0, there is a δ > 0 such that for all a ≤ a' < b' ≤ b with
b' - a' < δ, we have that for all c ∈ [a',b'] that
‖g(b')-g(a')‖ ≤ ‖g'(c)‖ * (b' - a') + ε * (b' - a')
-/
lemma MVT_with_error [CompleteSpace F] {g : ℝ → F} {a b ε : ℝ}
  (hab : a < b) (hg : ContDiffOn ℝ 1 g (.Icc a b)) (hε : 0 < ε)
  : ∃ δ > 0, ∀ a' ∈ Set.Icc a b, ∀ b' ∈ Set.Icc a b,
  |b' - a'| < δ → ∀ c ∈ Set.uIcc a' b', dist (g b' -g a')
    ((b' - a') • (derivWithin g (.Icc a b)) c) ≤ ε * |b' - a'| := by
  set g' := derivWithin g (.Icc a b)
  have hderiv_cont := hg.continuousOn_derivWithin (uniqueDiffOn_Icc hab) le_rfl
  obtain ⟨δ, hδ_pos, hδ_prop⟩ := hderiv_cont.metric_uniform ε (by positivity)
  refine ⟨δ, hδ_pos, fun a' _ b' _ _ c hc ↦ ?_⟩
  by_cases! ha'b' : a' = b'
  · simp [ha'b']
  have hIcc_subset : Set.uIcc a' b' ⊆ .Icc a b := by intro; simp [Set.mem_uIcc]; grind
  have h_ftc := calc
     g b' - g a' = ∫ x in a'..b', g' c + (g' x - g' c) := by
      rw [← integral_derivWithin_uIcc_of_contDiffOn_uIcc (hg.mono hIcc_subset)]
      apply integral_congr
      intro x hx
      simp only [add_sub_cancel]
      exact derivWithin_subset hIcc_subset (uniqueDiffOn_Icc (by grind) x hx)
        (hg.differentiableOn one_ne_zero x (hIcc_subset hx))
     _ = (∫ x in a'..b', g' c) + (∫ x in a'..b', (g' x - g' c)) := by
      rw [intervalIntegral.integral_add intervalIntegrable_const]
      exact (hderiv_cont.mono hIcc_subset).intervalIntegrable.sub
        intervalIntegrable_const
  simp only [h_ftc, intervalIntegral.integral_const, dist_self_add_left, ge_iff_le]
  apply norm_integral_le_of_norm_le_const
  intro x hx
  apply (hδ_prop _ (hIcc_subset ⟨hx.1.le, hx.2⟩) _ (hIcc_subset hc) _).le
  grw [dist_mem_Icc_le ⟨hx.1.le, hx.2⟩ hc]; grind

/-- Lemma MVT version using a bilinear form, this theorem is used in the proof of Theorem A3 (b)
Since the MVT is false in general (for higher dimensions), we prove a version where it is true up
to some error term.

For g : ℝ → F and f : ℝ → E, and B a bounded blinear from from E × F → G where E, F, and G are
normed. Then if g is C^1[a,b], and f is bounded on [a,b], then for any ε > 0, there is a δ > 0 such
that for all a',b' with a ≤ a' < b' ≤ b, we have for all c ∈ [a',b'] that
‖B(f(c),g(b') - g(a'))‖ ≤ ‖B(f(c),g'(c))‖ (b' - a') + ε (b' - a')
We remark that the theorem is most powerful when we take a' = a and b' = b. Since this is used to
say that if the mesh is fine enough (of size < δ), then we have this MVT with small error.

Remark: In the use of MV theorem A3, they assume that f is Riemann integrable on [a,b], and use the
fact that this will imply that f is bounded. However, for the MVT statement, we need only that f is
bounded.
-/
lemma MVT_with_bilinear_form_and_error [CompleteSpace F] {f : ℝ → E} {g : ℝ → F} {a b ε : ℝ}
  (B : E →L[ℝ] F →L[ℝ] G) (hab : a < b) (hg : ContDiffOn ℝ 1 g (.Icc a b)) (hε : 0 < ε)
  (f_bounded : ∃ M > 0, ∀ x ∈ Set.Icc a b, ‖f x‖ < M) : ∃ δ > 0, ∀ a' ≥ a, ∀ b' ≤ b,
  a' < b' → b' - a' < δ → ∀ c ∈ Set.Icc a' b', ‖B (f c) (g b' -g a')‖
    ≤ ‖B (f c) (derivWithin g (.Icc a b) c)‖ * (b' - a') + ε * (b' - a') := by
  by_cases! hB : B = 0
  · use 1; simp only [gt_iff_lt, zero_lt_one, ge_iff_le, Set.mem_Icc, hB, zero_apply, norm_zero,
    zero_mul, zero_add, and_imp, true_and]; intros; positivity
  obtain ⟨M, hM_pos, hM_bound⟩ := f_bounded
  have hB_norm_pos : 0 < ‖B‖ := norm_pos_iff.mpr hB
  obtain ⟨ δ, hδ_pos, hδ_prop⟩ := MVT_with_error hab hg (show 0 < ε / (‖B‖ * M) by positivity)
  use δ, hδ_pos
  intros a' _ b' _ h_a'b' _ c hc
  specialize hδ_prop a' (by grind) b' (by grind) (by grind) c
    (by simpa [Set.uIcc_of_lt h_a'b'] using hc)
  rw [dist_eq_norm] at hδ_prop
  have : |b'-a'| = b' - a' := abs_of_pos (by positivity)
  calc
    _ = ‖B (f c) ((b' - a') • derivWithin g (.Icc a b) c)
      + B (f c) (g b' - g a' - (b' - a') • derivWithin g (.Icc a b) c)‖ := by simp
    _ ≤ ‖B (f c) ((b' - a') • derivWithin g (.Icc a b) c)‖
      + ‖B (f c) (g b' - g a' - (b' - a') • derivWithin g (.Icc a b) c)‖ := by apply norm_add_le
    _ ≤ _ := by
      simp only [map_smul, norm_smul, Real.norm_eq_abs, this, mul_comm,
        add_le_add_iff_left]
      grw [B.le_opNorm₂ (f c) _, hδ_prop, hM_bound _ (by grind), this]
      field_simp; order

/-- Theorem A.3 (a).  If g′ is continuous on [a, b], then
Varₐᵇ g = ∫ₐᵇ ‖g′(x)‖ dx.
-/
theorem variation_of_derivative {a b : ℝ} {g : ℝ → F} (hab : a < b)
    (hg : ContDiffOn ℝ 1 g (.Icc a b)) :
    (eVariationOn g (.Icc a b)).toReal = ∫ x in a..b, ‖deriv g x‖ := by sorry

/-- Theorem A.3 (b).  If g′ is continuous on [a, b] and if in addition f is
Riemann integrable, then ∫ₐᵇ f(x) dg(x) = ∫ₐᵇ f(x) g′(x) dx. -/
theorem integral_of_derivative {a b : ℝ} {f : ℝ → E} {g : ℝ → F} (hab : a < b)
    (hg : ContDiffOn ℝ 1 g (.Icc a b))
    (hf : RiemannIntegrable a b f) :
    HasStieltjesIntegral a b B f g (∫ x in a..b, B (f x) (deriv g x)) := by sorry

/-- Theorem A.4. Suppose that g has bounded variation, and put g∗(x) = Varₐˣ g. Then
‖∫ₐᵇ f(x) dg(x)‖ ≤ ∫ₐᵇ ‖f(x)‖ dg∗(x),
provided that both integrals exist. -/
theorem integral_le_integral_of_variation {a b : ℝ} {B : E →L[ℝ] F →L[ℝ] G}
    {f : ℝ → E} {g : ℝ → F} {L : G} {L' : ℝ}
    (hab : a < b) (hg : BoundedVariationOn g (.Icc a b))
    (hfg : HasStieltjesIntegral a b B f g L)
    (hfabs_gstar : HasStieltjesIntegral a b (mul ℝ ℝ) (‖f ·‖)
      (fun x ↦ (eVariationOn g (.Icc a x)).toReal) L') :
    ‖L‖ ≤ ‖B‖ * L' := by sorry

def boxLexKey (J : Box (Fin 1)) : ℝ ×ₗ ℝ :=
  toLex (J.lower 0, J.upper 0)

lemma boxLexKey_injective : Function.Injective boxLexKey := by
  intro J K h
  ext x
  have h_lower : J.lower 0 = K.lower 0 := by
    have := congrArg (fun p : ℝ ×ₗ ℝ ↦ (ofLex p).1) h
    simpa [boxLexKey] using this
  have h_upper : J.upper 0 = K.upper 0 := by
    have := congrArg (fun p : ℝ ×ₗ ℝ ↦ (ofLex p).2) h
    simpa [boxLexKey] using this
  simp [Box.mem_def, Fin.forall_fin_one, h_lower, h_upper]

instance instIsTransBoxLexKey :
    IsTrans (Box (Fin 1)) (fun J K ↦ boxLexKey J ≤ boxLexKey K) :=
  ⟨fun _ _ _ h₁ h₂ ↦ le_trans h₁ h₂⟩

instance instIsAntisymmBoxLexKey :
    IsAntisymm (Box (Fin 1)) (fun J K ↦ boxLexKey J ≤ boxLexKey K) :=
  ⟨fun _ _ h₁ h₂ ↦ boxLexKey_injective (le_antisymm h₁ h₂)⟩

instance instIsTotalBoxLexKey :
    IsTotal (Box (Fin 1)) (fun J K ↦ boxLexKey J ≤ boxLexKey K) :=
  ⟨fun _ _ ↦ le_total _ _⟩

instance instIsReflBoxLexKey :
    IsRefl (Box (Fin 1)) (fun J K ↦ boxLexKey J ≤ boxLexKey K) :=
  ⟨fun _ ↦ le_rfl⟩


/-- Disjoint one-dimensional boxes have disjoint underlying real half-open intervals. -/
lemma disjoint_Ioc_of_disjoint_box {J K : Box (Fin 1)}
    (h : Disjoint (J : Set (Fin 1 → ℝ)) K) :
    Disjoint (Set.Ioc (J.lower 0) (J.upper 0)) (Set.Ioc (K.lower 0) (K.upper 0)) := by
  rw [Set.disjoint_left]
  intro x hxJ hxK
  have hxJ' : (fun _ : Fin 1 ↦ x) ∈ J := by
    simpa [Box.mem_def, Fin.forall_fin_one] using hxJ
  have hxK' : (fun _ : Fin 1 ↦ x) ∈ K := by
    simpa [Box.mem_def, Fin.forall_fin_one] using hxK
  exact h.le_bot ⟨hxJ', hxK'⟩

/-- If two disjoint one-dimensional boxes are ordered by lower endpoint, then the first lies to the
left of the second. -/
lemma upper_le_lower_of_disjoint_box_of_lower_le {J K : Box (Fin 1)}
    (hdisj : Disjoint (J : Set (Fin 1 → ℝ)) K) (hlower : J.lower 0 ≤ K.lower 0) :
    J.upper 0 ≤ K.lower 0 := by
  have hd := disjoint_Ioc_of_disjoint_box hdisj
  have h := (Set.Ioc_disjoint_Ioc).1 hd
  rw [max_eq_right hlower] at h
  rcases min_le_iff.mp h with hju | hku
  · exact hju
  · exact (K.lower_lt_upper 0).not_ge hku |>.elim

omit [NormedSpace ℝ F] in
/-- The sum of variations over a list of ordered one-dimensional boxes is bounded by the
variation over their union. -/
lemma list_sum_eVariationOn_Icc_le_iUnion (g : ℝ → F) :
    ∀ L : List (Box (Fin 1)),
      L.Pairwise (fun J K ↦ J.upper 0 ≤ K.lower 0) →
      (L.map fun J ↦ eVariationOn g (Set.Icc (J.lower 0) (J.upper 0))).sum ≤
        eVariationOn g {x | ∃ J ∈ L, x ∈ Set.Icc (J.lower 0) (J.upper 0)}
  | [], _ => by simp
  | J :: L, hpair => by
      rw [List.pairwise_cons] at hpair
      rcases hpair with ⟨hhead, htail⟩
      have ih := list_sum_eVariationOn_Icc_le_iUnion g L htail
      let Utail : Set ℝ := {x | ∃ K ∈ L, x ∈ Set.Icc (K.lower 0) (K.upper 0)}
      have hleft : ∀ x ∈ Set.Icc (J.lower 0) (J.upper 0), ∀ y ∈ Utail, x ≤ y := by
        intro x hx y hy
        rcases hy with ⟨K, hK, hyK⟩
        exact hx.2.trans ((hhead K hK).trans hyK.1)
      have hU : Set.Icc (J.lower 0) (J.upper 0) ∪ Utail =
          {x | ∃ K ∈ J :: L, x ∈ Set.Icc (K.lower 0) (K.upper 0)} := by
        ext x
        simp [Utail]
      calc
        (List.map (fun J ↦ eVariationOn g (Set.Icc (J.lower 0) (J.upper 0)))
              (J :: L)).sum =
            eVariationOn g (Set.Icc (J.lower 0) (J.upper 0)) +
              (L.map fun J ↦ eVariationOn g (Set.Icc (J.lower 0) (J.upper 0))).sum := by
          simp
        _ ≤ eVariationOn g (Set.Icc (J.lower 0) (J.upper 0)) + eVariationOn g Utail := by
          simpa [add_comm, add_left_comm, add_assoc] using add_le_add_left ih _
        _ ≤ eVariationOn g (Set.Icc (J.lower 0) (J.upper 0) ∪ Utail) :=
          eVariationOn.add_le_union g hleft
        _ = eVariationOn g {x | ∃ K ∈ J :: L,
              x ∈ Set.Icc (K.lower 0) (K.upper 0)} := by
          rw [hU]

/-- Sorting the boxes of a one-dimensional prepartition by lower endpoint puts each box to the
left of all later boxes. -/
lemma sorted_boxes_pairwise_upper_le_lower {I : Box (Fin 1)} (π : Prepartition I) :
    (π.boxes.sort (fun J K ↦ boxLexKey J ≤ boxLexKey K)).Pairwise
      (fun J K ↦ J.upper 0 ≤ K.lower 0) := by
  let L := π.boxes.sort (fun J K ↦ boxLexKey J ≤ boxLexKey K)
  have hsort : L.Pairwise (fun J K ↦ boxLexKey J ≤ boxLexKey K) := Finset.pairwise_sort _ _
  have hnodup : L.Nodup := Finset.sort_nodup _ _
  rw [List.pairwise_iff_get]
  intro i j hij
  have hlex : boxLexKey (L.get i) ≤ boxLexKey (L.get j) := hsort.rel_get_of_lt hij
  have hlower : (L.get i).lower 0 ≤ (L.get j).lower 0 :=
    Prod.Lex.monotone_fst _ _ hlex
  have hne : L.get i ≠ L.get j := by
    exact fun h ↦ (Nat.ne_of_lt hij) (Fin.val_eq_of_eq ((hnodup.get_inj_iff).1 h))
  have hmemi : L.get i ∈ π.boxes := by
    exact (Finset.mem_sort (fun J K ↦ boxLexKey J ≤ boxLexKey K)).1 (List.get_mem L i)
  have hmemj : L.get j ∈ π.boxes := by
    exact (Finset.mem_sort (fun J K ↦ boxLexKey J ≤ boxLexKey K)).1 (List.get_mem L j)
  exact upper_le_lower_of_disjoint_box_of_lower_le (π.disjoint_coe_of_mem hmemi hmemj hne)
    hlower

lemma Icc_subset_of_box_le_Ioc {J : Box (Fin 1)} (hab : a < b) (hJ : J ≤ Ioc a b) :
    Set.Icc (J.lower 0) (J.upper 0) ⊆ Set.Icc a b := by
  have hla : a ≤ J.lower 0 := by
    simpa [Ioc.lower hab] using Box.antitone_lower hJ 0
  have hub : J.upper 0 ≤ b := by
    simpa [Ioc.upper hab] using Box.monotone_upper hJ 0
  intro x hx
  exact ⟨hla.trans hx.1, hx.2.trans hub⟩

omit [NormedSpace ℝ F] in
/-- The total variation over the boxes of a one-dimensional prepartition is bounded by the
variation on the ambient interval. -/
lemma sum_eVariationOn_Icc_le_eVariationOn (g : ℝ → F) (hab : a < b)
    (π : Prepartition (Ioc a b)) :
    ∑ J ∈ π.boxes, eVariationOn g (Set.Icc (J.lower 0) (J.upper 0)) ≤
      eVariationOn g (Set.Icc a b) := by
  let L := π.boxes.sort (fun J K ↦ boxLexKey J ≤ boxLexKey K)
  have hpair : L.Pairwise (fun J K ↦ J.upper 0 ≤ K.lower 0) :=
    sorted_boxes_pairwise_upper_le_lower π
  have hlist := list_sum_eVariationOn_Icc_le_iUnion g L hpair
  have hsub : {x | ∃ J ∈ L, x ∈ Set.Icc (J.lower 0) (J.upper 0)} ⊆ Set.Icc a b := by
    intro x hx
    rcases hx with ⟨J, hJL, hxJ⟩
    have hJπ : J ∈ π.boxes :=
      (Finset.mem_sort (fun J K ↦ boxLexKey J ≤ boxLexKey K)).1 hJL
    exact Icc_subset_of_box_le_Ioc a b hab (π.le_of_mem hJπ) hxJ
  calc
    ∑ J ∈ π.boxes, eVariationOn g (Set.Icc (J.lower 0) (J.upper 0)) =
        (L.map fun J ↦ eVariationOn g (Set.Icc (J.lower 0) (J.upper 0))).sum := by
      rw [← Multiset.sum_coe, ← Multiset.map_coe, Finset.sort_eq]
      rfl
    _ ≤ eVariationOn g {x | ∃ J ∈ L, x ∈ Set.Icc (J.lower 0) (J.upper 0)} := hlist
    _ ≤ eVariationOn g (Set.Icc a b) := eVariationOn.mono g hsub

omit [NormedSpace ℝ F] in
/-- Real-valued form of `sum_eVariationOn_Icc_le_eVariationOn` under finite total variation. -/
lemma sum_eVariationOn_Icc_toReal_le_eVariationOn (g : ℝ → F) (hab : a < b)
    (hg : BoundedVariationOn g (Set.Icc a b)) (π : Prepartition (Ioc a b)) :
    ∑ J ∈ π.boxes, (eVariationOn g (Set.Icc (J.lower 0) (J.upper 0))).toReal ≤
      (eVariationOn g (Set.Icc a b)).toReal := by
  have hfin : ∀ J ∈ π.boxes, eVariationOn g (Set.Icc (J.lower 0) (J.upper 0)) ≠ ⊤ := by
    intro J hJ
    exact hg.mono (Icc_subset_of_box_le_Ioc a b hab (π.le_of_mem hJ))
  rw [← ENNReal.toReal_sum hfin]
  exact ENNReal.toReal_mono hg (sum_eVariationOn_Icc_le_eVariationOn a b g hab π)


end BoxIntegral
